The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraReader.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraReader.cc File Reference
#include <vector>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <list>
#include "CassandraReader.hh"
Functions
list< string > tokenise (const string &line)
void processData (SparseMatrix &m, istream &matrixData)
void processData (SparseMatrix &m, int b, list< string >::iterator s, list< string >::iterator e)
void processData (SparseMatrix &m, int b, istream &matrixData)
void processData (SparseMatrix &m, int b, int c, string value)
void processData (SparseMatrix &m, int b, int c, istream &matrixData)
int toIndex (map< string, int > map, string potentialIndex)
Cassandra * readCassandra (ifstream &file)
Function Documentation
void processData (SparseMatrix & m, int b, int c, istream & matrixData)
Definition at line 111 of file CassandraReader.cc.
References mergeProcessorOptimisatorOutput::line, processData(), and tokenise().
void processData (SparseMatrix & m, int b, int c, string value)
Definition at line 96 of file CassandraReader.cc.
References sumAndPlot::i, sumAndPlot::m, and processData().
void processData (SparseMatrix & m, int b, istream & matrixData)
Definition at line 85 of file CassandraReader.cc.
References mergeProcessorOptimisatorOutput::line, processData(), and tokenise().
void processData (SparseMatrix & m, int b, list< string >::iterator s, list< string >::iterator e)
Definition at line 70 of file CassandraReader.cc.
References sumAndPlot::i, sumAndPlot::m, and processData().
void processData (SparseMatrix & m, istream & matrixData)
Definition at line 38 of file CassandraReader.cc.
References sumAndPlot::i, mergeProcessorOptimisatorOutput::line, sumAndPlot::m, sumAndPlot::min, and tokenise().
Referenced by processData(), and readCassandra().
Cassandra* readCassandra (ifstream & file)
Definition at line 130 of file CassandraReader.cc.
Referenced by main().
int toIndex (map< string, int > map, string potentialIndex)
Definition at line 122 of file CassandraReader.cc.
Referenced by readCassandra().
list<string> tokenise (const string & line)
Definition at line 21 of file CassandraReader.cc.
Referenced by processData(), and readCassandra().