The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/PSRTest/PSRTest.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/PSRTest/PSRTest.cc File Reference
#include "PGBasics.hh"
#include "Sequence.hh"
#include "LookupTable.hh"
#include "LookupTableBatch.hh"
#include "NeuralNet.hh"
#include "NeuralNetBatch.hh"
#include "PSRTransform.hh"
#include "BasicController.hh"
#include "BinaryController.hh"
#include "OLPomdp.hh"
Defines
#define DISCOUNT 0.90
#define TD_DISCOUNT 0.9
#define PSR_STEP_SIZE 0.25
#define STEP_SIZE 0.001
#define STEPS_PER_EPOCH 100
#define MAX_STEPS 0
#define MAX_TIME 0
#define TEST_RUNS 1
#define NN_LAYERS 2
#define PARAM_FILE "PSRTest.params"
#define MAX_RAND_PARAM 0.00
#define MAX_HISTORY 1000
#define MAX_CORE_TESTS 10
#define MIN_KAPPA_FOR_CORE 20.0
#define PASSES_BEFORE_ADDCORES 5
Functions
int main (int argc, char **argv)
Define Documentation
#define DISCOUNT 0.90
Definition at line 16 of file PSRTest.cc.
#define MAX_CORE_TESTS 10
Definition at line 28 of file PSRTest.cc.
#define MAX_HISTORY 1000
Definition at line 27 of file PSRTest.cc.
#define MAX_RAND_PARAM 0.00
Definition at line 26 of file PSRTest.cc.
#define MAX_STEPS 0
Definition at line 21 of file PSRTest.cc.
#define MAX_TIME 0
Definition at line 22 of file PSRTest.cc.
#define MIN_KAPPA_FOR_CORE 20.0
Definition at line 29 of file PSRTest.cc.
#define NN_LAYERS 2
Definition at line 24 of file PSRTest.cc.
#define PARAM_FILE "PSRTest.params"
Definition at line 25 of file PSRTest.cc.
#define PASSES_BEFORE_ADDCORES 5
Definition at line 30 of file PSRTest.cc.
#define PSR_STEP_SIZE 0.25
Definition at line 18 of file PSRTest.cc.
#define STEP_SIZE 0.001
Definition at line 19 of file PSRTest.cc.
#define STEPS_PER_EPOCH 100
Definition at line 20 of file PSRTest.cc.
#define TD_DISCOUNT 0.9
Definition at line 17 of file PSRTest.cc.
#define TEST_RUNS 1
Definition at line 23 of file PSRTest.cc.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 32 of file PSRTest.cc.
References ACTIONS, APPROX_OUTPUTS, DISCOUNT, sumAndPlot::i, libpg::RLAlg::learn(), MAX_CORE_TESTS, MAX_HISTORY, MAX_RAND_PARAM, MAX_STEPS, MAX_TIME, MIN_KAPPA_FOR_CORE, NN_LAYERS, PARAM_FILE, PASSES_BEFORE_ADDCORES, PSR_STEP_SIZE, libpg::Controller::randomizeParams(), libpg::RLAlg::saveBest(), libpg::RLAlg::setUseAutoBaseline(), STEP_SIZE, STEPS_PER_EPOCH, SYMBOLS, and TEST_RUNS.