The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/TaoProject/ThreeStateTest.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/TaoProject/ThreeStateTest.cc File Reference
#include <PGBasics.hh>
#include "ThreeState.hh"
#include "LookupTable.hh"
#include "LookupTableBatch.hh"
#include "NeuralNet.hh"
#include "NeuralNetBatch.hh"
#include "NACTransform.hh"
#include "SoftmaxPolicy.hh"
#include "eGreedyPolicy.hh"
#include "BasicController.hh"
#include "BinaryController.hh"
#include "ValueController.hh"
#include "SARSAController.hh"
#include "QLearningController.hh"
#include "FactoredController.hh"
#include "LSPIController.hh"
#include "OLBFGS.hh"
#include "OLPomdp.hh"
#include "GPomdp.hh"
#include "LineSearchAlg.hh"
Classes
class Temp
class EpsilonDecay
Defines
#define TD_DISCOUNT 0.6
#define STEPS_PER_EPOCH 10000
#define MAX_STEPS 1000000
#define MAX_TIME 0
#define TEST_RUNS 1
#define NN_LAYERS 2
#define PARAM_FILE "ThreeState.params"
#define MAX_RAND_PARAM 0.00
#define APPROX_OUTPUTS 2
#define LINE_SEARCH_STEPS 20
#define TOLERANCE 1e-9
#define BACKOFF 3.0
#define EXPONENT_BASE 2.0
#define MAX_TRIES 16
#define DOWNHILL_THRESH 0.05
#define commonInit()
Functions
template<class Controller>
void ExploreeGreedyKnobs (int max_time, int max_steps)
template<class Controller>
void ExploreSoftmaxKnobs (int max_time, int max_steps)
void ExploreBinaryControllerKnobs (int max_time, int max_steps)
void ExploreFactoredBinaryControllersKnobs (int max_time, int max_steps)
OLPomdp * SARSA_NeuralNet_Softmax_Decaying ()
OLPomdp * LSPI_NeuralNet_Softmax_Decaying ()
OLPomdp * LSPI_NeuralNet_Uniform_Random ()
OLPomdp * SARSA_NeuralNet_eGreedy_Constant ()
OLPomdp * SARSA_NeuralNet_eGreedy_Decaying ()
OLPomdp * QLearning_NeuralNet_Softmax_Decaying ()
OLPomdp * QLearning_NeuralNet_eGreedy_Constant ()
OLPomdp * QLearning_NeuralNet_eGreedy_Decaying ()
OLPomdp * Basic_NeuralNet ()
OLPomdp * NACTransform_Binary_NeuralNet ()
OLPomdp * OLBFGS_NeuralNet ()
OLPomdp * Factored_Binary_NeuralNet ()
int main (int argc, char **argv)
Define Documentation
#define APPROX_OUTPUTS 2
Definition at line 39 of file ThreeStateTest.cc.
#define BACKOFF 3.0
Definition at line 42 of file ThreeStateTest.cc.
#define commonInit ()
Value:
Vector nnDims(NN_LAYERS); \
    nnDims[0] = OBS_DIM; \
    nnDims[1] = APPROX_OUTPUTS; \
    Vector squash(NN_LAYERS); \
    squash.clear();
Definition at line 288 of file ThreeStateTest.cc.
Referenced by Basic_NeuralNet(), Factored_Binary_NeuralNet(), LSPI(), LSPI_NeuralNet_Softmax_Decaying(), LSPI_NeuralNet_Uniform_Random(), LSTDQ_NeuralNet_Softmax_Decaying(), NACTransform_Binary_NeuralNet(), OLBFGS_NeuralNet(), QLearning_NeuralNet_eGreedy_Constant(), QLearning_NeuralNet_eGreedy_Decaying(), QLearning_NeuralNet_Softmax_Decaying(), SARSA_NeuralNet_eGreedy_Constant(), SARSA_NeuralNet_eGreedy_Decaying(), and SARSA_NeuralNet_Softmax_Decaying().
#define DOWNHILL_THRESH 0.05
Definition at line 45 of file ThreeStateTest.cc.
#define EXPONENT_BASE 2.0
Definition at line 43 of file ThreeStateTest.cc.
#define LINE_SEARCH_STEPS 20
Definition at line 40 of file ThreeStateTest.cc.
#define MAX_RAND_PARAM 0.00
Definition at line 38 of file ThreeStateTest.cc.
#define MAX_STEPS 1000000
Definition at line 33 of file ThreeStateTest.cc.
#define MAX_TIME 0
Definition at line 34 of file ThreeStateTest.cc.
#define MAX_TRIES 16
Definition at line 44 of file ThreeStateTest.cc.
#define NN_LAYERS 2
Definition at line 36 of file ThreeStateTest.cc.
#define PARAM_FILE "ThreeState.params"
Definition at line 37 of file ThreeStateTest.cc.
#define STEPS_PER_EPOCH 10000
Definition at line 32 of file ThreeStateTest.cc.
#define TD_DISCOUNT 0.6
Definition at line 31 of file ThreeStateTest.cc.
#define TEST_RUNS 1
Definition at line 35 of file ThreeStateTest.cc.
#define TOLERANCE 1e-9
Definition at line 41 of file ThreeStateTest.cc.
Function Documentation
OLPomdp* Basic_NeuralNet ()
Binary controller with neural net function approximator.
Returns:
OLPomdp agent
Definition at line 515 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), and mergeProcessorOptimisatorOutput::step_size.
Referenced by main().
void ExploreBinaryControllerKnobs (int max_time, int max_steps)
This function tries to find the best combination of step size and discount. It is specific to tune Binary Controller, but it can be generalized.
Parameters:
max_time time limit (0 for no limit [default])
max_steps steps (0 for no limit [default])
Definition at line 203 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, libpg::RLAlg::learn(), NN_LAYERS, OBS_DIM, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and STEPS_PER_EPOCH.
template<class Controller> void ExploreeGreedyKnobs (int max_time, int max_steps)
This function tries to find the best combination of step size, Epsilon and discount. It is specific to tune a Controller with e-greedy policy, but it can be generalized.
Parameters:
max_time time limit (0 for no limit [default])
max_steps steps (0 for no limit [default])
Definition at line 102 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, libpg::RLAlg::learn(), NN_LAYERS, OBS_DIM, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, STEPS_PER_EPOCH, and TD_DISCOUNT.
void ExploreFactoredBinaryControllersKnobs (int max_time, int max_steps)
This function tries to find the best combination of step size and discount. It is specific to tune Factored Binary Controller, but it can be generalized.
Parameters:
max_time time limit (0 for no limit [default])
max_steps steps (0 for no limit [default])
Definition at line 248 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, libpg::RLAlg::learn(), NN_LAYERS, OBS_DIM, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and STEPS_PER_EPOCH.
template<class Controller> void ExploreSoftmaxKnobs (int max_time, int max_steps)
This function tries to find the best combination of step size, Kapa and discount. It is specific to tune a Controller with Softmax policy, but it can be generalized.
Parameters:
max_time time limit (0 for no limit [default])
max_steps steps (0 for no limit [default])
Definition at line 153 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, libpg::RLAlg::learn(), NN_LAYERS, OBS_DIM, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, STEPS_PER_EPOCH, and TD_DISCOUNT.
OLPomdp* Factored_Binary_NeuralNet ()
Factored Binary controller with neural net function approximator.
Returns:
OLPomdp agent
Definition at line 582 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), and mergeProcessorOptimisatorOutput::step_size.
Referenced by main().
OLPomdp* LSPI_NeuralNet_Softmax_Decaying ()
SARSA controller with linear function approximator and Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 331 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, commonInit, OBS_DIM, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* LSPI_NeuralNet_Uniform_Random ()
Definition at line 358 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 603 of file ThreeStateTest.cc.
References Basic_NeuralNet(), Factored_Binary_NeuralNet(), libpg::RLAlg::learn(), LSPI_NeuralNet_Softmax_Decaying(), LSPI_NeuralNet_Uniform_Random(), MAX_STEPS, MAX_TIME, NACTransform_Binary_NeuralNet(), OLBFGS_NeuralNet(), QLearning_NeuralNet_eGreedy_Constant(), QLearning_NeuralNet_eGreedy_Decaying(), QLearning_NeuralNet_Softmax_Decaying(), SARSA_NeuralNet_eGreedy_Constant(), SARSA_NeuralNet_eGreedy_Decaying(), SARSA_NeuralNet_Softmax_Decaying(), and STEPS_PER_EPOCH.
OLPomdp* NACTransform_Binary_NeuralNet ()
NAC Transform with Binary controller with neural net function approximator.
Returns:
OLPomdp agent
Definition at line 537 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* OLBFGS_NeuralNet ()
NAC Transform with Binary controller with neural net function approximator.
Returns:
OLPomdp agent
Definition at line 559 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), and mergeProcessorOptimisatorOutput::step_size.
Referenced by main().
OLPomdp* QLearning_NeuralNet_eGreedy_Constant ()
QLearning controller with linear function approximator and e-Greedy policy (constant epsilon).
Returns:
OLPomdp agent
Definition at line 464 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* QLearning_NeuralNet_eGreedy_Decaying ()
QLearning controller with linear function approximator and e-Greedy policy (decaying epsilon).
Returns:
OLPomdp agent
Definition at line 490 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* QLearning_NeuralNet_Softmax_Decaying ()
QLearning controller with linear function approximator and Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 438 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* SARSA_NeuralNet_eGreedy_Constant ()
SARSA controller with linear function approximator and e-Greedy policy (constant epsilon).
Returns:
OLPomdp agent
Definition at line 386 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* SARSA_NeuralNet_eGreedy_Decaying ()
SARSA controller with linear function approximator and e-Greedy policy (decaying epsilon).
Returns:
OLPomdp agent
Definition at line 412 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
OLPomdp* SARSA_NeuralNet_Softmax_Decaying ()
SARSA controller with linear function approximator and Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 301 of file ThreeStateTest.cc.
References commonInit, libpg::RLAlg::setUseAutoBaseline(), mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().