The PG Library: libpg::HMMTransform Class Reference
libpg::HMMTransform
libpg::HMMTransform Class Reference
#include <HMMTransform.hh>
Public Member Functions
HMMTransform (Controller *controller, size_t maxHistory, size_t window, size_t numStates, size_t numObs, size_t numActions)
~HMMTransform ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
Detailed Description
Definition at line 16 of file HMMTransform.hh.
Constructor & Destructor Documentation
libpg::HMMTransform::HMMTransform (Controller * controller, size_t maxHistory, size_t window, size_t numStates, size_t numObs, size_t numActions)
Definition at line 20 of file HMMTransform.cc.
References sumAndPlot::a, libpg::Observation::getFeatures(), libpg::Controller::getInputDim(), sumAndPlot::i, libpg::Observation::init(), and RAND_PROB.
libpg::HMMTransform::~HMMTransform ()
Definition at line 97 of file HMMTransform.cc.
Member Function Documentation
void libpg::HMMTransform::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Just pass to underlying controller
Reimplemented from libpg::TransformController.
Definition at line 103 of file HMMTransform.cc.
References libpg::TransformController::controller, libpg::Controller::getAction(), libpg::Observation::getAgent(), libpg::Observation::getFeatures(), libpg::Observation::getSteps(), libpg::Observation::setAgent(), and libpg::Observation::setSteps().