The PG Library: ServerSocket Class Reference
ServerSocket Class Reference
#include <ServerSocket.hh>
Public Member Functions
ServerSocket (int port)
ServerSocket ()
virtual ~ServerSocket ()
const ServerSocket & operator<< (const std::string &) const
const ServerSocket & operator>> (std::string &) const
void accept (ServerSocket &)
Detailed Description
Definition at line 9 of file ServerSocket.hh.
Constructor & Destructor Documentation
ServerSocket::ServerSocket (int port)
Definition at line 12 of file ServerSocket.cc.
References Socket::bind(), Socket::create(), and Socket::listen().
ServerSocket::ServerSocket ()
Definition at line 14 of file ServerSocket.hh.
ServerSocket::~ServerSocket () [virtual]
Definition at line 31 of file ServerSocket.cc.
Member Function Documentation
const ServerSocket & ServerSocket::operator<< (const std::string & s) const
Definition at line 36 of file ServerSocket.cc.
References Socket::send().
const ServerSocket & ServerSocket::operator>> (std::string & s) const
Definition at line 49 of file ServerSocket.cc.
References Socket::recv().
void ServerSocket::accept (ServerSocket & sock)
Definition at line 59 of file ServerSocket.cc.
References Socket::accept().