The PG Library: SP38::Link Class Reference
SP38::Link
SP38::Link Class Reference
#include <Link.hh>
Public Member Functions
Link (string id, Intersection *from, Intersection *to, int numLanes)
string getId ()
Intersection * getFrom ()
Intersection * getTo ()
int getNumLanes ()
void addDetector (Detector *)
Detector * getDetector (int scatsId)
void addSignalGroup (SignalGroup *)
SignalGroup * getSignalGroup (int scatsId)
Public Attributes
DetectorSet detectors
SignalGroupSet signal_groups
Detailed Description
A connection between two intersections.
Definition at line 18 of file Link.hh.
Constructor & Destructor Documentation
SP38::Link::Link (string id_p, Intersection * from_p, Intersection * to_p, int numLanes_p)
Constructor of a Link between two intersections
Parameters:
Link ID
One Intersection end-point
Other Intersection end-point
Number of lanes in the link
Definition at line 15 of file Link.cc.
Member Function Documentation
string SP38::Link::getId ()
Definition at line 22 of file Link.cc.
Intersection * SP38::Link::getFrom ()
Definition at line 29 of file Link.cc.
Referenced by SP38::Scenario::addLink().
Intersection * SP38::Link::getTo ()
Definition at line 36 of file Link.cc.
Referenced by SP38::Scenario::addLink().
int SP38::Link::getNumLanes ()
Definition at line 43 of file Link.cc.
void SP38::Link::addDetector (Detector * dt)
Adds a detector to the Link. The link's detectors are the same as the destination intersection.
Definition at line 51 of file Link.cc.
References SP38::Intersection::addDetector(), and detectors.
Detector * SP38::Link::getDetector (int scatsId)
Gets a detector from the Intersection.
Parameters:
Detector's scats ID
Definition at line 60 of file Link.cc.
References SP38::Intersection::getDetector().
void SP38::Link::addSignalGroup (SignalGroup * sg)
Adds a Signal Group to the Link.
Definition at line 68 of file Link.cc.
References signal_groups.
SignalGroup * SP38::Link::getSignalGroup (int scatsId)
Gets a SignalGroup from the Link.
Parameters:
Signal Group's scats ID
Definition at line 76 of file Link.cc.
References signal_groups.
Member Data Documentation
DetectorSet SP38::Link::detectors
Definition at line 31 of file Link.hh.
Referenced by addDetector().
SignalGroupSet SP38::Link::signal_groups
Definition at line 32 of file Link.hh.
Referenced by addSignalGroup(), and getSignalGroup().