The PG Library: libpg::NACTransform Class Reference
libpg::NACTransform
libpg::NACTransform Class Reference
#include <NACTransform.hh>
Public Member Functions
NACTransform (Controller *controller, double tdDiscount)
virtual void discountTrace ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual void resetTrace ()
virtual void resetGrad ()
virtual void accumulateGrad (double reward, Observation &newObs)
virtual void instantStep (Vector &reward)
virtual void delayedInstantStep (double reward, Observation &newObs)
virtual void computeDirection (int steps)
virtual void batchStep ()
virtual void updateStatistics (double reward, Observation &newObs)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
virtual void reduce (Vector &v, Approximator::StatsEnum s)
virtual void setDiscount (double discount)
Protected Attributes
int nacDimension
Observation lastObs
double lastReward
bool instantStepRequired
double discount
Matrix AInverse
Vector nacTrace
Vector nacGrad
Vector nacDirection
Vector nacTD
Vector nacParamUpdate
Matrix I
double tdDiscount
Detailed Description
Definition at line 8 of file NACTransform.hh.
Constructor & Destructor Documentation
libpg::NACTransform::NACTransform (Controller * controller, double tdDiscount)
Constructor. Set up additional vectors and matrices needed to implement natural actor critic.
Definition at line 17 of file NACTransform.cc.
References AInverse, libpg::Controller::getInputDim(), libpg::Controller::getNumParams(), I, instantStepRequired, nacDimension, nacDirection, nacGrad, nacParamUpdate, nacTD, and nacTrace.
Member Function Documentation
void libpg::NACTransform::discountTrace () [virtual]
NAC delays it's discounting till the end of a updateStatistics()
Reimplemented from libpg::TransformController.
Definition at line 53 of file NACTransform.cc.
void libpg::NACTransform::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Just a wrapper that intercepts the new observation and completes the instant step from the last round if necessary.
Reimplemented from libpg::TransformController.
Definition at line 62 of file NACTransform.cc.
References libpg::TransformController::controller, delayedInstantStep(), libpg::Controller::getAction(), libpg::Observation::getAgent(), libpg::Observation::getFeatures(), libpg::TransformController::getInputDim(), libpg::Controller::getNumParams(), instantStepRequired, lastObs, lastReward, nacDimension, nacTrace, libpg::Controller::reduce(), libpg::Controller::resetTrace(), and libpg::Approximator::TRACES.
virtual void libpg::NACTransform::getMostProbAction (Observation & obs, Vector & action) [virtual]
Just pass to underlying controller
Parameters:
Observation vector
empty vector to load with the most probably action
Reimplemented from libpg::TransformController.
Definition at line 39 of file NACTransform.hh.
References NYI.
void libpg::NACTransform::resetTrace () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 87 of file NACTransform.cc.
References AInverse, I, and nacTrace.
void libpg::NACTransform::resetGrad () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 93 of file NACTransform.cc.
References AInverse, I, nacGrad, and nacTrace.
void libpg::NACTransform::accumulateGrad (double reward, Observation & newObs) [virtual]
Definition at line 137 of file NACTransform.cc.
References updateStatistics().
void libpg::NACTransform::instantStep (Vector & reward) [virtual]
In the case of NAC this is a bit of a hack. The update requires the next observation to work, so we'll store the fact that an update is required and do it in the next feedback() phase. This effectively means you end up with steps-1 updates, but oh well...
Reimplemented from libpg::TransformController.
Definition at line 108 of file NACTransform.cc.
References instantStepRequired, and lastReward.
void libpg::NACTransform::delayedInstantStep (double reward, Observation & newObs) [virtual]
Definition at line 116 of file NACTransform.cc.
References AInverse, batchStep(), libpg::Observation::getFeatures(), libpg::TransformController::getInputDim(), instantStepRequired, nacDirection, nacGrad, and updateStatistics().
Referenced by getAction().
void libpg::NACTransform::computeDirection (int steps) [virtual]
Normalise the gradient and multiply by the inverse of the A matrix, doing the magic step of natural actor-critic in one go. Could use Sherman-Morrison: (A + u^T v)^-1 = A^-1 - (A^-1 u)^T (v A^-1) / (1 + v A^-1 u)
Parameters:
how many steps did we run to compute grad
Reimplemented from libpg::TransformController.
Definition at line 202 of file NACTransform.cc.
References AInverse, nacDirection, and nacGrad.
void libpg::NACTransform::batchStep () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 212 of file NACTransform.cc.
References libpg::Controller::batchStep(), libpg::TransformController::controller, libpg::Controller::getNumParams(), libpg::Approximator::GRADS, nacDirection, nacParamUpdate, and libpg::Controller::scatter().
Referenced by delayedInstantStep().
void libpg::NACTransform::updateStatistics (double reward, Observation & newObs) [virtual]
Definition at line 143 of file NACTransform.cc.
References AInverse, libpg::TransformController::controller, discount, libpg::Observation::getAgent(), libpg::Observation::getFeatures(), libpg::TransformController::getInputDim(), libpg::Controller::getNumParams(), libpg::Observation::getSteps(), lastObs, nacDimension, nacGrad, nacTD, nacTrace, libpg::Controller::reduce(), tdDiscount, libpg::Approximator::TRACES, and libpg::UBlasExtras::updateInverseMatrix().
Referenced by accumulateGrad(), and delayedInstantStep().
void libpg::NACTransform::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::TransformController.
Definition at line 239 of file NACTransform.cc.
References libpg::TransformController::controller, libpg::TransformController::getNumParams(), libpg::Approximator::GRADS, nacDirection, libpg::Approximator::PARAMS, libpg::Controller::scatter(), and libpg::Approximator::TRACES.
void libpg::NACTransform::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::TransformController.
Definition at line 223 of file NACTransform.cc.
References libpg::TransformController::controller, libpg::TransformController::getNumParams(), libpg::Approximator::GRADS, nacDirection, NYI, libpg::Approximator::PARAMS, libpg::Controller::reduce(), and libpg::Approximator::TRACES.
void libpg::NACTransform::setDiscount (double discount) [virtual]
Takes a local copy of discount and passes it back down to next controller
Reimplemented from libpg::TransformController.
Definition at line 259 of file NACTransform.cc.
References libpg::TransformController::controller, and libpg::Controller::setDiscount().
Member Data Documentation
int libpg::NACTransform::nacDimension [protected]
Definition at line 13 of file NACTransform.hh.
Referenced by getAction(), NACTransform(), and updateStatistics().
Observation libpg::NACTransform::lastObs [protected]
Definition at line 15 of file NACTransform.hh.
Referenced by getAction(), and updateStatistics().
double libpg::NACTransform::lastReward [protected]
Definition at line 16 of file NACTransform.hh.
Referenced by getAction(), and instantStep().
bool libpg::NACTransform::instantStepRequired [protected]
Definition at line 17 of file NACTransform.hh.
Referenced by delayedInstantStep(), getAction(), instantStep(), and NACTransform().
double libpg::NACTransform::discount [protected]
Definition at line 19 of file NACTransform.hh.
Referenced by updateStatistics().
Matrix libpg::NACTransform::AInverse [protected]
Definition at line 21 of file NACTransform.hh.
Referenced by computeDirection(), delayedInstantStep(), NACTransform(), resetGrad(), resetTrace(), and updateStatistics().
Vector libpg::NACTransform::nacTrace [protected]
Definition at line 22 of file NACTransform.hh.
Referenced by getAction(), NACTransform(), resetGrad(), resetTrace(), and updateStatistics().
Vector libpg::NACTransform::nacGrad [protected]
Definition at line 23 of file NACTransform.hh.
Referenced by computeDirection(), delayedInstantStep(), NACTransform(), resetGrad(), and updateStatistics().
Vector libpg::NACTransform::nacDirection [protected]
Definition at line 24 of file NACTransform.hh.
Referenced by batchStep(), computeDirection(), delayedInstantStep(), NACTransform(), reduce(), and scatter().
Vector libpg::NACTransform::nacTD [protected]
Definition at line 25 of file NACTransform.hh.
Referenced by NACTransform(), and updateStatistics().
Vector libpg::NACTransform::nacParamUpdate [protected]
Definition at line 26 of file NACTransform.hh.
Referenced by batchStep(), and NACTransform().
Matrix libpg::NACTransform::I [protected]
Definition at line 27 of file NACTransform.hh.
Referenced by NACTransform(), resetGrad(), and resetTrace().
double libpg::NACTransform::tdDiscount [protected]
Definition at line 29 of file NACTransform.hh.
Referenced by updateStatistics().