The PG Library: libpg::LineSearchAlg Class Reference
libpg::LineSearchAlg
libpg::LineSearchAlg Class Reference
#include <LineSearchAlg.hh>
Public Member Functions
LineSearchAlg ()
LineSearchAlg (Controller *controller, Simulator *simulator, double discount, double stepsize, int lineSearchSteps, double tolerance, double backOff, double exponentBase, double downhilllThresh, int maxTries)
virtual void lineSearchInit (int lineSearchSteps, double tolerance, double backOff, double exponentBase, double downhilllThresh, int maxTries)
virtual double learnCore (int stepsPerEpoch, int &totalSteps)
virtual double lineSearch (int &totalSteps, double lastEpochVal, Vector &totalRewards)
virtual double incrementLineSearch (double currentStep, Vector &totalRewards, int &totalSteps, double &currentReward)
Public Attributes
int lineSearchSteps
int maxTries
double tolerance
double exponentBase
double backOff
double stepSizeBackup
double downhilllThresh
Vector origParams
Vector params
Vector grads
Vector testGrads
int seed
Detailed Description
Perform a line search given a batch estimate coputed by GPomdp. Line search is controlled from the learnCore level, so the dosteps and learn functions are carried over nicely from GPomdp.
Definition at line 12 of file LineSearchAlg.hh.
Constructor & Destructor Documentation
libpg::LineSearchAlg::LineSearchAlg ()
Don't call this one directly. Tears will result.
Definition at line 35 of file LineSearchAlg.hh.
libpg::LineSearchAlg::LineSearchAlg (Controller * controller, Simulator * simulator, double discount, double stepsize, int lineSearchSteps, double tolerance, double backOff, double exponentBase, double downhilllThresh, int maxTries)
Definition at line 14 of file LineSearchAlg.cc.
References lineSearchInit().
Member Function Documentation
void libpg::LineSearchAlg::lineSearchInit (int lineSearchSteps, double tolerance, double backOff, double exponentBase, double downhilllThresh, int maxTries) [virtual]
Definition at line 30 of file LineSearchAlg.cc.
References libpg::RLAlg::controller, libpg::Controller::getNumParams(), grads, origParams, params, seed, libpg::RLAlg::stepSize, stepSizeBackup, and testGrads.
Referenced by LineSearchAlg().
double libpg::LineSearchAlg::learnCore (int stepsPerEpoch, int & totalSteps) [virtual]
Use the GPOMDP estimate to step parameters in the correct direction.
Parameters:
steps to estimate gradient for
ref to variable counting total learning steps. include any steps used for a line search
Reimplemented from libpg::GPomdp.
Definition at line 179 of file LineSearchAlg.cc.
References libpg::RLAlg::baseline, libpg::Controller::computeDirection(), libpg::RLAlg::controller, libpg::GPomdp::doSteps(), libpg::Controller::getMaxParam(), libpg::Simulator::getRewardDim(), lineSearch(), libpg::RLAlg::printPerformanceInfo(), seed, libpg::RLAlg::simulator, and libpg::RLAlg::useAutoBaseline.
double libpg::LineSearchAlg::lineSearch (int & totalSteps, double lastEpochVal, Vector & totalRewards) [virtual]
Returns:
totalSteps counts the number of steps we performed evaluating different step sizes.
Definition at line 60 of file LineSearchAlg.cc.
References backOff, libpg::RLAlg::controller, downhilllThresh, exponentBase, libpg::Approximator::GRADS, grads, incrementLineSearch(), libpg::RLAlg::maxSteps, maxTries, origParams, params, libpg::Approximator::PARAMS, libpg::Controller::reduce(), libpg::Controller::scatter(), libpg::RLAlg::stepSize, stepSizeBackup, and tolerance.
Referenced by learnCore().
double libpg::LineSearchAlg::incrementLineSearch (double currentStep, Vector & totalRewards, int & totalSteps, double & currentReward) [virtual]
Definition at line 160 of file LineSearchAlg.cc.
References libpg::Controller::computeDirection(), libpg::RLAlg::controller, libpg::GPomdp::doSteps(), libpg::Approximator::GRADS, grads, lineSearchSteps, origParams, libpg::Approximator::PARAMS, params, libpg::Controller::reduce(), libpg::Controller::resetTrace(), libpg::Controller::scatter(), seed, and testGrads.
Referenced by lineSearch().
Member Data Documentation
int libpg::LineSearchAlg::lineSearchSteps
Definition at line 16 of file LineSearchAlg.hh.
Referenced by incrementLineSearch().
int libpg::LineSearchAlg::maxTries
Definition at line 17 of file LineSearchAlg.hh.
Referenced by lineSearch().
double libpg::LineSearchAlg::tolerance
Definition at line 18 of file LineSearchAlg.hh.
Referenced by lineSearch().
double libpg::LineSearchAlg::exponentBase
Definition at line 19 of file LineSearchAlg.hh.
Referenced by lineSearch().
double libpg::LineSearchAlg::backOff
Definition at line 20 of file LineSearchAlg.hh.
Referenced by lineSearch().
double libpg::LineSearchAlg::stepSizeBackup
Definition at line 21 of file LineSearchAlg.hh.
Referenced by lineSearch(), and lineSearchInit().
double libpg::LineSearchAlg::downhilllThresh
Definition at line 22 of file LineSearchAlg.hh.
Referenced by lineSearch().
Vector libpg::LineSearchAlg::origParams
Definition at line 24 of file LineSearchAlg.hh.
Referenced by incrementLineSearch(), lineSearch(), and lineSearchInit().
Vector libpg::LineSearchAlg::params
Definition at line 25 of file LineSearchAlg.hh.
Referenced by incrementLineSearch(), lineSearch(), and lineSearchInit().
Vector libpg::LineSearchAlg::grads
Definition at line 27 of file LineSearchAlg.hh.
Referenced by incrementLineSearch(), lineSearch(), and lineSearchInit().
Vector libpg::LineSearchAlg::testGrads
Definition at line 28 of file LineSearchAlg.hh.
Referenced by incrementLineSearch(), and lineSearchInit().
int libpg::LineSearchAlg::seed
Definition at line 30 of file LineSearchAlg.hh.
Referenced by incrementLineSearch(), learnCore(), and lineSearchInit().