The PG Library: libpg::CatObsActionTransform Class Reference
libpg::CatObsActionTransform
libpg::CatObsActionTransform Class Reference
#include <CatObsActionTransform.hh>
Public Member Functions
CatObsActionTransform (Controller *controller, size_t numRows, size_t numCols, size_t agents, size_t actionDim, size_t actions)
~CatObsActionTransform ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
Detailed Description
Concatenate current observation and previous action to produce a new observation. Allows actions to be conditioned on previous action as well as the observation.
Definition at line 13 of file CatObsActionTransform.hh.
Constructor & Destructor Documentation
libpg::CatObsActionTransform::CatObsActionTransform (Controller * controller, size_t numRows, size_t numCols, size_t agents, size_t actionDim, size_t actions)
All of the parameter information here is availalble from the simulator class.
Definition at line 11 of file CatObsActionTransform.cc.
References libpg::Observation::init().
libpg::CatObsActionTransform::~CatObsActionTransform ()
Definition at line 44 of file CatObsActionTransform.hh.
Member Function Documentation
void libpg::CatObsActionTransform::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Just pass to underlying controller
Reimplemented from libpg::TransformController.
Definition at line 39 of file CatObsActionTransform.cc.
References libpg::TransformController::controller, libpg::Controller::getAction(), libpg::Observation::getAgent(), libpg::Observation::getFeatures(), and sumAndPlot::i.