The PG Library: SP38::SP38Simulation Class Reference
SP38::SP38Simulation
SP38::SP38Simulation Class Reference
#include <SP38Simulation.hh>
Public Member Functions
SP38Simulation (uint, ScenarioReader *, string, bool, bool, bool, bool, int, bool)
void startSimulation ()
void doStep ()
void endSimulation ()
bool simulating ()
void setNewPhase (Intersection *, Phase *)
void setNewPhase (int, Intersection *, Phase *)
void setNoChangesBetween (Intersection *i, int start_time, int end_time)
bool isAnythingScheduled (Intersection *, int)
Phase * getCurrentPhase (Intersection *)
int getCurrentPhaseDuration (Intersection *)
int getPhaseDurationInCurrentCycle (Intersection *, Phase *)
int getPhaseDurationBetween (Intersection *, Phase *, int, int)
bool isDetectorActive (Intersection *, Detector *)
int getDetectorCountInCurrentCycle (Intersection *, Detector *)
int getDetectorCountBetween (Intersection *, Detector *, double, double)
int getDetectorMaxThroughput (Intersection *, Detector *)
double getPhaseMaxDetectorThroughputBetween (Intersection *, Phase *, int, int)
double getPhaseThroughputInCurrentCyle (Intersection *, Phase *)
double getPhaseThroughputInLastCompletedCyle (Intersection *, Phase *)
double getPhaseThroughputBetween (Intersection *, Phase *, int, int)
double getIntersectionMaxThroughput (Intersection *)
Scenario * getScenario ()
ScenarioHistory * getCurrentScenarioHistory ()
int getCurrentTime ()
int getLastRestartTime ()
int getNextActionTime (int)
int getCurrentCycleStartingTime ()
int getCurrentCycleDuration ()
int getTimeStepSize ()
int getDayHour ()
int getDayHourMinute ()
int getMinimalActivationTime (Intersection *)
void setDebug (bool)
void setNoisy (bool)
Detailed Description
Manages the SP38Interface to make a simulation and extracts information about that. Any information about the simulation are exposed trough its methods. Enforces some constraints about schedule like minimum green time, maximum red time and inter green time.
Definition at line 21 of file SP38Simulation.hh.
Constructor & Destructor Documentation
SP38::SP38Simulation::SP38Simulation (uint s, ScenarioReader * sr, string host, bool fapc, bool f, bool d, bool n, int maxt, bool id)
SP38Simulation Constructor.
Parameters:
The time step size in seconds.
The scenario reader can be Artemis, Paramics or any other.
The IP of the simulator server that implements sp38 protocol (The port is always 2100).
Will the all phases in cycle constraint be forced to satisfaction?
Will the optimisation run forever (or until you ctrl+c it) ?
sets debug messages
sets noisy messages
sets maximum connect tries (will be used every simulation starting)
sets debug messages from SP38 protocol
Definition at line 17 of file SP38Simulation.cc.
References SP38::ScenarioReader::readScenario(), SP38::SP38Interface::set_debug(), and SP38::SP38Interface::set_noisy().
Member Function Documentation
void SP38::SP38Simulation::startSimulation ()
Connects to the server and clear things for a new simulation.
Definition at line 33 of file SP38Simulation.cc.
References doStep(), SP38::SP38Interface::getStartDate(), SP38::SP38Interface::getStartTime(), sumAndPlot::i, SP38::Scenario::intersections, setNewPhase(), Sleep, and SP38::SP38Interface::tryConnect().
Referenced by doStep(), endSimulation(), and SP38::SP38PGSimulator::SP38PGSimulator().
void SP38::SP38Simulation::doStep ()
Do one step of simulation, sending the schedule and refreshing the history.
Definition at line 79 of file SP38Simulation.cc.
References SP38::SP38Interface::do_step(), getCurrentCycleDuration(), SP38::Scenario::getCycleDuration(), getTimeStepSize(), SP38::ScenarioHistory::setCurrentTime(), SP38::ScenarioHistory::setInitialState(), simulating(), and startSimulation().
Referenced by SP38::SP38PGSimulator::doAction(), and startSimulation().
void SP38::SP38Simulation::endSimulation ()
Disconnects from the server.
Definition at line 150 of file SP38Simulation.cc.
References SP38::SP38Interface::disconnect(), getDetectorCountBetween(), sumAndPlot::i, SP38::Scenario::intersections, and startSimulation().
bool SP38::SP38Simulation::simulating ()
Tells if it's still simulating.
Definition at line 179 of file SP38Simulation.cc.
References SP38::SP38Interface::is_simulation_running().
Referenced by SP38::SP38PGSimulator::doAction(), and doStep().
void SP38::SP38Simulation::setNewPhase (Intersection * i, Phase * p)
Start changing the phase of an intersection at the current time.
Parameters:
the intersection
the new phase to be turned on
Definition at line 347 of file SP38Simulation.cc.
References getCurrentTime().
Referenced by SP38::SP38PGSimulator::doAction(), and startSimulation().
void SP38::SP38Simulation::setNewPhase (int time, Intersection * i, Phase * p)
Changes the phase of an intersection at a given time.
Parameters:
Time that the phase will be turned on
the intersection
ht new phase to be turned on
Definition at line 357 of file SP38Simulation.cc.
References SP38::PhaseHistory::activate(), SP38::PhaseHistory::deactivate(), SP38::Intersection::getId(), SP38::Phase::getId(), SP38::Intersection::getInterGreenInterval(), SP38::ScenarioHistory::getIntersectionHistory(), SP38::Intersection::getMinimumGreenDuration(), SP38::Intersection::getPhase(), SP38::IntersectionHistory::getPhase(), SP38::IntersectionHistory::getPhaseHistory(), SP38::ScatsObject::getScatsId(), SP38::Phase::getSignalGroup(), SP38::Intersection::getYellowDuration(), GREEN_SIGNAL_SP38, isAnythingScheduled(), SP38::PhaseHistory::lastActivation(), RED_SIGNAL_SP38, setNoChangesBetween(), SP38::Phase::signal_groups, SIGNAL_OFF_SP38, and YELLOW_SIGNAL_SP38.
void SP38::SP38Simulation::setNoChangesBetween (Intersection * i, int start_time, int end_time)
Sets that no actions/signal changes can be made between the time interval passed. This won't affect border of the interval.
Parameters:
The intersection
starting time
end time
Definition at line 467 of file SP38Simulation.cc.
References SP38::Intersection::getId(), and getNextActionTime().
Referenced by setNewPhase().
bool SP38::SP38Simulation::isAnythingScheduled (Intersection * i, int time)
Tells if anything signal changes are schedule for the intersection in a given time.
Parameters:
The intersection
the time instant to check
Definition at line 657 of file SP38Simulation.cc.
Referenced by SP38::SimpleDynamicController::getAction(), SP38::FixedController::getAction(), SP38::SP38PGSimulator::getObservation(), and setNewPhase().
Phase * SP38::SP38Simulation::getCurrentPhase (Intersection * i)
Gets the current phase of an intersection
Parameters:
the intersection to get the phase
Definition at line 216 of file SP38Simulation.cc.
References SP38::IntersectionHistory::getCurrentPhase(), and SP38::ScenarioHistory::getIntersectionHistory().
Referenced by SP38::SimpleDynamicController::getAction(), SP38::FixedController::getAction(), and SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getCurrentPhaseDuration (Intersection * i)
Gets the current phase duration of an intersection
Parameters:
the intersection to get the duration of current's phase
Definition at line 226 of file SP38Simulation.cc.
References SP38::IntersectionHistory::getCurrentPhaseDuration(), and SP38::ScenarioHistory::getIntersectionHistory().
Referenced by SP38::SimpleDynamicController::getAction(), SP38::FixedController::getAction(), and SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getPhaseDurationInCurrentCycle (Intersection * i, Phase * p)
Gets the a phase active time in the current cycle.
Parameters:
the intersection of the phase
The phase
Definition at line 236 of file SP38Simulation.cc.
References getCurrentCycleStartingTime(), and getPhaseDurationBetween().
Referenced by SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getPhaseDurationBetween (Intersection * i, Phase * p, int from, int to)
Gets the phase active time between two instants
Parameters:
the intersection of the phase
The phase
starting time
ending time
Definition at line 248 of file SP38Simulation.cc.
References SP38::ScenarioHistory::getIntersectionHistory(), SP38::IntersectionHistory::getPhaseHistory(), and SP38::PhaseHistory::totalActiveTime().
Referenced by getPhaseDurationInCurrentCycle().
bool SP38::SP38Simulation::isDetectorActive (Intersection * i, Detector * d)
Tells if a detector of an intersections is currently active.
Parameters:
The intersection of the detector
the detector
Definition at line 646 of file SP38Simulation.cc.
References SP38::IntersectionHistory::getDetectorHistory(), SP38::ScenarioHistory::getIntersectionHistory(), and SP38::DetectorHistory::isActive().
Referenced by SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getDetectorCountInCurrentCycle (Intersection * i, Detector * d)
Gets the current's cycle detector count.
Parameters:
the intersection of the detector
the detector
Definition at line 314 of file SP38Simulation.cc.
References getCurrentCycleStartingTime(), and getDetectorCountBetween().
int SP38::SP38Simulation::getDetectorCountBetween (Intersection * i, Detector * d, double from, double to)
Gets the detector count between two instants
Parameters:
the intersection of the detector
the detector
starting time
ending time
Definition at line 325 of file SP38Simulation.cc.
References SP38::IntersectionHistory::getDetectorHistory(), SP38::ScenarioHistory::getIntersectionHistory(), and SP38::DetectorHistory::totalActivations().
Referenced by endSimulation(), and getDetectorCountInCurrentCycle().
int SP38::SP38Simulation::getDetectorMaxThroughput (Intersection * i, Detector * d)
Gets the maximum detector count in one of the previously time steps.
Parameters:
the intersection of the detector
the detector
Definition at line 336 of file SP38Simulation.cc.
References SP38::IntersectionHistory::getDetectorHistory(), SP38::ScenarioHistory::getIntersectionHistory(), and SP38::DetectorHistory::getMaxActivationsInInterval().
double SP38::SP38Simulation::getPhaseMaxDetectorThroughputBetween (Intersection * i, Phase * p, int from, int to)
Gets the maximum rate of cars that passed through the phase in one of its detectors when active in a given interval.
Parameters:
intersection of the phase
the phase
start of the interval
end of the interval
Definition at line 293 of file SP38Simulation.cc.
References SP38::ScenarioHistory::getIntersectionHistory(), and SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween().
Referenced by SP38::SimpleDynamicController::getAction().
double SP38::SP38Simulation::getPhaseThroughputInCurrentCyle (Intersection * i, Phase * p)
Gets the rate of cars that passed through the phase when active in the current cycle.
Parameters:
intersection of the phase
the phase
Definition at line 259 of file SP38Simulation.cc.
References getCurrentCycleStartingTime(), and getPhaseThroughputBetween().
Referenced by SP38::SP38PGSimulator::getObservation().
double SP38::SP38Simulation::getPhaseThroughputInLastCompletedCyle (Intersection * i, Phase * p)
Gets the rate of cars that passed through the phase when active in the last completed cycle.
Parameters:
intersection of the phase
the phase
Definition at line 268 of file SP38Simulation.cc.
References getCurrentCycleStartingTime(), SP38::Scenario::getCycleDuration(), and getPhaseThroughputBetween().
Referenced by SP38::SP38PGSimulator::getObservation().
double SP38::SP38Simulation::getPhaseThroughputBetween (Intersection * i, Phase * p, int from, int to)
Gets the rate of cars that passed through the phase when active in a given interval.
Parameters:
intersection of the phase
the phase
start of the interval
end of the interval
Definition at line 281 of file SP38Simulation.cc.
References SP38::ScenarioHistory::getIntersectionHistory(), and SP38::IntersectionHistory::getPhaseThroughputBetween().
Referenced by getPhaseThroughputInCurrentCyle(), and getPhaseThroughputInLastCompletedCyle().
double SP38::SP38Simulation::getIntersectionMaxThroughput (Intersection * i)
Gets the maximum rate of cars that passed through the intersection when some phase was active.
Parameters:
intersection of the phase
Definition at line 303 of file SP38Simulation.cc.
References SP38::ScenarioHistory::getIntersectionHistory(), and SP38::IntersectionHistory::getMaxThroughput().
Referenced by SP38::SP38PGSimulator::getObservation().
Scenario * SP38::SP38Simulation::getScenario ()
Gets the scenario
Definition at line 628 of file SP38Simulation.cc.
Referenced by SP38::SP38PGSimulator::SP38PGSimulator().
ScenarioHistory * SP38::SP38Simulation::getCurrentScenarioHistory ()
Gets the current scenario history. Note that it changes when the simulation is restarted.
Definition at line 636 of file SP38Simulation.cc.
Referenced by SP38::SP38PGSimulator::getCurrentScenarioHistory().
int SP38::SP38Simulation::getCurrentTime ()
Gets the current time.
Definition at line 550 of file SP38Simulation.cc.
Referenced by SP38::SimpleDynamicController::getAction(), SP38::FixedController::getAction(), SP38::SP38PGSimulator::getObservation(), and setNewPhase().
int SP38::SP38Simulation::getLastRestartTime ()
Gets the last time the simulation restarted.
Definition at line 557 of file SP38Simulation.cc.
Referenced by SP38::FixedController::getAction().
int SP38::SP38Simulation::getNextActionTime (int time)
Get next action time. Will always be greater then the time passed.
Parameters:
base time
Definition at line 604 of file SP38Simulation.cc.
Referenced by setNoChangesBetween().
int SP38::SP38Simulation::getCurrentCycleStartingTime ()
Gets current's cycle starting time
Definition at line 587 of file SP38Simulation.cc.
References getCurrentCycleDuration().
Referenced by getDetectorCountInCurrentCycle(), getPhaseDurationInCurrentCycle(), getPhaseThroughputInCurrentCyle(), and getPhaseThroughputInLastCompletedCyle().
int SP38::SP38Simulation::getCurrentCycleDuration ()
Return how many steps the current cycle has lasted.
Definition at line 594 of file SP38Simulation.cc.
References SP38::ScenarioHistory::getCurrentCycleDuration().
Referenced by doStep(), getCurrentCycleStartingTime(), and SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getTimeStepSize ()
Gets the time step size in seconds.
Definition at line 565 of file SP38Simulation.cc.
Referenced by doStep(), SP38::SP38PGSimulator::getObservation(), and SP38::SP38PGSimulator::getObsRows().
int SP38::SP38Simulation::getDayHour ()
Get the hour of day in the simulation.
Definition at line 124 of file SP38Simulation.cc.
Referenced by SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getDayHourMinute ()
Get the minute of the current hour in the simulation.
Definition at line 131 of file SP38Simulation.cc.
Referenced by SP38::SP38PGSimulator::getObservation().
int SP38::SP38Simulation::getMinimalActivationTime (Intersection * i)
Gets the minimal time needed to have one valid green interval. It assumes you will need some yellow time, inter green interval and minimum green time. It rounds things to fit into a multiple of the time step size.
Parameters:
the intersection
Definition at line 576 of file SP38Simulation.cc.
References SP38::Intersection::getInterGreenInterval(), SP38::Intersection::getMinimumGreenDuration(), and SP38::Intersection::getYellowDuration().
void SP38::SP38Simulation::setDebug (bool d)
Set debug nessages
Parameters:
state of debug messages
Definition at line 612 of file SP38Simulation.cc.
void SP38::SP38Simulation::setNoisy (bool n)
Set general messages
Parameters:
state of general messages
Definition at line 620 of file SP38Simulation.cc.