The PG Library: libpg::ObsWindowTransform Class Reference
libpg::ObsWindowTransform
libpg::ObsWindowTransform Class Reference
#include <ObsWindowTransform.hh>
Public Member Functions
ObsWindowTransform (Controller *controller, size_t maxHistory, size_t numRows, size_t numCols, size_t agents)
~ObsWindowTransform ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
Detailed Description
Take observations and stack them in an history vector of fixed length. History vector then becomes the observation vector.
Definition at line 15 of file ObsWindowTransform.hh.
Constructor & Destructor Documentation
libpg::ObsWindowTransform::ObsWindowTransform (Controller * controller, size_t maxHistory, size_t numRows, size_t numCols, size_t agents)
Definition at line 10 of file ObsWindowTransform.cc.
References libpg::Observation::getFeatures(), and libpg::Observation::init().
libpg::ObsWindowTransform::~ObsWindowTransform ()
Definition at line 43 of file ObsWindowTransform.hh.
Member Function Documentation
void libpg::ObsWindowTransform::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Just pass to underlying controller
Reimplemented from libpg::TransformController.
Definition at line 33 of file ObsWindowTransform.cc.
References libpg::TransformController::controller, libpg::Controller::getAction(), libpg::Observation::getAgent(), libpg::Observation::getEligible(), libpg::Observation::getFeatures(), and libpg::Observation::setAgent().