The PG Library: libpg::RegularizeTransform Class Reference
libpg::RegularizeTransform
libpg::RegularizeTransform Class Reference
#include <RegularizeTransform.hh>
Public Member Functions
RegularizeTransform (Controller *c, double penalty)
~RegularizeTransform ()
virtual void setPenalty (double penalty)
virtual void setStepSize (double stepSize)
virtual void instantStep (Vector &rewards)
virtual void batchStep ()
Protected Member Functions
void penalise ()
Protected Attributes
double stepSize
double penalty
Vector params
Vector penaltyVector
Detailed Description
Definition at line 6 of file RegularizeTransform.hh.
Constructor & Destructor Documentation
libpg::RegularizeTransform::RegularizeTransform (Controller * c, double penalty)
Implements Tikhonov style regularisation, either in an online step, or batch step. Regularizer gradient for is -q Should be able to sit anywhere in the controller stack since it uses the reduce and scatter commands for the params only.
Definition at line 17 of file RegularizeTransform.cc.
References libpg::TransformController::controller, libpg::Controller::getNumParams(), params, and penaltyVector.
libpg::RegularizeTransform::~RegularizeTransform ()
Definition at line 21 of file RegularizeTransform.hh.
Member Function Documentation
void libpg::RegularizeTransform::penalise () [protected]
Definition at line 70 of file RegularizeTransform.cc.
References libpg::TransformController::controller, libpg::Approximator::PARAMS, params, penalty, penaltyVector, libpg::Controller::reduce(), libpg::Controller::scatter(), and stepSize.
Referenced by batchStep(), and instantStep().
void libpg::RegularizeTransform::setPenalty (double penalty) [virtual]
Definition at line 32 of file RegularizeTransform.cc.
void libpg::RegularizeTransform::setStepSize (double stepSize) [virtual]
Reimplemented from libpg::TransformController.
Definition at line 25 of file RegularizeTransform.cc.
References libpg::TransformController::controller, and libpg::Controller::setStepSize().
void libpg::RegularizeTransform::instantStep (Vector & rewards) [virtual]
Reimplemented from libpg::TransformController.
Definition at line 54 of file RegularizeTransform.cc.
References libpg::TransformController::controller, libpg::Controller::instantStep(), libpg::Approximator::PARAMS, penalise(), penalty, penaltyVector, and libpg::Controller::reduce().
void libpg::RegularizeTransform::batchStep () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 38 of file RegularizeTransform.cc.
References libpg::Controller::batchStep(), libpg::TransformController::controller, libpg::Approximator::PARAMS, penalise(), penalty, penaltyVector, and libpg::Controller::reduce().
Member Data Documentation
double libpg::RegularizeTransform::stepSize [protected]
Definition at line 11 of file RegularizeTransform.hh.
Referenced by penalise().
double libpg::RegularizeTransform::penalty [protected]
Definition at line 12 of file RegularizeTransform.hh.
Referenced by batchStep(), instantStep(), and penalise().
Vector libpg::RegularizeTransform::params [protected]
Definition at line 13 of file RegularizeTransform.hh.
Referenced by penalise(), and RegularizeTransform().
Vector libpg::RegularizeTransform::penaltyVector [protected]
Definition at line 14 of file RegularizeTransform.hh.
Referenced by batchStep(), instantStep(), penalise(), and RegularizeTransform().