The PG Library: ClientSocket Class Reference
ClientSocket Class Reference
#include <ClientSocket.hh>
Public Member Functions
ClientSocket (std::string host, int port)
virtual ~ClientSocket ()
const ClientSocket & operator<< (const std::string &) const
const ClientSocket & operator>> (std::string &) const
Detailed Description
Definition at line 9 of file ClientSocket.hh.
Constructor & Destructor Documentation
ClientSocket::ClientSocket (std::string host, int port)
Definition at line 8 of file ClientSocket.cc.
References Socket::connect(), and Socket::create().
virtual ClientSocket::~ClientSocket () [virtual]
Definition at line 14 of file ClientSocket.hh.
Member Function Documentation
const ClientSocket & ClientSocket::operator<< (const std::string & s) const
Definition at line 23 of file ClientSocket.cc.
References Socket::send().
const ClientSocket & ClientSocket::operator>> (std::string & s) const
Definition at line 35 of file ClientSocket.cc.
References Socket::recv().