The PG Library: GridSim Class Reference
GridSim Class Reference
#include <GridSim.hh>
Public Member Functions
GridSim (int gridSize, double packetGenProb, int bufferSize)
virtual ~GridSim ()
virtual int getObsRows ()
virtual int getObsCols ()
virtual int getAgents ()
virtual int getActionDim ()
virtual int getRewardDim ()
virtual void getReward (Vector &rewards)
virtual void getObservation (Observation &obs)
virtual int doAction (Vector &action)
Detailed Description
Container for any RL problem we care to define. We simply have to define the dimensionality of actions, a reward function, a way to get observationsk, and a way to do actions.
Definition at line 13 of file GridSim.hh.
Constructor & Destructor Documentation
GridSim::GridSim (int gridSize, double packetGenProb, int bufferSize)
Parameters:
gridSize how many paths in for each direction, e.g., square root of number of agents.
frequency with which packets arrive.
bufferSize new packets will be dropped if more than this packets waiting in any queue
Definition at line 21 of file GridSim.cc.
References sumAndPlot::i.
virtual GridSim::~GridSim () [virtual]
Definition at line 37 of file GridSim.hh.
Member Function Documentation
int GridSim::getObsRows () [virtual]
Get the number of rows in observation matrix. Generally the length of the observation vector.
Implements libpg::Simulator.
Definition at line 39 of file GridSim.cc.
References OBS_DIM.
Referenced by main_crf().
int GridSim::getObsCols () [virtual]
Get the number of columns in the observation matrix Typically use multiple columns to provide a different observation to each agent, so the number of columns is the same as getAgents()
Implements libpg::Simulator.
Definition at line 41 of file GridSim.cc.
int GridSim::getAgents () [virtual]
Get the total number of agents. Usually 1.
Implements libpg::Simulator.
Definition at line 43 of file GridSim.cc.
Referenced by main_crf().
int GridSim::getActionDim () [virtual]
Get the total action dimensionality. Often, but not necessarily, the same as the number of agents.
Implements libpg::Simulator.
Definition at line 45 of file GridSim.cc.
int GridSim::getRewardDim () [virtual]
Get the dimensionality of the reward vector. Often, but not necessarily, the same as the number of agents.
Global rewards
Implements libpg::Simulator.
Definition at line 50 of file GridSim.cc.
void GridSim::getReward (Vector & rewards) [virtual]
Just return the reward associated with the most recent state achieved.
Parameters:
rewards vector of rewards. The vector has getAgents() dimensionality In non-local reward mode this vector will just be averaged.
Just return the next reward set in doAction
Implements libpg::Simulator.
Definition at line 55 of file GridSim.cc.
void GridSim::getObservation (Observation & obs) [virtual]
Two observations per node giving normalised number of waiting packets.
Parameters:
obs observation structure that should be correct size already
Implements libpg::Simulator.
Definition at line 67 of file GridSim.cc.
References libpg::Observation::getFeatures(), and OBS_DIM.
int GridSim::doAction (Vector & action) [virtual]
Do action issued by a controller
Returns:
vector of actions, typically just a scalar which is cast to an int, but it there are multiple agents it will be a vector of actions for each agent.
Parameters:
action vector that describes the action to perform.
Do the suggested action, passing through any packets if possible, then add in new packets
Implements libpg::Simulator.
Definition at line 86 of file GridSim.cc.
References DBG_POL.