The PG Library: SP38::Intersection Class Reference
SP38::Intersection
SP38::Intersection Class Reference
#include <Intersection.hh>
Public Member Functions
Intersection (string, int, int, int)
string getId ()
int getCycle ()
int getOffset ()
void setYellowDuration (int)
void setInterGreenInterval (int)
void setMinimumGreenDuration (int)
int getYellowDuration ()
int getInterGreenInterval ()
int getMinimumGreenDuration ()
int getTotalDetectors ()
int getTotalPhases ()
void addPhase (Phase *)
void addDetector (Detector *)
void addNeighbour (Intersection *)
Detector * getDetector (int scatsId)
Phase * getPhase (string id)
int getPhaseIndex (Phase *)
Phase * getPhaseByIndex (int)
Phase * getStartPhase ()
Phase * getNextPhase (Phase *current)
void addInLink (Link *)
void addOutLink (Link *)
Link * getInLink (string)
Link * getOutLink (string)
Public Attributes
PhaseSet phases
DetectorSet detectors
IntersectionSet neighbours
vector< Link * > in_links
vector< Link * > out_links
Detailed Description
An intersection between links (streets).
Definition at line 29 of file Intersection.hh.
Constructor & Destructor Documentation
SP38::Intersection::Intersection (string id_p, int scatsId_p, int cycle_p, int offset_p)
Intersection basic constructor
Parameters:
An ID for the intersection
Scats Id
Cycle length
Offset value
Definition at line 14 of file Intersection.cc.
Member Function Documentation
string SP38::Intersection::getId ()
Definition at line 72 of file Intersection.cc.
Referenced by SP38::SimpleDynamicController::getAction(), SP38::SP38Optimisator::getController(), SP38::SP38Optimisator::setIntersectionTimes(), SP38::SP38Simulation::setNewPhase(), and SP38::SP38Simulation::setNoChangesBetween().
int SP38::Intersection::getCycle ()
Gets the Intersection's Cycle.
Definition at line 79 of file Intersection.cc.
int SP38::Intersection::getOffset ()
Gets the Intersection's Offset.
Definition at line 86 of file Intersection.cc.
void SP38::Intersection::setYellowDuration (int time)
Set the yellow time duration for the intersection.
Parameters:
time in seconds
Definition at line 25 of file Intersection.cc.
Referenced by SP38::SP38Optimisator::setIntersectionTimes().
void SP38::Intersection::setInterGreenInterval (int time)
Set the inter green interval for the intersection.
Parameters:
time in seconds
Definition at line 33 of file Intersection.cc.
Referenced by SP38::SP38Optimisator::setIntersectionTimes().
void SP38::Intersection::setMinimumGreenDuration (int time)
Set the inter green interval for the intersection.
Parameters:
time in seconds
Definition at line 41 of file Intersection.cc.
Referenced by SP38::SP38Optimisator::setIntersectionTimes().
int SP38::Intersection::getYellowDuration ()
Set the inter green interval for the intersection.
Parameters:
time in seconds
Definition at line 49 of file Intersection.cc.
Referenced by SP38::SP38Simulation::getMinimalActivationTime(), and SP38::SP38Simulation::setNewPhase().
int SP38::Intersection::getInterGreenInterval ()
Set the inter green interval for the intersection.
Parameters:
time in seconds
Definition at line 57 of file Intersection.cc.
Referenced by SP38::SP38Simulation::getMinimalActivationTime(), and SP38::SP38Simulation::setNewPhase().
int SP38::Intersection::getMinimumGreenDuration ()
Set the inter green interval for the intersection.
Parameters:
time in seconds
Definition at line 65 of file Intersection.cc.
Referenced by SP38::SP38Simulation::getMinimalActivationTime(), and SP38::SP38Simulation::setNewPhase().
int SP38::Intersection::getTotalDetectors ()
Gives the number of detectors in the intersection.
Definition at line 93 of file Intersection.cc.
References detectors.
int SP38::Intersection::getTotalPhases ()
Gives the number of phases in the intersection.
Definition at line 100 of file Intersection.cc.
References phases.
Referenced by SP38::SP38Optimisator::getController().
void SP38::Intersection::addPhase (Phase * p)
Adds a Phase to the Intersection.
Parameters:
the phase
Definition at line 109 of file Intersection.cc.
References phases.
void SP38::Intersection::addDetector (Detector * dt)
Adds a detector to the Intersection.
Parameters:
the detector
Definition at line 117 of file Intersection.cc.
References detectors.
Referenced by SP38::Link::addDetector().
void SP38::Intersection::addNeighbour (Intersection * i)
Adds a neighbour Intersection to this Intersection.
Parameters:
the neighbour intersection
Definition at line 125 of file Intersection.cc.
References neighbours.
Referenced by SP38::Scenario::addLink().
Detector * SP38::Intersection::getDetector (int scatsId)
Gets a detector from the Intersection.
Parameters:
Detector's scats ID
Definition at line 170 of file Intersection.cc.
References detectors.
Referenced by SP38::Link::getDetector().
Phase * SP38::Intersection::getPhase (string id)
Gets a signal group from the Intersection.
Parameters:
Signal Group's scats ID
Definition at line 180 of file Intersection.cc.
References phases.
Referenced by SP38::SP38Simulation::setNewPhase().
int SP38::Intersection::getPhaseIndex (Phase * pe)
Gets the phase index in the phases vector.
Parameters:
Phase
Definition at line 190 of file Intersection.cc.
References phases.
Referenced by SP38::SimpleDynamicController::getAction(), and SP38::FixedController::getAction().
Phase * SP38::Intersection::getPhaseByIndex (int pos)
Gets the Phase in the phases vector by the index.
Parameters:
the phase's index
Definition at line 203 of file Intersection.cc.
References phases.
Phase * SP38::Intersection::getStartPhase ()
Gets the starting phase.
Definition at line 215 of file Intersection.cc.
References phases.
Phase * SP38::Intersection::getNextPhase (Phase * cp)
Gets the next phase.
Definition at line 222 of file Intersection.cc.
References SP38::Phase::getId(), and phases.
void SP38::Intersection::addInLink (Link * l)
Adds a Link to the set of links to this intersection.
Parameters:
the link
Definition at line 133 of file Intersection.cc.
References in_links.
Referenced by SP38::Scenario::addLink().
void SP38::Intersection::addOutLink (Link * l)
Adds a Link to the set of links from this intersection.
Parameters:
the link
Definition at line 141 of file Intersection.cc.
References out_links.
Referenced by SP38::Scenario::addLink().
Link * SP38::Intersection::getInLink (string id)
Gets a Link from the set of links to this intersection.
Parameters:
the link's ID
Definition at line 149 of file Intersection.cc.
References in_links.
Link * SP38::Intersection::getOutLink (string id)
Gets a Link from the set of links from this intersection.
Parameters:
the link's ID
Definition at line 159 of file Intersection.cc.
References out_links.
Member Data Documentation
PhaseSet SP38::Intersection::phases
Definition at line 83 of file Intersection.hh.
Referenced by addPhase(), SP38::SimpleDynamicController::getAction(), SP38::SP38Optimisator::getController(), getNextPhase(), getPhase(), getPhaseByIndex(), getPhaseIndex(), getStartPhase(), getTotalPhases(), SP38::IntersectionHistory::IntersectionHistory(), and SP38::SimpleDynamicController::SimpleDynamicController().
DetectorSet SP38::Intersection::detectors
Definition at line 84 of file Intersection.hh.
Referenced by addDetector(), getDetector(), getTotalDetectors(), and SP38::IntersectionHistory::IntersectionHistory().
IntersectionSet SP38::Intersection::neighbours
Definition at line 85 of file Intersection.hh.
Referenced by addNeighbour().
vector<Link*> SP38::Intersection::in_links
Definition at line 86 of file Intersection.hh.
Referenced by addInLink(), and getInLink().
vector<Link*> SP38::Intersection::out_links
Definition at line 87 of file Intersection.hh.
Referenced by addOutLink(), and getOutLink().