The PG Library: libpg::Observation Class Reference
libpg::Observation
libpg::Observation Class Reference
#include <Observation.hh>
Public Member Functions
Observation (int rows, int cols, int agents, int actions)
Observation (Observation &obs)
Observation ()
void init (int rows, int cols, int agents, int actions)
int getSteps ()
void setSteps (int s)
void setAgent (int a)
int getAgent ()
Matrix & getFeatures ()
bVector & getEligible ()
Observation & operator= (Observation &rhs)
Protected Attributes
Matrix features
bVector eligible
int agent
int steps
Detailed Description
Definition at line 6 of file Observation.hh.
Constructor & Destructor Documentation
libpg::Observation::Observation (int rows, int cols, int agents, int actions)
Definition at line 5 of file Observation.cc.
References init().
libpg::Observation::Observation (Observation & obs)
Copy constructor
Definition at line 15 of file Observation.cc.
libpg::Observation::Observation ()
Definition at line 55 of file Observation.hh.
Member Function Documentation
void libpg::Observation::init (int rows, int cols, int agents, int actions)
Resize the observation matricies and vectors. Normally done by the constructor with the same arguments. Elgible vector size inited to agents if agents>1, actions otherwise
Definition at line 32 of file Observation.cc.
References agent, eligible, features, sumAndPlot::i, and steps.
Referenced by libpg::CatObsActionTransform::CatObsActionTransform(), libpg::HMMTransform::HMMTransform(), Observation(), libpg::ObsWindowTransform::ObsWindowTransform(), libpg::PSRTransform::PSRTransform(), and libpg::RLAlg::RLAlg().
int libpg::Observation::getSteps ()
Get count of the number of steps in optimisation/evaluation so far. This may only be reset in between epochs (in the case of batch learning) Or after a complete learning reset (i.e., reset of parameters). Any part of the controller/agent code may use this. E.g., if the policy is non-stationary, or if step sizes need to be computed based on optimisation steps. It may only be set by the RLAlg class.
Definition at line 73 of file Observation.hh.
References steps.
Referenced by libpg::LSTDQController::accumulateGrad(), libpg::CyclicPolicyBias::doApprox(), libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), libpg::SoftmaxPolicy::getAction(), libpg::SARSAController::getAction(), libpg::QLearningController::getAction(), libpg::PSRTransform::getAction(), libpg::LSTDQController::getAction(), libpg::HMMTransform::getAction(), libpg::eGreedyPolicy::getAction(), Sequence::getObservation(), PSRCassandra::getObservation(), operator=(), and libpg::NACTransform::updateStatistics().
void libpg::Observation::setSteps (int s)
Set the number of steps. Only RLAlg should call this.
Parameters:
s new step number
Definition at line 79 of file Observation.hh.
References steps.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), libpg::PSRTransform::getAction(), libpg::HMMTransform::getAction(), and libpg::RLAlg::resetLearning().
void libpg::Observation::setAgent (int a)
set which agent this observation is destined for. Used by approximators and controllers that single out a particular part of the feature matrix depending on the agent.
Definition at line 87 of file Observation.hh.
References agent.
Referenced by libpg::FactoredApproximator::doApprox(), libpg::PSRTransform::getAction(), libpg::ObsWindowTransform::getAction(), libpg::HMMTransform::getAction(), libpg::FactoredController::getAction(), and libpg::FactoredController::getMostProbAction().
int libpg::Observation::getAgent ()
Find out which agent is being represented now. Assists with pulling out the correct part of the features, but exactly how this is done depends on the controller and approximators involved.
Definition at line 95 of file Observation.hh.
References agent.
Referenced by libpg::NeuralNet::doApprox(), libpg::MultidimensionalLookupTable::doApprox(), libpg::LookupTable::doApprox(), libpg::NeuralNet::feedbackGrad(), libpg::MultidimensionalLookupTable::feedbackGrad(), libpg::LookupTable::feedbackGrad(), libpg::PSRTransform::getAction(), libpg::ObsWindowTransform::getAction(), libpg::NACTransform::getAction(), libpg::HMMTransform::getAction(), libpg::CatObsActionTransform::getAction(), operator=(), and libpg::NACTransform::updateStatistics().
Matrix& libpg::Observation::getFeatures ()
Get the observation matrix.
Definition at line 100 of file Observation.hh.
References features.
Referenced by libpg::NACTransform::delayedInstantStep(), libpg::NeuralNet::doApprox(), libpg::MultidimensionalLookupTable::doApprox(), libpg::LookupTable::doApprox(), libpg::FactoredApproximator::doApprox(), libpg::NeuralNet::feedbackGrad(), libpg::MultidimensionalLookupTable::feedbackGrad(), libpg::LookupTable::feedbackGrad(), libpg::OLBFGS::getAction(), libpg::PSRTransform::getAction(), libpg::ObsWindowTransform::getAction(), libpg::NACTransform::getAction(), libpg::LSTDQController::getAction(), libpg::HMMTransform::getAction(), libpg::FactoredController::getAction(), libpg::CatObsActionTransform::getAction(), libpg::FactoredController::getMostProbAction(), MySimulator::getObservation(), ThreeState::getObservation(), SP38::SP38PGSimulator::getObservation(), Sequence::getObservation(), FunctionSim::getObservation(), GridSim::getObservation(), PSRCassandra::getObservation(), Cassandra::getObservation(), BlindCassandra::getObservation(), BeliefStateCassandra::getObservation(), libpg::HMMTransform::HMMTransform(), libpg::ObsWindowTransform::ObsWindowTransform(), operator=(), test(), and libpg::NACTransform::updateStatistics().
bVector& libpg::Observation::getEligible ()
Get the eligibility vector
Definition at line 105 of file Observation.hh.
References eligible.
Referenced by libpg::FactoredApproximatorMinUpdates::doApprox(), libpg::FactoredApproximator::doApprox(), libpg::FactoredApproximator::feedbackGrad(), libpg::ObsWindowTransform::getAction(), libpg::ImportanceSamplingController::getAction(), libpg::FactoredController::getAction(), libpg::BasicController::getAction(), libpg::FactoredController::getMostProbAction(), and operator=().
Observation & libpg::Observation::operator= (Observation & rhs)
Perfect copy of observation, including resizing
Definition at line 21 of file Observation.cc.
References agent, eligible, features, getAgent(), getEligible(), getFeatures(), getSteps(), and steps.
Member Data Documentation
Matrix libpg::Observation::features [protected]
The actual full observation, filled in by the simulator
Definition at line 16 of file Observation.hh.
Referenced by getFeatures(), init(), and operator=().
bVector libpg::Observation::eligible [protected]
A vector that describes which action are available It's up to a controller to decide how to use this, if at all. It is initialised to dimension=number of agents if agents>1 and the number of actions otherwise.
Note: This is not a boost::numeric::ublas vector, but an STL one !
Definition at line 26 of file Observation.hh.
Referenced by getEligible(), init(), and operator=().
int libpg::Observation::agent [protected]
Another optional variable designed for multiple controllers where the observation for each agent is encoded as a row or column of the observation vector. Determines which row or col should be used in the current controller. Basically an efficiency thing, avoiding copying a potentially large observation column into a stand alone column
Definition at line 37 of file Observation.hh.
Referenced by getAgent(), init(), operator=(), and setAgent().
int libpg::Observation::steps [protected]
A count of the number of steps in optimisation/evaluation so far. This may only be reset in between epochs (in the case of batch learning) Or after a complete learning reset (i.e., reset of parameters). Any part of the controller/agent code may use this. E.g., if the policy is non-stationary, or if step sizes need to be computed based on optimisation steps. It may only be set by the RLAlg class.
Definition at line 48 of file Observation.hh.
Referenced by getSteps(), init(), operator=(), and setSteps().