The PG Library: libpg::LSTDQController Class Reference
libpg::LSTDQController
libpg::LSTDQController Class Reference
#include <LSTDQController.hh>
Public Member Functions
LSTDQController (Approximator *approx, Policy *policy, double tdDiscount)
virtual ~LSTDQController ()
virtual void discountTrace ()
virtual void getAction (Observation &obs, Vector &action, bool learn=true)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual void resetTrace ()
virtual void resetGrad ()
virtual void accumulateGrad (Vector &reward, Observation &newObs)
virtual void instantStep (Vector &reward)
virtual void delayedInstantStep (double reward, int steps)
virtual void computeDirection (int steps)
virtual void batchStep ()
virtual void updateStatistics (double reward, int steps)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
virtual void reduce (Vector &v, Approximator::StatsEnum s)
virtual void setDiscount (double discount)
void doApprox (Observation &obs, Vector &output)
Protected Attributes
Policy * policy
double tdDiscount
int actions
int lstdqDimension
Vector previousPhi
Vector currentPhi
double lastReward
double oldReward
bool instantStepRequired
double discount
Vector values
Matrix AInverse
Vector lstdqTrace
Vector lstdqGrad
Vector lstdqWeights
Vector lstdqTD
Vector bVec
Matrix I
int lstdqSteps
Detailed Description
This is a subclass of BasicController, implementing an abstract value controller.
Definition at line 13 of file LSTDQController.hh.
Constructor & Destructor Documentation
libpg::LSTDQController::LSTDQController (Approximator * approx, Policy * policy, double tdDiscount)
Constructor. Set up additional vectors and matrices needed to implement natural actor critic.
Parameters:
actions the LSTDQCOntroller needs to know how many actions it has since the approximator doesn't know about actions in this case, only Q-values
Definition at line 23 of file LSTDQController.cc.
References AInverse, bVec, currentPhi, libpg::Approximator::getNumParams(), libpg::Approximator::getOutputDim(), I, IDENT_SCALE, instantStepRequired, lstdqDimension, lstdqSteps, lstdqTD, lstdqTrace, lstdqWeights, previousPhi, and values.
virtual libpg::LSTDQController::~LSTDQController () [virtual]
Definition at line 50 of file LSTDQController.hh.
Member Function Documentation
void libpg::LSTDQController::discountTrace () [virtual]
LSTDQ delays it's discounting till the end of a updateStatistics()
Reimplemented from libpg::BasicController.
Definition at line 64 of file LSTDQController.cc.
void libpg::LSTDQController::getAction (Observation & obs, Vector & action, bool learn = true) [virtual]
Just a wrapper that intercepts the new observation and completes the instant step from the last round if necessary.
Implements libpg::ValueController.
Definition at line 72 of file LSTDQController.cc.
References libpg::BasicController::approx, currentPhi, delayedInstantStep(), libpg::Approximator::doApprox(), libpg::Approximator::feedbackGrad(), libpg::Policy::getAction(), libpg::Observation::getFeatures(), libpg::BasicController::getInputDim(), libpg::Observation::getSteps(), instantStepRequired, lastReward, policy, previousPhi, libpg::Approximator::reduce(), libpg::Approximator::resetTrace(), libpg::Approximator::TRACES, and values.
virtual void libpg::LSTDQController::getMostProbAction (Observation & obs, Vector & action) [virtual]
Return the most probable action for evaluation purposes only.
Parameters:
Observation vector
empty vector to load with the most probably action
Reimplemented from libpg::ValueController.
Definition at line 55 of file LSTDQController.hh.
References NYI.
void libpg::LSTDQController::resetTrace () [virtual]
Reimplemented from libpg::BasicController.
Definition at line 115 of file LSTDQController.cc.
References AInverse, I, and lstdqTrace.
void libpg::LSTDQController::resetGrad () [virtual]
Just reset all learning elements. Note that these are not really gradients as the name of the function implies.
Reimplemented from libpg::BasicController.
Definition at line 126 of file LSTDQController.cc.
References AInverse, bVec, I, lstdqSteps, and lstdqTrace.
Referenced by batchStep().
void libpg::LSTDQController::accumulateGrad (Vector & reward, Observation & newObs) [virtual]
Used in batch mode only. Accumualtes a direction to change without doing a change in params. This is called instead of instantStep() to implement LSPI. RLAlgs like GPomdp and LineSearchAlg use this method.
Reimplemented from libpg::BasicController.
Definition at line 180 of file LSTDQController.cc.
References libpg::Observation::getSteps(), oldReward, and updateStatistics().
void libpg::LSTDQController::instantStep (Vector & reward) [virtual]
The assumption here is that the reward received is for the transition, i.e., the previous state, current state
Reimplemented from libpg::BasicController.
Definition at line 138 of file LSTDQController.cc.
References instantStepRequired, lastReward, and oldReward.
void libpg::LSTDQController::delayedInstantStep (double reward, int steps) [virtual]
Do the work that instantStep() would normally do. This is called from getAction() This assumes rewards are independent of the transition and next state.
Parameters:
reward the last reward received (between the previous action and current action)
steps the number of steps done
Definition at line 157 of file LSTDQController.cc.
References libpg::BasicController::approx, computeDirection(), instantStepRequired, lstdqWeights, libpg::Approximator::PARAMS, libpg::Approximator::scatter(), and updateStatistics().
Referenced by getAction().
void libpg::LSTDQController::computeDirection (int steps) [virtual]
Solve the system A^{-1} b = w
Parameters:
how many steps did we run to compute grad (not used)
Reimplemented from libpg::BasicController.
Definition at line 258 of file LSTDQController.cc.
References AInverse, bVec, and lstdqWeights.
Referenced by delayedInstantStep().
void libpg::LSTDQController::batchStep () [virtual]
Set the params to the new weights solution. Unlike the name implies, this is not a step. It's a new absolute solution. The name is reused to fit in with all the other controllers. Now just for batch mode, hence the reset
Reimplemented from libpg::BasicController.
Definition at line 272 of file LSTDQController.cc.
References libpg::BasicController::approx, lstdqWeights, libpg::Approximator::PARAMS, resetGrad(), and libpg::Approximator::scatter().
void libpg::LSTDQController::updateStatistics (double reward, int steps) [virtual]
Update the A matrix (actually, it's inverse) and bVec vector prior to solving the system.
Definition at line 192 of file LSTDQController.cc.
References AInverse, bVec, currentPhi, discount, lstdqSteps, lstdqTD, lstdqTrace, previousPhi, tdDiscount, and libpg::UBlasExtras::updateInverseMatrix().
Referenced by accumulateGrad(), and delayedInstantStep().
void libpg::LSTDQController::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::BasicController.
Definition at line 298 of file LSTDQController.cc.
References libpg::BasicController::approx, libpg::BasicController::getNumParams(), libpg::Approximator::GRADS, lstdqWeights, libpg::Approximator::PARAMS, libpg::Approximator::scatter(), and libpg::Approximator::TRACES.
void libpg::LSTDQController::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::BasicController.
Definition at line 281 of file LSTDQController.cc.
References libpg::BasicController::approx, libpg::BasicController::getNumParams(), libpg::Approximator::GRADS, lstdqWeights, NYI, libpg::Approximator::PARAMS, libpg::Approximator::reduce(), and libpg::Approximator::TRACES.
void libpg::LSTDQController::setDiscount (double discount) [virtual]
Takes a local copy of discount and passes it back down to next approx
Reimplemented from libpg::BasicController.
Definition at line 319 of file LSTDQController.cc.
References libpg::BasicController::approx, and libpg::Approximator::setDiscount().
void libpg::LSTDQController::doApprox (Observation & obs, Vector & output)
Definition at line 68 of file LSTDQController.hh.
References libpg::BasicController::approx, and libpg::Approximator::doApprox().
Member Data Documentation
Policy* libpg::LSTDQController::policy [protected]
Definition at line 20 of file LSTDQController.hh.
Referenced by getAction().
double libpg::LSTDQController::tdDiscount [protected]
Definition at line 21 of file LSTDQController.hh.
Referenced by updateStatistics().
int libpg::LSTDQController::actions [protected]
Definition at line 22 of file LSTDQController.hh.
int libpg::LSTDQController::lstdqDimension [protected]
Definition at line 26 of file LSTDQController.hh.
Referenced by LSTDQController().
Vector libpg::LSTDQController::previousPhi [protected]
Definition at line 28 of file LSTDQController.hh.
Referenced by getAction(), LSTDQController(), and updateStatistics().
Vector libpg::LSTDQController::currentPhi [protected]
Definition at line 29 of file LSTDQController.hh.
Referenced by getAction(), LSTDQController(), and updateStatistics().
double libpg::LSTDQController::lastReward [protected]
Definition at line 30 of file LSTDQController.hh.
Referenced by getAction(), and instantStep().
double libpg::LSTDQController::oldReward [protected]
Definition at line 31 of file LSTDQController.hh.
Referenced by accumulateGrad(), and instantStep().
bool libpg::LSTDQController::instantStepRequired [protected]
Definition at line 32 of file LSTDQController.hh.
Referenced by delayedInstantStep(), getAction(), instantStep(), and LSTDQController().
double libpg::LSTDQController::discount [protected]
Definition at line 34 of file LSTDQController.hh.
Referenced by updateStatistics().
Vector libpg::LSTDQController::values [protected]
Definition at line 36 of file LSTDQController.hh.
Referenced by getAction(), and LSTDQController().
Matrix libpg::LSTDQController::AInverse [protected]
Definition at line 37 of file LSTDQController.hh.
Referenced by computeDirection(), LSTDQController(), resetGrad(), resetTrace(), and updateStatistics().
Vector libpg::LSTDQController::lstdqTrace [protected]
Definition at line 38 of file LSTDQController.hh.
Referenced by LSTDQController(), resetGrad(), resetTrace(), and updateStatistics().
Vector libpg::LSTDQController::lstdqGrad [protected]
Definition at line 39 of file LSTDQController.hh.
Vector libpg::LSTDQController::lstdqWeights [protected]
Definition at line 40 of file LSTDQController.hh.
Referenced by batchStep(), computeDirection(), delayedInstantStep(), LSTDQController(), reduce(), and scatter().
Vector libpg::LSTDQController::lstdqTD [protected]
Definition at line 41 of file LSTDQController.hh.
Referenced by LSTDQController(), and updateStatistics().
Vector libpg::LSTDQController::bVec [protected]
Definition at line 42 of file LSTDQController.hh.
Referenced by computeDirection(), LSTDQController(), resetGrad(), and updateStatistics().
Matrix libpg::LSTDQController::I [protected]
Definition at line 43 of file LSTDQController.hh.
Referenced by LSTDQController(), resetGrad(), and resetTrace().
int libpg::LSTDQController::lstdqSteps [protected]
Definition at line 45 of file LSTDQController.hh.
Referenced by LSTDQController(), resetGrad(), and updateStatistics().