The PG Library: libpg::QLearningController Class Reference
libpg::QLearningController
libpg::QLearningController Class Reference
#include <QLearningController.hh>
Public Member Functions
QLearningController (Approximator *approx, Policy *policy, double tdDiscount)
virtual ~QLearningController ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void instantStep (Vector &reward)
virtual void discountTrace ()
virtual void setDiscount (double lambda)
Detailed Description
This is a subclass of ValueController, implementing a Watkin's Q-Learning Labda specific controller.
Definition at line 10 of file QLearningController.hh.
Constructor & Destructor Documentation
libpg::QLearningController::QLearningController (Approximator * approx, Policy * policy, double tdDiscount)
Q-Learning controller constructor
Parameters:
approx parameterised distribution we'll be using today
tdDicount temporal difference discount
Definition at line 19 of file QLearningController.cc.
References libpg::Approximator::getOutputDim().
libpg::QLearningController::~QLearningController () [virtual]
Q-Learning controller destructor
Definition at line 34 of file QLearningController.cc.
Member Function Documentation
void libpg::QLearningController::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Where the real coding is done to implement Q learning error calculation
Select the next action based on policy parameter
Parameters:
obs observation vector
action single position vector used to return the selected action
computeGrad flag used to enable learning from experience
Implements libpg::ValueController.
Definition at line 45 of file QLearningController.cc.
References libpg::BasicController::approx, libpg::Approximator::doApprox(), libpg::Policy::getAction(), and libpg::Observation::getSteps().
void libpg::QLearningController::instantStep (Vector & reward) [virtual]
Reimplemented from libpg::BasicController.
Definition at line 94 of file QLearningController.cc.
References libpg::BasicController::approx, and libpg::Approximator::instantStep().
void libpg::QLearningController::discountTrace () [virtual]
Updates the eligibility traces
Reimplemented from libpg::BasicController.
Definition at line 83 of file QLearningController.cc.
References libpg::BasicController::approx, libpg::Approximator::discountTrace(), libpg::Approximator::feedbackGrad(), and libpg::Approximator::resetTrace().
void libpg::QLearningController::setDiscount (double lambda) [virtual]
Reimplemented from libpg::BasicController.
Definition at line 102 of file QLearningController.cc.
References libpg::BasicController::approx, and libpg::Approximator::setDiscount().