The PG Library: libpg::UBlasExtras Class Reference
libpg::UBlasExtras
libpg::UBlasExtras Class Reference
#include <UBlasExtras.hh>
Static Public Member Functions
static bool containsNaN (Matrix &m)
static bool containsNaN (Vector &m)
static void randomize (Matrix &m, double maxRand)
static void invertMatrix (const Matrix &input, Matrix &inverse)
static void solveLinear (Matrix &A, Vector &b, Vector &x)
static void solveLinearCholesky (Matrix &A, Vector &b, Vector &x)
static void updateInverseMatrix (Matrix &inverse, Vector &c, Vector &d)
static void addMatrixToVector (Matrix &m, Vector &v, int s=0)
static void addScaledVectorToMatrix (double scale, Vector &v, Matrix &m, int s=0)
static double angle (Vector &v1, Vector &v2)
static void linearLeastSquares (Matrix &A, Vector &y, Vector &x)
static void svd (Matrix &A, Vector &s)
static size_t rank (Matrix &A)
static Matrix & pseudoInverse (Matrix &A, Matrix &Ainv)
static void linearLeastSquares_test ()
Detailed Description
Static methods to augment the general UBLAS library methods.
Definition at line 10 of file UBlasExtras.hh.
Member Function Documentation
bool libpg::UBlasExtras::containsNaN (Matrix & m) [static]
Check in a vector for NaNs Pretty slow!
Definition at line 189 of file UBlasExtras.cc.
References sumAndPlot::i, and sumAndPlot::m.
Referenced by libpg::HardLimitTransform::checkParams().
bool libpg::UBlasExtras::containsNaN (Vector & v) [static]
Check in a vector for NaNs Pretty slow!
Definition at line 179 of file UBlasExtras.cc.
References sumAndPlot::i.
void libpg::UBlasExtras::randomize (Matrix & m, double maxRand) [static]
Create a random matrix with entrie
Parameters:
matrix to randomize
maximum absolute value. Negative entries are also made.
Definition at line 44 of file UBlasExtras.cc.
References sumAndPlot::i, and sumAndPlot::m.
Referenced by libpg::NeuralNet::randomizeParams(), and libpg::LookupTable::randomizeParams().
void libpg::UBlasExtras::invertMatrix (const Matrix & input, Matrix & inverse) [static]
Matrix inversion routine. Uses lu_factorize and lu_substitute in uBLAS to invert a matrix
Parameters:
input matrix
destination for inverse.
Definition at line 62 of file UBlasExtras.cc.
void libpg::UBlasExtras::solveLinear (Matrix & A, Vector & b, Vector & x) [static]
Solve a linear system Ax=b for x. Assumes full rank.
Parameters:
A matrix
b vector
destination vector
Definition at line 88 of file UBlasExtras.cc.
Referenced by linearLeastSquares().
void libpg::UBlasExtras::solveLinearCholesky (Matrix & A, Vector & b, Vector & x) [static]
Perform singular value demomposition using clapack and the ublas bindings.
Parameters:
vector to put singular values in.
Definition at line 388 of file UBlasExtras.cc.
Referenced by linearLeastSquares().
void libpg::UBlasExtras::updateInverseMatrix (Matrix & inverse, Vector & c, Vector & d) [static]
Use Sherman-Morrison fomular to update inverse of a Matrix Formula: (A+cd')^-1 = A^-1 - (A^-1cd'A^-1) / (1+d'A^-1c)
Parameters:
A^-1 from previous step
vector c as in A_{t+1} = A_t + cd^T
vector d as in A_{t+1} = A_t + cd^T
Definition at line 111 of file UBlasExtras.cc.
References sumAndPlot::a, and sumAndPlot::b.
Referenced by libpg::NACTransform::updateStatistics(), and libpg::LSTDQController::updateStatistics().
void libpg::UBlasExtras::addMatrixToVector (Matrix & m, Vector & v, int s = 0) [static]
Parameters:
matrix to convert to a vector
output will be the sum of this input plus vectorised matrix.
requires,second arg dimension should be > size1()*size2() of first input matrix
starting point in the vector, this allows vectors to aggregate many small matricies. Defaults to 0
Definition at line 132 of file UBlasExtras.cc.
Referenced by libpg::NeuralNetBatch::reduce(), libpg::NeuralNet::reduce(), libpg::LookupTableBatch::reduce(), and libpg::LookupTable::reduce().
void libpg::UBlasExtras::addScaledVectorToMatrix (double scale, Vector & v, Matrix & m, int s = 0) [static]
split up scaled vector and add to matrix INPUT scale factor
Parameters:
output will be the sum of this input plus vectorised matrix.
requires,second arg dimension should be > size1()*size2() of first input matrix
starting point in the vector, this allows vectors to aggregate many small matricies. Defaults to 0
Definition at line 152 of file UBlasExtras.cc.
Referenced by libpg::NeuralNetBatch::scatter(), libpg::NeuralNet::scatter(), libpg::LookupTableBatch::scatter(), and libpg::LookupTable::scatter().
double libpg::UBlasExtras::angle (Vector & v1, Vector & v2) [static]
Compute the angle between two vectors Not very efficient. Output: radians
Definition at line 168 of file UBlasExtras.cc.
void libpg::UBlasExtras::linearLeastSquares (Matrix & A, Vector & y, Vector & x) [static]
Perform least squares regression. Should use cholesky solve here because A trans(A) is symmetric pos.
Parameters:
Matrix A with one sample per row
Vector y with observed outcomes
destination vector
Definition at line 206 of file UBlasExtras.cc.
References solveLinear(), and solveLinearCholesky().
Referenced by linearLeastSquares_test().
void libpg::UBlasExtras::svd (Matrix & A, Vector & s) [static]
Perform singular value demomposition using clapack and the ublas bindings.
Parameters:
vector to put singular values in.
Definition at line 278 of file UBlasExtras.cc.
References sumAndPlot::m, and sumAndPlot::min.
Referenced by rank().
size_t libpg::UBlasExtras::rank (Matrix & A) [static]
Compute rank of matrix based on SVD. Does not cope with noise beyond simple threshold for errors at machine precision level.
Parameters:
Matrix to take SVD of. Rank will be less or equal to smallest diim
Returns:
rank >= 0, <= size of smallest dim of A.
Definition at line 315 of file UBlasExtras.cc.
References sumAndPlot::s, and svd().
Matrix & libpg::UBlasExtras::pseudoInverse (Matrix & A, Matrix & Ainv) [static]
Compute pseudo inverse from SVD. If A = USB', where S is diagonal, then pseudo inverse is Ainv = BS^{-1}A'
Definition at line 335 of file UBlasExtras.cc.
References sumAndPlot::m, sumAndPlot::min, and sumAndPlot::s.
void libpg::UBlasExtras::linearLeastSquares_test () [static]
Definition at line 229 of file UBlasExtras.cc.
References sumAndPlot::b, and linearLeastSquares().