The PG Library: libpg::RLAlg Class Reference
libpg::RLAlg
libpg::RLAlg Class Reference
#include <RLAlg.hh>
Public Member Functions
RLAlg ()
RLAlg (Controller *controller, Simulator *simulator, double discount, double stepSize)
virtual ~RLAlg ()
virtual double doSteps (Vector &totalRewards, int steps, bool learn)=0
virtual double evaluate (Vector &totalRewards, int steps)
virtual double evaluateAndPrint (int stepsPerEpoch, int maxSteps)
virtual void setUseAutoBaseline (bool ubl)
virtual void setMaxSteps (int ms)
virtual void setMaxValue (int mv)
virtual void resetLearning ()
virtual double learn (int stepsPerEpoch, int maxTime=0, int maxSteps=0, double maxValue=0)
virtual double learnCore (int stepsPerEpoch, int &totalSteps)
virtual void saveBest (char *fname)
virtual char * getSaveName ()
virtual Controller * getController ()
virtual void write (char *fname)
virtual void read (char *fname)
virtual void printPerformanceInfo (bool printTitles, int steps, double avgReward, double maxParam, int seconds)
virtual void checkStepSize (double curr, double best, double last)
virtual void restoreBestParameters ()
virtual void setStepSize (double s)
virtual double getStepSize ()
virtual bool testForHalt (time_t secs, int steps, double val)
void setEpochsBetweenStepUpdates (int e)
void setThreshold (double t)
void setIncreaseFactor (double ifa)
void setDecreaseFactor (double df)
Protected Attributes
double maxVal
time_t maxTime
Vector baseline
bool useAutoBaseline
double stepSize
int maxSteps
int epochsBetweenStepUpdates
double threshold
double increaseFactor
double decreaseFactor
bool doSaves
char * saveName
Controller * controller
Simulator * simulator
Observation obs
Detailed Description
Definition at line 6 of file RLAlg.hh.
Constructor & Destructor Documentation
libpg::RLAlg::RLAlg ()
Definition at line 75 of file RLAlg.hh.
libpg::RLAlg::RLAlg (Controller * controller, Simulator * simulator, double discount, double stepSize)
Top level piece of glue for Policy gradient, link the controller and the simulator
Parameters:
Controller
Simulator (problem specific)
discount factor [0, 1]. If 1, trace must be reset occasionally or have 0 mean reward.
Definition at line 21 of file RLAlg.cc.
References baseline, doSaves, epochsBetweenStepUpdates, libpg::Simulator::getAgents(), libpg::Simulator::getNumActions(), libpg::Simulator::getObsCols(), libpg::Simulator::getObsRows(), libpg::Simulator::getRewardDim(), libpg::Observation::init(), obs, resetLearning(), saveName, libpg::Controller::setDiscount(), libpg::Controller::setStepSize(), and useAutoBaseline.
virtual libpg::RLAlg::~RLAlg () [virtual]
Definition at line 77 of file RLAlg.hh.
Member Function Documentation
virtual double libpg::RLAlg::doSteps (Vector & totalRewards, int steps, bool learn) [pure virtual]
The only abstract method
Implemented in libpg::GOALPomdp, libpg::GPomdp, and libpg::OLPomdp.
Referenced by learn(), and learnCore().
double libpg::RLAlg::evaluate (Vector & totalRewards, int steps) [virtual]
Just do an evaluation phase with the most probable action. This gives a different answer from doSteps without learning because doSteps is still following the stochastic policy.
Just do an evaluation phase with the most probable action. This gives a different answer from doSteps without learning because doSteps is still following the stochastic policy. If you are using your own controller, and you haven't implemented getMostProbAction, you will get the default behavious which is to just call getAction.
Parameters:
empty rewards vector to populate
number of steps to evaluate for
Definition at line 328 of file RLAlg.cc.
References controller, libpg::Simulator::doAction(), libpg::Simulator::getActionDim(), libpg::Simulator::getAgents(), libpg::Controller::getMostProbAction(), libpg::Simulator::getNumActions(), libpg::Simulator::getObsCols(), libpg::Simulator::getObservation(), libpg::Simulator::getObsRows(), libpg::Simulator::getReward(), libpg::Simulator::getRewardDim(), obs, sumAndPlot::s, and simulator.
Referenced by evaluateAndPrint().
double libpg::RLAlg::evaluateAndPrint (int stepsPerEpoch, int maxSteps) [virtual]
Acts a bit like learn, where evaluate is the equivalent of doSteps Does sets of stepsPerEpoch evaluations, but includes timing and printing of performance information.
Evaluate for a number of steps, then print the results
Parameters:
number of steps to evaluate before.
Definition at line 361 of file RLAlg.cc.
References controller, evaluate(), libpg::Controller::getMaxParam(), libpg::Simulator::getRewardDim(), printPerformanceInfo(), and simulator.
Referenced by evaluate().
virtual void libpg::RLAlg::setUseAutoBaseline (bool ubl) [virtual]
Automatically estimate the baseline over an epoch and subtract that baseline from any rewards in the next epoch. Do not use if your rewards are mostly 0 (results in less efficiency in gradient update), but generally a good idea otherwise.
Definition at line 104 of file RLAlg.hh.
References useAutoBaseline.
Referenced by Basic_NeuralNet(), ExploreBinaryControllerKnobs(), ExploreeGreedyKnobs(), ExploreFactoredBinaryControllersKnobs(), ExploreSoftmaxKnobs(), Factored_Binary_NeuralNet(), LSPI_NeuralNet_Softmax_Decaying(), LSPI_NeuralNet_Uniform_Random(), main(), NACTransform_Binary_NeuralNet(), OLBFGS_NeuralNet(), QLearning_NeuralNet_eGreedy_Constant(), QLearning_NeuralNet_eGreedy_Decaying(), QLearning_NeuralNet_Softmax_Decaying(), SARSA_NeuralNet_eGreedy_Constant(), SARSA_NeuralNet_eGreedy_Decaying(), SARSA_NeuralNet_Softmax_Decaying(), and SP38::SP38Optimisator::SP38Optimisator().
virtual void libpg::RLAlg::setMaxSteps (int ms) [virtual]
Set the maximum number of steps allowed before learning stops. A value of 0 means unlimited steps.
Definition at line 110 of file RLAlg.hh.
References maxSteps.
virtual void libpg::RLAlg::setMaxValue (int mv) [virtual]
Terminate when a threshold value is reached. 0 means no threshold (bummer if you want 0 to be the threshold)
Definition at line 116 of file RLAlg.hh.
References maxVal.
void libpg::RLAlg::resetLearning () [virtual]
Definition at line 47 of file RLAlg.cc.
References baseline, controller, obs, libpg::Controller::resetParams(), libpg::Controller::resetTrace(), and libpg::Observation::setSteps().
Referenced by RLAlg().
double libpg::RLAlg::learn (int stepsPerEpoch, int maxTime = 0, int ms = 0, double maxVal = 0) [virtual]
Do optimisation until either time expires or steps runs out. We train in epochs of a fixed number of steps, reporting after each epoch. We get the initial reward by running for an epoch without learning. This initial epoch does not count towards step totals or final long-term average reward or time
Parameters:
steps per epoch
time limit (0 for no limit [default])
steps (0 for no limit [default])
max value (0 for no limit [default])
Returns:
final epoch reward
Definition at line 98 of file RLAlg.cc.
References checkStepSize(), controller, doSaves, doSteps(), epochsBetweenStepUpdates, libpg::Controller::getMaxParam(), libpg::Simulator::getRewardDim(), learnCore(), maxSteps, printPerformanceInfo(), libpg::Controller::resetTrace(), saveName, simulator, testForHalt(), and write().
Referenced by ExploreBinaryControllerKnobs(), ExploreeGreedyKnobs(), ExploreFactoredBinaryControllersKnobs(), ExploreSoftmaxKnobs(), main(), main_crf(), optimise(), and SP38::SP38Optimisator::run().
double libpg::RLAlg::learnCore (int stepsPerEpoch, int & totalSteps) [virtual]
By default this is very simple, call doSteps for stepsPerEpoch times, leaving online learning to doSteps. In other RLAlgs this might call doSteps to build up a batch estimate and then do a line search.
Reimplemented in libpg::GPomdp, and libpg::LineSearchAlg.
Definition at line 186 of file RLAlg.cc.
References baseline, doSteps(), libpg::Simulator::getRewardDim(), simulator, and useAutoBaseline.
Referenced by learn().
void libpg::RLAlg::saveBest (char * fname) [virtual]
Provide the filename for regular paramter saves whenever we achieve a new best policy
Definition at line 208 of file RLAlg.cc.
References doSaves, and saveName.
Referenced by main(), main_crf(), optimise(), and SP38::SP38Optimisator::saveBestParameters().
virtual char* libpg::RLAlg::getSaveName () [virtual]
Definition at line 124 of file RLAlg.hh.
References saveName.
virtual Controller* libpg::RLAlg::getController () [virtual]
Return a pointer to the current controller
Definition at line 129 of file RLAlg.hh.
References controller.
void libpg::RLAlg::write (char * fname) [virtual]
Create an output stream and write all controller parameters to it.
Parameters:
file name to write to
Definition at line 220 of file RLAlg.cc.
References controller, and libpg::Controller::write().
Referenced by learn(), and main().
void libpg::RLAlg::read (char * fname) [virtual]
Restore controller parameters. Be careful to make sure your reading params from the same controller arch. There's no checks for this at present.
Parameters:
file name.
Definition at line 238 of file RLAlg.cc.
References controller, and libpg::Controller::read().
Referenced by checkStepSize(), evaluate(), SP38::SP38Optimisator::loadParameters(), and restoreBestParameters().
void libpg::RLAlg::printPerformanceInfo (bool printTitles, int steps, double avgReward, double maxParam, int seconds) [virtual]
Print a line of performance information
Parameters:
are we only printing the headers?
total number of steps so far
average reward over last epoch
maximum parameter
time elapsed so far.
Reimplemented in libpg::GOALPomdp.
Definition at line 65 of file RLAlg.cc.
References CWIDTH, and PRECISION.
Referenced by evaluateAndPrint(), learn(), and libpg::LineSearchAlg::learnCore().
void libpg::RLAlg::checkStepSize (double curr, double best, double last) [virtual]
Do automatic scalar step size update. Will be redundant if using SMD. Very dumb: attempts to back off quickly if policy dies catastrophically, and slowly increase if we stop learning fast enough. Should help to go to a more deterministic policy. This is not a substitute for a good initial step size, but it will hopefully save you if things go bad half way through optimisation.
Parameters:
current average reward
best average reward
average reward **last time checkStepSize** was called.
Definition at line 263 of file RLAlg.cc.
References controller, decreaseFactor, epochsBetweenStepUpdates, increaseFactor, read(), saveName, libpg::Controller::setStepSize(), stepSize, and threshold.
Referenced by learn().
void libpg::RLAlg::restoreBestParameters () [virtual]
Restore the best parameters recorded in file "savename". Should be used after optimisation, before using the policy.
Definition at line 299 of file RLAlg.cc.
References read(), and saveName.
void libpg::RLAlg::setStepSize (double s) [virtual]
Definition at line 310 of file RLAlg.cc.
References stepSize.
double libpg::RLAlg::getStepSize () [virtual]
Definition at line 314 of file RLAlg.cc.
References stepSize.
bool libpg::RLAlg::testForHalt (time_t secs, int steps, double val) [virtual]
User can override halting conditions with this function.
Returns:
true if user should halt.
Check all the halting conditions. This is provided for convenience of users to override for their own halting conditions.
Parameters:
wall clock time how long the current learn() call has been running
steps the total learning steps in the current learn() call
val the current long term average reward (over last epoch)
Returns:
true if optimisation should halt
Definition at line 170 of file RLAlg.cc.
References maxSteps, maxTime, and maxVal.
Referenced by learn().
void libpg::RLAlg::setEpochsBetweenStepUpdates (int e)
If non-zero attempt to use a naive automatics step size update. You'll need to tune the threshold, increasFactor, and decreaseFactor
Definition at line 154 of file RLAlg.hh.
References epochsBetweenStepUpdates.
void libpg::RLAlg::setThreshold (double t)
How much better or worse are tings allowed to get before attempting to change the step size.
Definition at line 160 of file RLAlg.hh.
References threshold.
void libpg::RLAlg::setIncreaseFactor (double ifa)
How much to increase step size by if slow
Definition at line 165 of file RLAlg.hh.
References increaseFactor.
void libpg::RLAlg::setDecreaseFactor (double df)
How much to decrease stepsize if bad
Definition at line 170 of file RLAlg.hh.
References decreaseFactor.
Member Data Documentation
double libpg::RLAlg::maxVal [protected]
Definition at line 10 of file RLAlg.hh.
Referenced by setMaxValue(), and testForHalt().
time_t libpg::RLAlg::maxTime [protected]
Definition at line 11 of file RLAlg.hh.
Referenced by testForHalt().
Vector libpg::RLAlg::baseline [protected]
Baseline for reward measure. The reward for each step will have the baseline subtracted from it. Idea is to reduce the variance in gradient estimates by turning the rewards into a zero mean process. Typical baseline is the long-term average reward, but that's not known. DEFAULT: 0.0 SEE-ALSO: useAutoBaseline();
Definition at line 22 of file RLAlg.hh.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), learnCore(), libpg::LineSearchAlg::learnCore(), libpg::GPomdp::learnCore(), resetLearning(), and RLAlg().
bool libpg::RLAlg::useAutoBaseline [protected]
If true, baseLine will always be set to the long-term average reward from the last epoch DEFAULT: false
Definition at line 28 of file RLAlg.hh.
Referenced by learnCore(), libpg::LineSearchAlg::learnCore(), libpg::GPomdp::learnCore(), main_crf(), RLAlg(), and setUseAutoBaseline().
double libpg::RLAlg::stepSize [protected]
Current step size
Definition at line 34 of file RLAlg.hh.
Referenced by checkStepSize(), getStepSize(), libpg::LineSearchAlg::lineSearch(), libpg::LineSearchAlg::lineSearchInit(), and setStepSize().
int libpg::RLAlg::maxSteps [protected]
Maximum number of steps allowed in total. 0=unlimited.
Definition at line 39 of file RLAlg.hh.
Referenced by learn(), libpg::LineSearchAlg::lineSearch(), setMaxSteps(), and testForHalt().
int libpg::RLAlg::epochsBetweenStepUpdates [protected]
Shall we automatically update the scalar step size using a naive algorithm.. Use with caution. Probably still requires a degree of fine tuning for a class of problems. Any SMD algorithm will ignore this.
Definition at line 47 of file RLAlg.hh.
Referenced by checkStepSize(), learn(), RLAlg(), and setEpochsBetweenStepUpdates().
double libpg::RLAlg::threshold [protected]
Definition at line 48 of file RLAlg.hh.
Referenced by checkStepSize(), and setThreshold().
double libpg::RLAlg::increaseFactor [protected]
Definition at line 49 of file RLAlg.hh.
Referenced by checkStepSize(), and setIncreaseFactor().
double libpg::RLAlg::decreaseFactor [protected]
Definition at line 50 of file RLAlg.hh.
Referenced by checkStepSize(), and setDecreaseFactor().
bool libpg::RLAlg::doSaves [protected]
If this is true we save whenever we get a best value so far
Definition at line 55 of file RLAlg.hh.
Referenced by learn(), RLAlg(), and saveBest().
char* libpg::RLAlg::saveName [protected]
Definition at line 56 of file RLAlg.hh.
Referenced by checkStepSize(), getSaveName(), learn(), restoreBestParameters(), RLAlg(), and saveBest().
Controller* libpg::RLAlg::controller [protected]
The top level controller, possibly with many babies under it
Definition at line 61 of file RLAlg.hh.
Referenced by checkStepSize(), libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), evaluate(), evaluateAndPrint(), getController(), libpg::LineSearchAlg::incrementLineSearch(), learn(), libpg::LineSearchAlg::learnCore(), libpg::GPomdp::learnCore(), libpg::LineSearchAlg::lineSearch(), libpg::LineSearchAlg::lineSearchInit(), read(), resetLearning(), and write().
Simulator* libpg::RLAlg::simulator [protected]
The simulator that knows about the environment
Definition at line 66 of file RLAlg.hh.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), evaluate(), evaluateAndPrint(), learn(), learnCore(), libpg::LineSearchAlg::learnCore(), and libpg::GPomdp::learnCore().
Observation libpg::RLAlg::obs [protected]
The observations passed to the simulator and controller
Definition at line 71 of file RLAlg.hh.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), evaluate(), resetLearning(), and RLAlg().