The PG Library: libpg::BinaryController Class Reference
libpg::BinaryController
libpg::BinaryController Class Reference
#include <BinaryController.hh>
Public Member Functions
BinaryController (Approximator *approx)
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void getMostProbAction (Observation &obs, Vector &action)
Detailed Description
Identical to BasicController except that the output dimension of the approximator must be 1, and we output the action as either 1, or 0 based on a logistic regression mapping of the single approx output to a probability of choosing 1 or 0. Halves the number of parameters needed in the case where decisions are binary.
Definition at line 14 of file BinaryController.hh.
Constructor & Destructor Documentation
libpg::BinaryController::BinaryController (Approximator * approx)
Parameters:
parameterised distribution we'll be using today
Definition at line 10 of file BinaryController.cc.
References libpg::Approximator::getOutputDim().
Member Function Documentation
void libpg::BinaryController::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Where the real coding is done to implement
Implement logistic regression to compute the probability of action=yes, or no. approximator output dimension must = 1
Parameters:
observation matrix
vector to store action in
shall we propogate the log action prob derivative back to approximator?
Reimplemented from libpg::BasicController.
Definition at line 26 of file BinaryController.cc.
References libpg::BasicController::approx, libpg::BasicController::dist, libpg::Approximator::doApprox(), and libpg::Approximator::feedbackGrad().
void libpg::BinaryController::getMostProbAction (Observation & obs, Vector & action) [virtual]
For evaluation purposes only. Select the most probable action
Parameters:
observation
a vector of length 1 to put in the binary action, 1 or 0.
Reimplemented from libpg::BasicController.
Definition at line 56 of file BinaryController.cc.
References libpg::BasicController::approx, libpg::BasicController::dist, and libpg::Approximator::doApprox().