The PG Library: libpg::CyclicPolicyBias Class Reference
libpg::CyclicPolicyBias
libpg::CyclicPolicyBias Class Reference
#include <CyclicPolicyBias.hh>
Public Member Functions
CyclicPolicyBias (Approximator *, int cycleTime, double bias)
virtual void doApprox (Observation &obs, Vector &output)
virtual void feedbackGrad (Observation &obs, Vector &deltas)
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void instantStep (double reward)
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetParams ()
virtual void randomizeParams (double maxRand)
virtual double getMaxParam ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void batchStep ()
virtual void accumulateGrad (double reward, Observation &newObs)
virtual void resetGrad ()
virtual void computeDirection (int steps)
virtual int getNumParams ()
virtual int getInputDim ()
virtual int getOutputDim ()
virtual void reduce (Vector &v, Approximator::StatsEnum s)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
Detailed Description
Knows about time using the clock from RLAlg in the features. Adds a constant to each approximator output based on the clock, and a phase time. Requires number of approximator outputs be a factor of the cycle time.
Definition at line 13 of file CyclicPolicyBias.hh.
Constructor & Destructor Documentation
libpg::CyclicPolicyBias::CyclicPolicyBias (Approximator * approx, int cycleTime, double bias)
Constructor, do whatever you need
See header for purpose of this approximator. Always sits on top of another controller that has parameters.
Definition at line 15 of file CyclicPolicyBias.cc.
References libpg::Approximator::getOutputDim().
Member Function Documentation
void libpg::CyclicPolicyBias::doApprox (Observation & obs, Vector & output) [virtual]
Adds constant to normal approximator
Implements libpg::Approximator.
Definition at line 38 of file CyclicPolicyBias.cc.
References libpg::Approximator::doApprox(), and libpg::Observation::getSteps().
void libpg::CyclicPolicyBias::feedbackGrad (Observation & obs, Vector & deltas) [virtual]
Everything else is just a pass through to the normal approximator
Implements libpg::Approximator.
Definition at line 49 of file CyclicPolicyBias.cc.
References libpg::Approximator::feedbackGrad().
void libpg::CyclicPolicyBias::discountTrace () [virtual]
Just multiply trace by discount factors
Implements libpg::Approximator.
Definition at line 53 of file CyclicPolicyBias.cc.
References libpg::Approximator::discountTrace().
void libpg::CyclicPolicyBias::setDiscount (double) [virtual]
Set the discount factors. Does not necessarily have to be constant.
Implements libpg::Approximator.
Definition at line 57 of file CyclicPolicyBias.cc.
References libpg::Approximator::setDiscount().
void libpg::CyclicPolicyBias::instantStep (double) [virtual]
Calculate instant gradient and step the parameters
Implements libpg::Approximator.
Definition at line 61 of file CyclicPolicyBias.cc.
References libpg::Approximator::instantStep().
void libpg::CyclicPolicyBias::setStepSize (double) [virtual]
Set the step size. Does not necessarily have to be a constant.
Implements libpg::Approximator.
Definition at line 65 of file CyclicPolicyBias.cc.
References libpg::Approximator::setStepSize().
void libpg::CyclicPolicyBias::resetTrace () [virtual]
Reset the eligibility trace to 0
Implements libpg::Approximator.
Definition at line 69 of file CyclicPolicyBias.cc.
References libpg::Approximator::resetTrace().
void libpg::CyclicPolicyBias::resetParams () [virtual]
Do whatever resetting the params means.
Implements libpg::Approximator.
Definition at line 73 of file CyclicPolicyBias.cc.
References libpg::Approximator::resetParams().
void libpg::CyclicPolicyBias::randomizeParams (double) [virtual]
Create a new random set of params.
Reimplemented from libpg::Approximator.
Definition at line 77 of file CyclicPolicyBias.cc.
References libpg::Approximator::randomizeParams().
double libpg::CyclicPolicyBias::getMaxParam () [virtual]
Retrieve largest absolute parameter value.
Implements libpg::Approximator.
Definition at line 81 of file CyclicPolicyBias.cc.
References libpg::Approximator::getMaxParam().
virtual void libpg::CyclicPolicyBias::write (std::ostream &) [virtual]
Read or write parameters
Reimplemented from libpg::Approximator.
virtual void libpg::CyclicPolicyBias::read (std::istream & o) [virtual]
Reimplemented from libpg::Approximator.
void libpg::CyclicPolicyBias::batchStep () [virtual]
Additional methods that are only for batch gradient algs Assuming we have accumulated a gradient somewhere, step in that direction.
Reimplemented from libpg::Approximator.
Definition at line 93 of file CyclicPolicyBias.cc.
References libpg::Approximator::batchStep().
void libpg::CyclicPolicyBias::accumulateGrad (double , Observation &) [virtual]
Calculate and accumulate instant gradient into a batch gradient estimate
Reimplemented from libpg::Approximator.
Definition at line 97 of file CyclicPolicyBias.cc.
References libpg::Approximator::accumulateGrad().
void libpg::CyclicPolicyBias::resetGrad () [virtual]
Reset the accumulated gradient only.
Reimplemented from libpg::Approximator.
Definition at line 101 of file CyclicPolicyBias.cc.
References libpg::Approximator::resetGrad().
void libpg::CyclicPolicyBias::computeDirection (int) [virtual]
Update the search direction for the parameters from the current gradient and possible past information. For GPOMDP and most codes this is empty. This could hold conjugation code Or it can extract natural actor critic search direction
Reimplemented from libpg::Approximator.
Definition at line 105 of file CyclicPolicyBias.cc.
References libpg::Approximator::computeDirection().
int libpg::CyclicPolicyBias::getNumParams () [virtual]
Constructor, do whatever you need to. Approximator() {};
Implements libpg::Approximator.
Definition at line 110 of file CyclicPolicyBias.cc.
References libpg::Approximator::getNumParams().
int libpg::CyclicPolicyBias::getInputDim () [virtual]
Query expected number of inputs
Implements libpg::Approximator.
Definition at line 115 of file CyclicPolicyBias.cc.
References libpg::Approximator::getInputDim().
int libpg::CyclicPolicyBias::getOutputDim () [virtual]
Query output dimension
Implements libpg::Approximator.
Definition at line 120 of file CyclicPolicyBias.cc.
References libpg::Approximator::getOutputDim().
void libpg::CyclicPolicyBias::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Approximator.
Definition at line 125 of file CyclicPolicyBias.cc.
References libpg::Approximator::reduce().
void libpg::CyclicPolicyBias::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Approximator.
Definition at line 130 of file CyclicPolicyBias.cc.
References libpg::Approximator::scatter().