The PG Library: SP38::FixedController Class Reference
SP38::FixedController
SP38::FixedController Class Reference
#include <FixedController.hh>
Public Member Functions
FixedController (Intersection *, SP38Simulation *, int, int, std::vector< int >)
virtual void getAction (libpg::Observation &obs, libpg::Vector &action, bool computeGrad=false)
virtual void computePartialsAndFeedback (libpg::Observation &, int, double)
virtual int getInputDim ()
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void instantStep (libpg::Vector &reward)
virtual void batchStep ()
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetGrad ()
virtual void resetParams ()
virtual void randomizeParams ()
virtual double getMaxParam ()
virtual int getNumParams ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void reduce (libpg::Vector &v, libpg::Approximator::StatsEnum s)
virtual void scatter (libpg::Vector &v, libpg::Approximator::StatsEnum s)
virtual void accumulateGrad (libpg::Vector &r, libpg::Observation &newObs)
virtual void computeDirection (int s)
Detailed Description
Fixed Controller. This controller alternates the phases with fixed given time interval.
Definition at line 20 of file FixedController.hh.
Constructor & Destructor Documentation
SP38::FixedController::FixedController (Intersection * i, SP38Simulation * sim, int os, int p, std::vector< int > pl)
Definition at line 7 of file FixedController.cc.
Member Function Documentation
void SP38::FixedController::getAction (libpg::Observation & obs, libpg::Vector & action, bool computeGrad = false) [virtual]
Main work horse, feed observations through, sample an action. Optionally accumulate instant log action grad directly to trace
Implements libpg::Controller.
Definition at line 12 of file FixedController.cc.
References SP38::SP38Simulation::getCurrentPhase(), SP38::SP38Simulation::getCurrentPhaseDuration(), SP38::SP38Simulation::getCurrentTime(), SP38::SP38Simulation::getLastRestartTime(), SP38::Intersection::getPhaseIndex(), and SP38::SP38Simulation::isAnythingScheduled().
virtual void SP38::FixedController::computePartialsAndFeedback (libpg::Observation & obs, int sampledAct, double weight) [virtual]
compute partial derivative of prob of action wrt a vector of likelihoods then feedback to the underlying parametersiation.
Implements libpg::Controller.
Definition at line 38 of file FixedController.hh.
virtual int SP38::FixedController::getInputDim () [virtual]
Find out what the input dimension of this controller is
Implements libpg::Controller.
Definition at line 39 of file FixedController.hh.
virtual void SP38::FixedController::discountTrace () [virtual]
Remaining methods just pass through to equivalent in Approximator
Implements libpg::Controller.
Definition at line 40 of file FixedController.hh.
virtual void SP38::FixedController::setDiscount (double discount) [virtual]
Implements libpg::Controller.
Definition at line 41 of file FixedController.hh.
virtual void SP38::FixedController::instantStep (libpg::Vector & reward) [virtual]
Reimplemented from libpg::Controller.
Definition at line 42 of file FixedController.hh.
virtual void SP38::FixedController::batchStep () [virtual]
Reimplemented from libpg::Controller.
Definition at line 43 of file FixedController.hh.
virtual void SP38::FixedController::setStepSize (double stepSize) [virtual]
Implements libpg::Controller.
Definition at line 44 of file FixedController.hh.
virtual void SP38::FixedController::resetTrace () [virtual]
Implements libpg::Controller.
Definition at line 45 of file FixedController.hh.
virtual void SP38::FixedController::resetGrad () [virtual]
Reimplemented from libpg::Controller.
Definition at line 46 of file FixedController.hh.
virtual void SP38::FixedController::resetParams () [virtual]
Implements libpg::Controller.
Definition at line 47 of file FixedController.hh.
virtual void SP38::FixedController::randomizeParams () [virtual]
Definition at line 48 of file FixedController.hh.
References NYI.
virtual double SP38::FixedController::getMaxParam () [virtual]
Implements libpg::Controller.
Definition at line 49 of file FixedController.hh.
virtual int SP38::FixedController::getNumParams () [virtual]
How many parameters does it have
Implements libpg::Controller.
Definition at line 50 of file FixedController.hh.
void SP38::FixedController::write (std::ostream & o) [virtual]
Reimplemented from libpg::Controller.
Definition at line 26 of file FixedController.cc.
References sumAndPlot::i.
void SP38::FixedController::read (std::istream & o) [virtual]
Reimplemented from libpg::Controller.
Definition at line 32 of file FixedController.cc.
References sumAndPlot::i.
virtual void SP38::FixedController::reduce (libpg::Vector & , libpg::Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Controller.
Definition at line 53 of file FixedController.hh.
virtual void SP38::FixedController::scatter (libpg::Vector & , libpg::Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Controller.
Definition at line 54 of file FixedController.hh.
virtual void SP38::FixedController::accumulateGrad (libpg::Vector & r, libpg::Observation & newObs) [virtual]
Reimplemented from libpg::Controller.
Definition at line 55 of file FixedController.hh.
virtual void SP38::FixedController::computeDirection (int s) [virtual]
Reimplemented from libpg::Controller.
Definition at line 56 of file FixedController.hh.