The PG Library: SP38::SP38Interface Class Reference
SP38::SP38Interface
SP38::SP38Interface Class Reference
#include <SP38Interface.hh>
Public Member Functions
SP38Interface (Scenario *sc, string host)
void set_noisy (bool)
void set_debug (bool)
void connect ()
void tryConnect ()
EventSet do_step (ScheduleSet ss)
bool is_simulation_running ()
string getStartTime ()
string getStartDate ()
void disconnect ()
Detailed Description
Implements the SP38 protocol.
Definition at line 71 of file SP38Interface.hh.
Constructor & Destructor Documentation
SP38::SP38Interface::SP38Interface (Scenario * sc, string hst)
Parameters:
Scenario being treated
IP of the simulator server
Definition at line 9 of file SP38Interface.cc.
References MAX_MESSAGE_SIZE, and SP38::OFF.
Member Function Documentation
void SP38::SP38Interface::set_noisy (bool v)
Parameters:
set general messages on or off
Definition at line 28 of file SP38Interface.cc.
Referenced by SP38::SP38Simulation::SP38Simulation().
void SP38::SP38Interface::set_debug (bool v)
Parameters:
set internal messages on or off
Definition at line 34 of file SP38Interface.cc.
Referenced by SP38::SP38Simulation::SP38Simulation().
void SP38::SP38Interface::connect ()
Connects and Starts the communication.
Definition at line 487 of file SP38Interface.cc.
References SocketException::description(), and tryConnect().
void SP38::SP38Interface::tryConnect ()
Try to connect to the server. It Will throw SocketException if can't connect.
Definition at line 499 of file SP38Interface.cc.
References CLIENT_READY_SP38, Sleep, and SP38::STARTED.
Referenced by connect(), and SP38::SP38Simulation::startSimulation().
EventSet SP38::SP38Interface::do_step (ScheduleSet ss)
Do one step of simulation, sending some schedules for signals and receiving detector events.
Parameters:
The set of schedules to be sent
Definition at line 519 of file SP38Interface.cc.
References CLIENT_CYCLE_FINISHED_SP38, CLIENT_SCHEDULE_DATA_SP38, SocketException::description(), disconnect(), SP38::RUNNING, SIMULATOR_CYCLE_FINISHED_SP38, SIMULATOR_END_SP38, SIMULATOR_FINISHED_SP38, SIMULATOR_UNKNOWN_SP38, and SP38::STARTED.
Referenced by SP38::SP38Simulation::doStep().
bool SP38::SP38Interface::is_simulation_running ()
Says if the simulation is running.
Definition at line 479 of file SP38Interface.cc.
References SP38::RUNNING, and SP38::STARTED.
Referenced by SP38::SP38Simulation::simulating().
string SP38::SP38Interface::getStartTime ()
Gets the time when the simulation started.
Definition at line 222 of file SP38Interface.cc.
Referenced by SP38::SP38Simulation::startSimulation().
string SP38::SP38Interface::getStartDate ()
Gets the date when the simulation started.
Definition at line 215 of file SP38Interface.cc.
Referenced by SP38::SP38Simulation::startSimulation().
void SP38::SP38Interface::disconnect ()
Disconnects and ends the communication.
Definition at line 568 of file SP38Interface.cc.
References SP38::ENDED.
Referenced by do_step(), and SP38::SP38Simulation::endSimulation().