The PG Library: libpg::PSRTransform Class Reference
libpg::PSRTransform
libpg::PSRTransform Class Reference
#include <PSRTransform.hh>
Public Member Functions
PSRTransform (Controller *controller, size_t maxHistory, size_t numObs, size_t numActions, double stepSize, int passesBeforeAdd, double minKappaForCore)
~PSRTransform ()
void setDiscover (bool discover)
virtual void setStepSize (double stepSize)
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
Classes
struct testEq
Detailed Description
Take observations and turn them into PSR prediction vector. Optinally learn PSR online.
Definition at line 11 of file PSRTransform.hh.
Constructor & Destructor Documentation
libpg::PSRTransform::PSRTransform (Controller * controller, size_t maxHistory, size_t numObs, size_t numActions, double stepSize, int passesBeforeAdd, double minKappaForCore)
Definition at line 27 of file PSRTransform.cc.
References ADD_ALL_CORES, APPEND_OBS, BINARY_OBS, DIGITS, libpg::Controller::getInputDim(), and libpg::Observation::init().
libpg::PSRTransform::~PSRTransform ()
Definition at line 122 of file PSRTransform.hh.
Member Function Documentation
void libpg::PSRTransform::setDiscover (bool discover)
Should core tests be updated
Definition at line 432 of file PSRTransform.cc.
void libpg::PSRTransform::setStepSize (double stepSize) [virtual]
Reimplemented from libpg::TransformController.
Definition at line 903 of file PSRTransform.cc.
References libpg::TransformController::controller, and libpg::Controller::setStepSize().
void libpg::PSRTransform::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
This is the top level routine in the step to step update of the PSR given an incoming observation.
Reimplemented from libpg::TransformController.
Definition at line 189 of file PSRTransform.cc.
References ADDCHRS, libpg::TransformController::controller, libpg::Controller::getAction(), libpg::Observation::getAgent(), libpg::Observation::getFeatures(), libpg::Controller::getMaxParam(), libpg::Observation::getSteps(), PSR_CONF_FREQ, libpg::Observation::setAgent(), and libpg::Observation::setSteps().