The PG Library: libpg::NeuralNetBatch Class Reference
libpg::NeuralNetBatch
libpg::NeuralNetBatch Class Reference
#include <NeuralNetBatch.hh>
Public Member Functions
NeuralNetBatch (Vector &dims, Vector &squash)
NeuralNetBatch (int in, int out)
virtual void batchStep ()
virtual void computeDirection (int steps)
virtual void accumulateGrad (double reward, Observation &newObs)
virtual void resetGrad ()
virtual void reduce (Vector &v, StatsEnum s)
virtual void scatter (Vector &v, StatsEnum s)
Public Attributes
Matrix * grads
Detailed Description
A version of neural network that supports aggregated gradients
Definition at line 13 of file NeuralNetBatch.hh.
Constructor & Destructor Documentation
libpg::NeuralNetBatch::NeuralNetBatch (Vector & dims, Vector & squash)
Same as neural network call, but additionaly resizes accumulated gradient matrices
Definition at line 35 of file NeuralNetBatch.cc.
References grads, and libpg::NeuralNet::layers.
libpg::NeuralNetBatch::NeuralNetBatch (int ins, int outs)
A version of neural network that supports aggregated gradients Create a new linear approximator with given inputs and outputs
Parameters:
ins input dimensionality
outs output dimensionality
Definition at line 20 of file NeuralNetBatch.cc.
References libpg::NeuralNet::dims, grads, and libpg::NeuralNet::layers.
Member Function Documentation
void libpg::NeuralNetBatch::batchStep () [virtual]
Additional methods that are only for batch gradient algs Assuming we have accumulated a gradient somewhere, step in that direction.
Reimplemented from libpg::Approximator.
Definition at line 46 of file NeuralNetBatch.cc.
References grads, libpg::NeuralNet::layerParams, libpg::NeuralNet::layers, and libpg::NeuralNet::stepSize.
void libpg::NeuralNetBatch::computeDirection (int) [virtual]
Update the search direction for the parameters from the current gradient and possible past information. For GPOMDP and most codes this is empty. This could hold conjugation code Or it can extract natural actor critic search direction
Reimplemented from libpg::Approximator.
Definition at line 55 of file NeuralNetBatch.cc.
References grads, and libpg::NeuralNet::layers.
void libpg::NeuralNetBatch::accumulateGrad (double , Observation &) [virtual]
Calculate and accumulate instant gradient into a batch gradient estimate
Reimplemented from libpg::Approximator.
Definition at line 63 of file NeuralNetBatch.cc.
References grads, libpg::NeuralNet::layers, and libpg::NeuralNet::layerTraces.
void libpg::NeuralNetBatch::resetGrad () [virtual]
Reset the accumulated gradient only.
Reimplemented from libpg::Approximator.
Definition at line 70 of file NeuralNetBatch.cc.
References grads, and libpg::NeuralNet::layers.
void libpg::NeuralNetBatch::reduce (Vector & v, StatsEnum s) [virtual]
Parameters:
s whether to collect params or grads or traces. Only grads done in this routine. Others passed to NeuralNet
Reimplemented from libpg::NeuralNet.
Definition at line 80 of file NeuralNetBatch.cc.
References libpg::UBlasExtras::addMatrixToVector(), grads, libpg::Approximator::GRADS, libpg::NeuralNet::layerParams, libpg::NeuralNet::layers, libpg::NeuralNet::parameters, and libpg::NeuralNet::reduce().
void libpg::NeuralNetBatch::scatter (Vector & v, StatsEnum s) [virtual]
Parameters:
s what to set, can't do GRADS here.
Reimplemented from libpg::NeuralNet.
Definition at line 100 of file NeuralNetBatch.cc.
References libpg::UBlasExtras::addScaledVectorToMatrix(), grads, libpg::Approximator::GRADS, libpg::NeuralNet::layerParams, libpg::NeuralNet::layers, libpg::NeuralNet::parameters, and libpg::NeuralNet::scatter().
Member Data Documentation
Matrix* libpg::NeuralNetBatch::grads
Definition at line 17 of file NeuralNetBatch.hh.
Referenced by accumulateGrad(), batchStep(), computeDirection(), NeuralNetBatch(), reduce(), resetGrad(), and scatter().