The PG Library: Socket Class Reference
Socket Class Reference
#include <Socket.hh>
Public Member Functions
Socket ()
virtual ~Socket ()
bool create ()
bool bind (const int port)
bool listen () const
bool accept (Socket &) const
bool connect (const std::string host, const int port)
bool send (const std::string) const
int recv (std::string &) const
bool send (const char *, size_t) const
int recv (char *) const
void set_non_blocking (const bool)
void set_tcp_no_delay ()
bool is_valid () const
Protected Attributes
int m_sock
sockaddr_in m_addr
Detailed Description
Definition at line 26 of file Socket.hh.
Constructor & Destructor Documentation
Socket::Socket ()
Definition at line 13 of file Socket.cc.
References m_addr.
Socket::~Socket () [virtual]
Definition at line 23 of file Socket.cc.
References is_valid(), and m_sock.
Member Function Documentation
bool Socket::create ()
Definition at line 29 of file Socket.cc.
References is_valid(), and m_sock.
Referenced by ClientSocket::ClientSocket(), and ServerSocket::ServerSocket().
bool Socket::bind (const int port)
Definition at line 51 of file Socket.cc.
References is_valid(), m_addr, and m_sock.
Referenced by ServerSocket::ServerSocket().
bool Socket::listen () const
Definition at line 79 of file Socket.cc.
References is_valid(), m_sock, and MAXCONNECTIONS.
Referenced by ServerSocket::ServerSocket().
bool Socket::accept (Socket & new_socket) const
Definition at line 98 of file Socket.cc.
References m_addr, and m_sock.
Referenced by ServerSocket::accept().
bool Socket::connect (const std::string host, const int port)
Definition at line 170 of file Socket.cc.
References is_valid(), m_addr, and m_sock.
Referenced by ClientSocket::ClientSocket().
bool Socket::send (const std::string s) const
Definition at line 110 of file Socket.cc.
Referenced by ServerSocket::operator<<(), ClientSocket::operator<<(), and send().
int Socket::recv (std::string & s) const
Definition at line 132 of file Socket.cc.
References MAXRECV.
Referenced by ServerSocket::operator>>(), ClientSocket::operator>>(), and recv().
bool Socket::send (const char * data, size_t size) const
Definition at line 116 of file Socket.cc.
References m_sock, and send().
int Socket::recv (char * data) const
Definition at line 141 of file Socket.cc.
References m_sock, MAXRECV, and recv().
void Socket::set_non_blocking (const bool)
Definition at line 189 of file Socket.cc.
References m_sock.
void Socket::set_tcp_no_delay ()
Definition at line 215 of file Socket.cc.
References m_sock, and TCP_NODELAY.
bool Socket::is_valid () const
Definition at line 51 of file Socket.hh.
References m_sock.
Referenced by bind(), connect(), create(), listen(), and ~Socket().
Member Data Documentation
int Socket::m_sock [protected]
Definition at line 55 of file Socket.hh.
Referenced by accept(), bind(), connect(), create(), is_valid(), listen(), recv(), send(), set_non_blocking(), set_tcp_no_delay(), and ~Socket().
sockaddr_in Socket::m_addr [protected]
Definition at line 56 of file Socket.hh.
Referenced by accept(), bind(), connect(), and Socket().