The PG Library: libpg Namespace Reference
libpg Namespace Reference
Classes
class Approximator
class BasicController
class Bias
class BinaryController
class CatObsActionTransform
class Controller
class CyclicPolicyBias
class eGreedyPolicy
class FactoredApproximator
class FactoredApproximatorMinUpdates
class FactoredController
class GOALPomdp
class GPomdp
class HardLimitTransform
class HMMTransform
class ImportanceSamplingController
class LineSearchAlg
class LookupTable
class LookupTableBatch
class LSTDQController
class MultidimensionalLookupTable
class NACTransform
class NeuralNet
class NeuralNetBatch
class Observation
class ObsWindowTransform
class OLPomdp
class Policy
class PSRTransform
class QLearningController
class RegressionController
class RegularizeTransform
class RLAlg
class Sampler
class SARSAController
class Simulator
class OLBFGS
class SoftmaxPolicy
class Teacher
class TransformApproximator
class TransformController
class UBlasExtras
class ValueController
Typedefs
typedef matrix
< double,
column_major > Matrix
typedef
symmetric_matrix
< double, lower,
column_major > SymmetricMatrix
typedef
mapped_matrix
< double,
column_major > SparseMatrix
typedef
boost::numeric::ublas::vector
< double > Vector
typedef
boost::numeric::ublas::vector
< bool > bVector
typedef
banded_matrix
< double > Diagonal
Functions
int power (int y, unsigned int x)
Detailed Description
$Id
Factored Approximator to aggregate independent approximators into one. Replaces old ManyToOneController concept.
Id
Id
Id
Id
Id
Id
Id
Id
Typedef Documentation
typedef boost::numeric::ublas::vector<bool> libpg::bVector
Boolean vector
Definition at line 62 of file PGBasics.hh.
typedef banded_matrix<double> libpg::Diagonal
Diagonal matrix
Definition at line 68 of file PGBasics.hh.
typedef matrix<double, column_major> libpg::Matrix
Normal matrix
Definition at line 42 of file PGBasics.hh.
typedef mapped_matrix<double, column_major> libpg::SparseMatrix
Mapped Matrix for sparse data.
Definition at line 52 of file PGBasics.hh.
typedef symmetric_matrix<double, lower, column_major> libpg::SymmetricMatrix
Symmetric matrix, mostly for least squares stuff.
Definition at line 47 of file PGBasics.hh.
typedef boost::numeric::ublas::vector<double> libpg::Vector
Normal vector
Definition at line 57 of file PGBasics.hh.
Function Documentation
int libpg::power (int y, unsigned int x)
Integer power function returns y raised to the x.
Definition at line 19 of file MultidimensionalLookupTable.cc.
Referenced by libpg::MultidimensionalLookupTable::doApprox(), libpg::MultidimensionalLookupTable::feedbackGrad(), and libpg::MultidimensionalLookupTable::MultidimensionalLookupTable().