The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraReader.hh File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraReader.hh File Reference
#include <map>
#include "Cassandra.hh"
Functions
Cassandra * readCassandra (ifstream &file)
list< string > tokenise (const string &line)
void processData (Matrix &m, istream &matrixData)
void processData (Matrix &m, int b, list< string >::iterator s, list< string >::iterator e)
void processData (Matrix &m, int b, istream &matrixData)
void processData (Matrix &m, int b, int c, string value)
void processData (Matrix &m, int b, int c, istream &matrixData)
int toIndex (map< string, int > map, string potentialIndex)
Function Documentation
void processData (Matrix & m, int b, int c, istream & matrixData)
void processData (Matrix & m, int b, int c, string value)
void processData (Matrix & m, int b, istream & matrixData)
void processData (Matrix & m, int b, list< string >::iterator s, list< string >::iterator e)
void processData (Matrix & m, istream & matrixData)
Cassandra* readCassandra (ifstream & file)
Definition at line 130 of file CassandraReader.cc.
References sumAndPlot::i, mergeProcessorOptimisatorOutput::line, processData(), toIndex(), and tokenise().
int toIndex (map< string, int > map, string potentialIndex)
Definition at line 122 of file CassandraReader.cc.
References sumAndPlot::i.
list<string> tokenise (const string & line)
Definition at line 21 of file CassandraReader.cc.