The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraTest.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/Cassandra/CassandraTest.cc File Reference
#include "PGBasics.hh"
#include "LookupTable.hh"
#include "LookupTableBatch.hh"
#include "NeuralNet.hh"
#include "NeuralNetBatch.hh"
#include "BasicController.hh"
#include "PSRTransform.hh"
#include "NACTransform.hh"
#include "CatObsActionTransform.hh"
#include "ObsWindowTransform.hh"
#include "MultidimensionalLookupTable.hh"
#include "HMMTransform.hh"
#include "BinaryController.hh"
#include "OLPomdp.hh"
#include "RegularizeTransform.hh"
#include "Ps.hh"
#include "CassandraReader.hh"
#include "BeliefStateCassandra.hh"
#include "BlindCassandra.hh"
#include "PSRCassandra.hh"
Defines
#define MLP_LAYERS 3
#define LINEAR_LAYERS 2
#define STR_BUF_LEN 1024
Functions
int CassandraTest (int argc, char **argv)
int main (int argc, char **argv)
Define Documentation
#define LINEAR_LAYERS 2
Definition at line 26 of file CassandraTest.cc.
Referenced by main().
#define MLP_LAYERS 3
Definition at line 25 of file CassandraTest.cc.
Referenced by main().
#define STR_BUF_LEN 1024
Definition at line 27 of file CassandraTest.cc.
Referenced by main().
Function Documentation
int CassandraTest (int argc, char ** argv)
int main (int argc, char ** argv)
Definition at line 50 of file CassandraTest.cc.
References Cassandra::getDiscount(), Cassandra::getNumActions(), Cassandra::getNumObs(), Cassandra::getNumStates(), Cassandra::getObsRows(), LINEAR_LAYERS, MLP_LAYERS, Cassandra::print(), libpg::Controller::randomizeParams(), readCassandra(), Cassandra::setCheat(), and STR_BUF_LEN.