The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/functionApprox/FunctionApprox.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/functionApprox/FunctionApprox.cc File Reference
#include "PGBasics.hh"
#include "NeuralNetBatch.hh"
#include "RegressionController.hh"
#include "OLPomdp.hh"
#include "FunctionSim.hh"
#include "OLBFGS.hh"
Defines
#define STEP_SIZE 0.0001
#define STEPS_PER_EPOCH 10000
#define PARAMS_FILE "final_params"
#define MAX_STEPS 10000000
#define LAYERS 3
#define HIDDEN 4
#define MAX_PARM 0.1
#define MEM_LENGTH 10
Functions
void test (Controller *controller)
int main (int argc, char **argv)
Define Documentation
#define HIDDEN 4
Definition at line 17 of file FunctionApprox.cc.
#define LAYERS 3
Definition at line 16 of file FunctionApprox.cc.
Referenced by main().
#define MAX_PARM 0.1
Definition at line 18 of file FunctionApprox.cc.
Referenced by main().
#define MAX_STEPS 10000000
Definition at line 14 of file FunctionApprox.cc.
#define MEM_LENGTH 10
Definition at line 19 of file FunctionApprox.cc.
Referenced by OLBFGS::init(), main(), and OLBFGS::updateDirection().
#define PARAMS_FILE "final_params"
Definition at line 13 of file FunctionApprox.cc.
Referenced by main().
#define STEP_SIZE 0.0001
Definition at line 11 of file FunctionApprox.cc.
#define STEPS_PER_EPOCH 10000
Definition at line 12 of file FunctionApprox.cc.
Function Documentation
int main (int argc, char ** argv)
Definition at line 23 of file FunctionApprox.cc.
References HIDDEN, LAYERS, libpg::RLAlg::learn(), MAX_PARM, MAX_STEPS, MEM_LENGTH, OBSCOLS, OBSDIM, PARAMS_FILE, libpg::Controller::randomizeParams(), libpg::Controller::read(), FunctionSim::SQR, STEP_SIZE, STEPS_PER_EPOCH, test(), and libpg::RLAlg::write().
void test (Controller * controller)
Definition at line 63 of file FunctionApprox.cc.
References libpg::Controller::getAction(), libpg::Observation::getFeatures(), MAXX, MINX, OBSCOLS, OBSDIM, and XINC.
Referenced by PSRCassandra::discoverPSR(), and main().