The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/TemplateRLApp/TemplateRLApp.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/TemplateRLApp/TemplateRLApp.cc File Reference
#include "PGBasics.hh"
#include "MySimulator.hh"
#include "NeuralNetBatch.hh"
#include "LookupTableBatch.hh"
#include "BasicController.hh"
#include "NACTransform.hh"
#include "eGreedyPolicy.hh"
#include "LSTDQController.hh"
#include "OLPomdp.hh"
Defines
#define NAC 0
#define LSPI 1
#define ALGORITHM NAC
#define MAX_STEPS 0
#define MAX_TIME 0
#define EPOCH_STEPS 1000
#define PARAMETER_FILE "parameters.txt"
#define LAMBDA 0.8
#define EXPLORATION_PROB 0.1
#define STEP_SIZE 0.00001
Functions
RLAlg * createRLAlg ()
void optimise ()
void evaluate (char *oldParametersFile)
int main (int argc, char **argv)
Define Documentation
#define ALGORITHM NAC
Definition at line 41 of file TemplateRLApp.cc.
Referenced by createRLAlg().
#define EPOCH_STEPS 1000
Definition at line 46 of file TemplateRLApp.cc.
Referenced by evaluate(), and optimise().
#define EXPLORATION_PROB 0.1
Definition at line 64 of file TemplateRLApp.cc.
Referenced by createRLAlg().
#define LAMBDA 0.8
Definition at line 56 of file TemplateRLApp.cc.
Referenced by createRLAlg().
#define LSPI 1
Definition at line 40 of file TemplateRLApp.cc.
Referenced by main().
#define MAX_STEPS 0
Definition at line 44 of file TemplateRLApp.cc.
#define MAX_TIME 0
Definition at line 45 of file TemplateRLApp.cc.
#define NAC 0
Definition at line 39 of file TemplateRLApp.cc.
Referenced by createRLAlg().
#define PARAMETER_FILE "parameters.txt"
Definition at line 54 of file TemplateRLApp.cc.
Referenced by optimise().
#define STEP_SIZE 0.00001
Definition at line 67 of file TemplateRLApp.cc.
Function Documentation
RLAlg* createRLAlg ()
Definition at line 82 of file TemplateRLApp.cc.
References ALGORITHM, EXPLORATION_PROB, MySimulator::getDiscountFactor(), MySimulator::getNumActions(), MySimulator::getObsRows(), LAMBDA, NAC, and STEP_SIZE.
Referenced by evaluate(), and optimise().
void evaluate (char * oldParametersFile)
Definition at line 126 of file TemplateRLApp.cc.
References createRLAlg(), EPOCH_STEPS, libpg::RLAlg::evaluateAndPrint(), MAX_STEPS, and libpg::RLAlg::read().
Referenced by main().
int main (int argc, char ** argv)
Main routine to switch between evaluation and optimisation
Definition at line 141 of file TemplateRLApp.cc.
References evaluate(), and optimise().
void optimise ()
Definition at line 112 of file TemplateRLApp.cc.
References createRLAlg(), EPOCH_STEPS, libpg::RLAlg::learn(), MAX_STEPS, MAX_TIME, PARAMETER_FILE, and libpg::RLAlg::saveBest().
Referenced by main().