The PG Library: /Users/daa/legacy/src/libpg/trunk/simulators/ThreeState/ThreeStateTest.cc File Reference
/Users/daa/legacy/src/libpg/trunk/simulators/ThreeState/ThreeStateTest.cc File Reference
#include "PGBasics.hh"
#include "ThreeState.hh"
#include "LookupTable.hh"
#include "LookupTableBatch.hh"
#include "NeuralNet.hh"
#include "NeuralNetBatch.hh"
#include "NACTransform.hh"
#include "SoftmaxPolicy.hh"
#include "eGreedyPolicy.hh"
#include "BasicController.hh"
#include "BinaryController.hh"
#include "ValueController.hh"
#include "SARSAController.hh"
#include "QLearningController.hh"
#include "FactoredController.hh"
#include "LSTDQController.hh"
#include "OLPomdp.hh"
#include "GPomdp.hh"
#include "LineSearchAlg.hh"
Classes
class Temp
class EpsilonDecay
Defines
#define TD_DISCOUNT 0.6
#define STEPS_PER_EPOCH 10000
#define MAX_STEPS 10000000
#define MAX_TIME 0
#define TEST_RUNS 1
#define NN_LAYERS 2
#define PARAM_FILE "ThreeState.params"
#define MAX_RAND_PARAM 0.00
#define APPROX_OUTPUTS 2
#define LINE_SEARCH_STEPS 20
#define TOLERANCE 1e-9
#define BACKOFF 3.0
#define EXPONENT_BASE 2.0
#define MAX_TRIES 16
#define DOWNHILL_THRESH 0.05
#define commonInit()
Functions
OLPomdp * SARSA_NeuralNet_Softmax_Decaying ()
OLPomdp * LSTDQ_NeuralNet_Softmax_Decaying ()
GPomdp * LSPI ()
OLPomdp * SARSA_NeuralNet_eGreedy_Constant ()
OLPomdp * SARSA_NeuralNet_eGreedy_Decaying ()
OLPomdp * QLearning_NeuralNet_Softmax_Decaying ()
OLPomdp * QLearning_NeuralNet_eGreedy_Constant ()
OLPomdp * QLearning_NeuralNet_eGreedy_Decaying ()
OLPomdp * Binary_NeuralNet ()
OLPomdp * NACTransform_Binary_NeuralNet ()
OLPomdp * Factored_Binary_NeuralNet ()
int main (int argc, char **argv)
Define Documentation
#define APPROX_OUTPUTS 2
Definition at line 59 of file ThreeStateTest.cc.
#define BACKOFF 3.0
Definition at line 62 of file ThreeStateTest.cc.
#define commonInit ()
Value:
Vector nnDims(NN_LAYERS); \
    nnDims[0] = OBS_DIM; \
    nnDims[1] = APPROX_OUTPUTS; \
    Vector squash(NN_LAYERS); \
    squash.clear();
Definition at line 119 of file ThreeStateTest.cc.
#define DOWNHILL_THRESH 0.05
Definition at line 65 of file ThreeStateTest.cc.
#define EXPONENT_BASE 2.0
Definition at line 63 of file ThreeStateTest.cc.
#define LINE_SEARCH_STEPS 20
Definition at line 60 of file ThreeStateTest.cc.
#define MAX_RAND_PARAM 0.00
Definition at line 58 of file ThreeStateTest.cc.
#define MAX_STEPS 10000000
Definition at line 53 of file ThreeStateTest.cc.
#define MAX_TIME 0
Definition at line 54 of file ThreeStateTest.cc.
#define MAX_TRIES 16
Definition at line 64 of file ThreeStateTest.cc.
#define NN_LAYERS 2
Definition at line 56 of file ThreeStateTest.cc.
#define PARAM_FILE "ThreeState.params"
Definition at line 57 of file ThreeStateTest.cc.
#define STEPS_PER_EPOCH 10000
Definition at line 52 of file ThreeStateTest.cc.
#define TD_DISCOUNT 0.6
Definition at line 51 of file ThreeStateTest.cc.
#define TEST_RUNS 1
Definition at line 55 of file ThreeStateTest.cc.
#define TOLERANCE 1e-9
Definition at line 61 of file ThreeStateTest.cc.
Function Documentation
OLPomdp* Binary_NeuralNet ()
Binary controller with neural net function approximator. First policy gradient method. Assumes two actions only.
Returns:
OLPomdp agent
Definition at line 369 of file ThreeStateTest.cc.
References OBS_DIM, and mergeProcessorOptimisatorOutput::step_size.
Referenced by main().
OLPomdp* Factored_Binary_NeuralNet ()
Factored Binary controller with neural net function approximator. This is an example of how to create multi-agent problems.
Returns:
OLPomdp agent
Definition at line 419 of file ThreeStateTest.cc.
References OBS_DIM, and mergeProcessorOptimisatorOutput::step_size.
GPomdp* LSPI ()
Least squares policy iteration. Note that this just uses LSTDQ as a value estimator, and a batch GPomdp algorithm to drive the policy updates.
Returns:
OLPomdp agent
Definition at line 194 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, commonInit, OBS_DIM, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* LSTDQ_NeuralNet_Softmax_Decaying ()
Q values estimated in an online way by LSTDQ. Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 162 of file ThreeStateTest.cc.
References APPROX_OUTPUTS, commonInit, OBS_DIM, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
Referenced by main().
int main (int argc, char ** argv)
If a command line parameter is provided it is treated as the id number of the algorithm to run. Otherwise we loop through all algorithms.
Definition at line 445 of file ThreeStateTest.cc.
References Binary_NeuralNet(), Factored_Binary_NeuralNet(), libpg::RLAlg::learn(), LSPI, LSTDQ_NeuralNet_Softmax_Decaying(), MAX_STEPS, MAX_TIME, NACTransform_Binary_NeuralNet(), QLearning_NeuralNet_eGreedy_Constant(), QLearning_NeuralNet_eGreedy_Decaying(), QLearning_NeuralNet_Softmax_Decaying(), SARSA_NeuralNet_eGreedy_Constant(), SARSA_NeuralNet_eGreedy_Decaying(), SARSA_NeuralNet_Softmax_Decaying(), and STEPS_PER_EPOCH.
OLPomdp* NACTransform_Binary_NeuralNet ()
NAC Transform with Binary controller with neural net function approximator.
Returns:
OLPomdp agent
Definition at line 396 of file ThreeStateTest.cc.
References OBS_DIM, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* QLearning_NeuralNet_eGreedy_Constant ()
QLearning controller with linear function approximator and e-Greedy policy (constant epsilon).
Returns:
OLPomdp agent
Definition at line 313 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* QLearning_NeuralNet_eGreedy_Decaying ()
QLearning controller with linear function approximator and e-Greedy policy (decaying epsilon).
Returns:
OLPomdp agent
Definition at line 340 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* QLearning_NeuralNet_Softmax_Decaying ()
QLearning controller with linear function approximator and Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 285 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* SARSA_NeuralNet_eGreedy_Constant ()
SARSA controller with linear function approximator and e-Greedy policy (constant epsilon).
Returns:
OLPomdp agent
Definition at line 231 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* SARSA_NeuralNet_eGreedy_Decaying ()
SARSA controller with linear function approximator and e-Greedy policy (decaying epsilon).
Returns:
OLPomdp agent
Definition at line 258 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.
OLPomdp* SARSA_NeuralNet_Softmax_Decaying ()
SARSA controller with linear function approximator and Softmax policy (decaying temperature).
Returns:
OLPomdp agent
Definition at line 132 of file ThreeStateTest.cc.
References commonInit, mergeProcessorOptimisatorOutput::step_size, and TD_DISCOUNT.