The PG Library: MyVector Class Reference
MyVector Class Reference
#include <MyVector.h>
Public Member Functions
void shiftLeft (Vector &newElement)
void shiftLeft (double newElement)
MyVector (VVector *temp)
MyVector ()
Detailed Description
Definition at line 6 of file MyVector.h.
Constructor & Destructor Documentation
MyVector::MyVector (VVector * temp)
Definition at line 27 of file MyVector.cc.
MyVector::MyVector ()
Definition at line 32 of file MyVector.cc.
Member Function Documentation
void MyVector::shiftLeft (Vector & newElement)
Definition at line 8 of file MyVector.cc.
References sumAndPlot::i.
Referenced by shiftLeft(), and OLBFGS::updateDirection().
void MyVector::shiftLeft (double newElement)
Definition at line 19 of file MyVector.cc.
References shiftLeft().