The PG Library: SP38::SimpleDynamicController Class Reference
SP38::SimpleDynamicController
SP38::SimpleDynamicController Class Reference
#include <SimpleDynamicController.hh>
Public Member Functions
SimpleDynamicController (Intersection *, SP38Simulation *, int)
virtual void getAction (libpg::Observation &obs, libpg::Vector &action, bool computeGrad=false)
virtual void computePartialsAndFeedback (libpg::Observation &, int, double)
virtual int getInputDim ()
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void instantStep (libpg::Vector &reward)
virtual void batchStep ()
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetGrad ()
virtual void resetParams ()
virtual void randomizeParams ()
virtual double getMaxParam ()
virtual int getNumParams ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void reduce (libpg::Vector &v, libpg::Approximator::StatsEnum s)
virtual void scatter (libpg::Vector &v, libpg::Approximator::StatsEnum s)
virtual void accumulateGrad (libpg::Vector &r, libpg::Observation &newObs)
virtual void computeDirection (int s)
Detailed Description
A Simple Dynamic Controller. The SimpleDynamicController implements an adaptive signal controlling that for a fixed phases sequence and cycle duration will set the phases's lenghts propotional to their vehicles throughputs in some past cycle.
Definition at line 22 of file SimpleDynamicController.hh.
Constructor & Destructor Documentation
SP38::SimpleDynamicController::SimpleDynamicController (Intersection * i, SP38Simulation * sim, int cs)
Definition at line 7 of file SimpleDynamicController.cc.
References SP38::Intersection::phases.
Member Function Documentation
void SP38::SimpleDynamicController::getAction (libpg::Observation & obs, libpg::Vector & action, bool computeGrad = false) [virtual]
Main work horse, feed observations through, sample an action. Optionally accumulate instant log action grad directly to trace
Implements libpg::Controller.
Definition at line 16 of file SimpleDynamicController.cc.
References SP38::SP38Simulation::getCurrentPhase(), SP38::SP38Simulation::getCurrentPhaseDuration(), SP38::SP38Simulation::getCurrentTime(), SP38::Intersection::getId(), SP38::Intersection::getPhaseIndex(), SP38::SP38Simulation::getPhaseMaxDetectorThroughputBetween(), SP38::SP38Simulation::isAnythingScheduled(), and SP38::Intersection::phases.
virtual void SP38::SimpleDynamicController::computePartialsAndFeedback (libpg::Observation & obs, int sampledAct, double weight) [virtual]
compute partial derivative of prob of action wrt a vector of likelihoods then feedback to the underlying parametersiation.
Implements libpg::Controller.
Definition at line 41 of file SimpleDynamicController.hh.
virtual int SP38::SimpleDynamicController::getInputDim () [virtual]
Find out what the input dimension of this controller is
Implements libpg::Controller.
Definition at line 42 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::discountTrace () [virtual]
Remaining methods just pass through to equivalent in Approximator
Implements libpg::Controller.
Definition at line 43 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::setDiscount (double discount) [virtual]
Implements libpg::Controller.
Definition at line 44 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::instantStep (libpg::Vector & reward) [virtual]
Reimplemented from libpg::Controller.
Definition at line 45 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::batchStep () [virtual]
Reimplemented from libpg::Controller.
Definition at line 46 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::setStepSize (double stepSize) [virtual]
Implements libpg::Controller.
Definition at line 47 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::resetTrace () [virtual]
Implements libpg::Controller.
Definition at line 48 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::resetGrad () [virtual]
Reimplemented from libpg::Controller.
Definition at line 49 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::resetParams () [virtual]
Implements libpg::Controller.
Definition at line 50 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::randomizeParams () [virtual]
Definition at line 51 of file SimpleDynamicController.hh.
References NYI.
virtual double SP38::SimpleDynamicController::getMaxParam () [virtual]
Implements libpg::Controller.
Definition at line 52 of file SimpleDynamicController.hh.
virtual int SP38::SimpleDynamicController::getNumParams () [virtual]
How many parameters does it have
Implements libpg::Controller.
Definition at line 53 of file SimpleDynamicController.hh.
void SP38::SimpleDynamicController::write (std::ostream & o) [virtual]
Reimplemented from libpg::Controller.
Definition at line 64 of file SimpleDynamicController.cc.
void SP38::SimpleDynamicController::read (std::istream & o) [virtual]
Reimplemented from libpg::Controller.
Definition at line 68 of file SimpleDynamicController.cc.
virtual void SP38::SimpleDynamicController::reduce (libpg::Vector & , libpg::Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Controller.
Definition at line 56 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::scatter (libpg::Vector & , libpg::Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Controller.
Definition at line 57 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::accumulateGrad (libpg::Vector & r, libpg::Observation & newObs) [virtual]
Reimplemented from libpg::Controller.
Definition at line 58 of file SimpleDynamicController.hh.
virtual void SP38::SimpleDynamicController::computeDirection (int s) [virtual]
Reimplemented from libpg::Controller.
Definition at line 59 of file SimpleDynamicController.hh.