The PG Library: SP38::PhaseHistory Class Reference
SP38::PhaseHistory
SP38::PhaseHistory Class Reference
#include <PhaseHistory.hh>
Public Member Functions
PhaseHistory (Phase *, int *, int)
Phase * getPhase ()
void setInitialState ()
void activate ()
void deactivate ()
void activate (int)
void deactivate (int)
bool isActive ()
bool wasActive (int)
int lastDeactivation ()
int lastActivation ()
int totalActiveTime (int)
int totalActiveTime (int, int)
vector< int > getActivationsIntervals (int, int)
bool insertTimeInHistory (int)
Detailed Description
The history of a Signal Phase of an intersection
Definition at line 15 of file PhaseHistory.hh.
Constructor & Destructor Documentation
SP38::PhaseHistory::PhaseHistory (Phase * p, int * ct, int max_h)
PhaseHistory constructor.
Definition at line 11 of file PhaseHistory.cc.
Member Function Documentation
Phase * SP38::PhaseHistory::getPhase ()
Gets the phase.
Definition at line 29 of file PhaseHistory.cc.
void SP38::PhaseHistory::setInitialState ()
Sets the phase history as a valid initial state for a simulation.
Definition at line 21 of file PhaseHistory.cc.
References deactivate(), and isActive().
void SP38::PhaseHistory::activate ()
Sets the Phase as active for the current time.
Definition at line 57 of file PhaseHistory.cc.
Referenced by SP38::SP38Simulation::setNewPhase().
void SP38::PhaseHistory::deactivate ()
Sets the Phase as inactive for the current time.
Definition at line 76 of file PhaseHistory.cc.
Referenced by setInitialState(), and SP38::SP38Simulation::setNewPhase().
void SP38::PhaseHistory::activate (int time)
Sets the Phase as active for the time given.
Parameters:
activation time
Definition at line 65 of file PhaseHistory.cc.
References insertTimeInHistory().
void SP38::PhaseHistory::deactivate (int time)
Sets the Phase as inactive for the current time.
Parameters:
Deactivation time
Definition at line 84 of file PhaseHistory.cc.
References insertTimeInHistory().
bool SP38::PhaseHistory::isActive ()
Says if the phase is currently active.
Definition at line 36 of file PhaseHistory.cc.
References wasActive().
Referenced by setInitialState().
bool SP38::PhaseHistory::wasActive (int time)
Definition at line 40 of file PhaseHistory.cc.
References sumAndPlot::i.
Referenced by isActive().
int SP38::PhaseHistory::lastDeactivation ()
Gets the time of the last deactivation.
Definition at line 141 of file PhaseHistory.cc.
int SP38::PhaseHistory::lastActivation ()
Gets the time of the last activation.
Definition at line 134 of file PhaseHistory.cc.
Referenced by SP38::IntersectionHistory::getCurrentPhaseDuration(), and SP38::SP38Simulation::setNewPhase().
int SP38::PhaseHistory::totalActiveTime (int start)
Gets the total active time units from start time to current time.
Parameters:
Time to start couting active time units
Definition at line 149 of file PhaseHistory.cc.
Referenced by SP38::SP38Simulation::getPhaseDurationBetween(), SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween(), and SP38::IntersectionHistory::getPhaseThroughputBetween().
int SP38::PhaseHistory::totalActiveTime (int start, int end)
Gets the total active time units from start time to end time.
Parameters:
Time to start couting active time units
Time to stop couting active time units
Definition at line 158 of file PhaseHistory.cc.
References getActivationsIntervals(), and sumAndPlot::i.
vector< int > SP38::PhaseHistory::getActivationsIntervals (int start, int end)
Gets the activations intervals between a given interval.
Parameters:
Start of the interval
End of the interval
Definition at line 173 of file PhaseHistory.cc.
References sumAndPlot::i, sumAndPlot::max, and sumAndPlot::min.
Referenced by SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween(), SP38::IntersectionHistory::getPhaseThroughputBetween(), and totalActiveTime().
bool SP38::PhaseHistory::insertTimeInHistory (int time)
Insert the time given in the history keeping it ordered.
Parameters:
the time to be inserted
Returns:
True if the time given was inserted in the end of the history
Definition at line 98 of file PhaseHistory.cc.
Referenced by activate(), and deactivate().