The PG Library: SP38::SP38Optimisator Class Reference
SP38::SP38Optimisator
SP38::SP38Optimisator Class Reference
#include <SP38Optimisator.hh>
Public Member Functions
SP38Optimisator (string)
SP38Optimisator (ScenarioReader *, string, int, double, double, bool, bool, bool, bool, int, bool)
void saveBestParameters (string)
void loadParameters (string)
ScenarioReader * getScenarioReader (string, string)
libpg::Controller * getController (Intersection *, string)
void setIntersectionTimes (Intersection *, string)
RewardType getRewardType (string)
void setStepsPerEpoch (uint)
void run ()
Detailed Description
The SP38 Reinforcement Learning Optimisator.
Definition at line 81 of file SP38Optimisator.hh.
Constructor & Destructor Documentation
SP38::SP38Optimisator::SP38Optimisator (string cf)
SP38Optimisator constructor. Set up the simulator and controllers based on the given configuration file.
Parameters:
configuration file
Definition at line 49 of file SP38Optimisator.cc.
References ConfigFile::file_not_found::filename, getController(), getRewardType(), SP38::SP38PGSimulator::getScenario(), getScenarioReader(), sumAndPlot::i, SP38::Scenario::intersections, ConfigFile::key_not_found::key, loadParameters(), ConfigFile::read(), saveBestParameters(), SP38::Scenario::setCycleDuration(), setIntersectionTimes(), libpg::RLAlg::setUseAutoBaseline(), SP38::SP38PGSimulator::setUsingAllPhasesDurationFeature(), SP38::SP38PGSimulator::setUsingConstantFeature(), SP38::SP38PGSimulator::setUsingCurrentPhaseFeature(), SP38::SP38PGSimulator::setUsingCycleDurationFeature(), SP38::SP38PGSimulator::setUsingDayHourFeature(), SP38::SP38PGSimulator::setUsingDetectorActiveFeature(), SP38::SP38PGSimulator::setUsingIgnoredFeature(), SP38::SP38PGSimulator::setUsingPhaseDurationFeature(), SP38::SP38PGSimulator::setUsingPhasesHistoryFeature(), SP38_CVN_ALL_PHASES_DUR_FEATURE, SP38_CVN_ALL_PHASES_IN_CYCLE, SP38_CVN_AUTO_BASE_LINE, SP38_CVN_CONFIGURATION_SUFIX, SP38_CVN_CONSTANT_FEATURE, SP38_CVN_CONTROLLER_SUFIX, SP38_CVN_CUR_PHASE_FEATURE, SP38_CVN_CYCLE_DUR_FEATURE, SP38_CVN_CYCLE_DURATION, SP38_CVN_DAY_HOUR_FEATURE, SP38_CVN_DEBUG, SP38_CVN_DEBUG_SP38_PROTOCOL, SP38_CVN_DETECTOR_ACTIV_FEATURE, SP38_CVN_EPOCH_SIZE, SP38_CVN_IGNORED_FEATURE, SP38_CVN_INSTANCE_FORMAT, SP38_CVN_INSTANCE_PATH, SP38_CVN_INTERSECTION_PREFIX, SP38_CVN_LEARNER_DISCOUNT, SP38_CVN_LEARNER_STEP_SIZE, SP38_CVN_MAX_CONNECT_TRIES, SP38_CVN_NOISY, SP38_CVN_PARAMETERS, SP38_CVN_PHASE_DUR_FEATURE, SP38_CVN_PHASES_HISTORY_FEATURE, SP38_CVN_PRINT_CONFIGURATION, SP38_CVN_REWARD_TYPE, SP38_CVN_RUN_FOREVER, SP38_CVN_SAVE_PARAMETERS, SP38_CVN_SERVER_HOST, and SP38_CVN_TIME_STEP_DURATION.
SP38::SP38Optimisator::SP38Optimisator (ScenarioReader * sr, string host, int spe, double discount, double step_size, bool fapc, bool f, bool d, bool n, int maxt, bool id)
SP38Optimisator constructor. Set up the simulator and the learning controllers.
Parameters:
ScenarioReader for the instance
Simulator's IP
How many steps per epoch (libpg configuration)
Discount for the NAC
Step size for gradient methods
Force the All Phases in cycle constraint
Execute optimisation forever
Show debug messages
Show some general messages
Maximum connection tries
Show debug messages for the SP38 protocol
Definition at line 23 of file SP38Optimisator.cc.
References DEFAULT_SIM_STEP_SIZE, getController(), SP38::SP38PGSimulator::getScenario(), sumAndPlot::i, SP38::Scenario::intersections, SP38::RT_LocalReward, and SP38_CVV_NAC_CONTROLLER.
Member Function Documentation
void SP38::SP38Optimisator::saveBestParameters (string file)
Saves best parameters found in a file.
Parameters:
the filename
Definition at line 283 of file SP38Optimisator.cc.
References libpg::RLAlg::saveBest().
Referenced by SP38Optimisator().
void SP38::SP38Optimisator::loadParameters (string file)
Loads parameters from a file.
Parameters:
the filename
Definition at line 292 of file SP38Optimisator.cc.
References libpg::RLAlg::read().
Referenced by SP38Optimisator().
ScenarioReader * SP38::SP38Optimisator::getScenarioReader (string format, string path)
Gets the right instace format reader for the asked file format.
Parameters:
the file format (Artemis, Paramics etc)
the instance path
Definition at line 156 of file SP38Optimisator.cc.
References SP38_CVV_INST_FORMAT_ARTEMIS, SP38_CVV_INST_FORMAT_PARAMICS, and SP38_CVV_INST_FORMAT_RTA1.
Referenced by SP38Optimisator().
libpg::Controller * SP38::SP38Optimisator::getController (Intersection * intersection, string desc)
Gets the right controller with parameters for the description asked.
Parameters:
the controller description
Definition at line 201 of file SP38Optimisator.cc.
References SP38::Intersection::getId(), SP38::SP38PGSimulator::getObsRows(), SP38::SP38PGSimulator::getSP38Simulation(), SP38::Intersection::getTotalPhases(), sumAndPlot::i, SP38::Intersection::phases, SP38_CVN_CONTROLLER_SUFIX, SP38_CVN_INTERSECTION_PREFIX, SP38_CVV_DYNAMIC_CONTROLLER, SP38_CVV_FIXED_CONTROLLER, SP38_CVV_NAC_CONTROLLER, and SP38_CVV_OLPOMDP_CONTROLLER.
Referenced by SP38Optimisator().
void SP38::SP38Optimisator::setIntersectionTimes (Intersection * i, string conf)
Sets the yellow duration, inter green and minimum green time for an intersection.
Parameters:
the intersection
the configuration
Definition at line 175 of file SP38Optimisator.cc.
References SP38::Intersection::getId(), SP38::Intersection::setInterGreenInterval(), SP38::Intersection::setMinimumGreenDuration(), SP38::Intersection::setYellowDuration(), SP38_CVN_CONFIGURATION_SUFIX, and SP38_CVN_INTERSECTION_PREFIX.
Referenced by SP38Optimisator().
RewardType SP38::SP38Optimisator::getRewardType (string reward_name)
Gets the correct reward type.
Parameters:
the name of the reward.
Definition at line 134 of file SP38Optimisator.cc.
References SP38::RT_LocalReward, SP38::RT_MixedReward, SP38::RT_PowerLocalReward, SP38_CVV_REWARD_LOCAL, SP38_CVV_REWARD_MIXED, and SP38_CVV_REWARD_POWER.
Referenced by SP38Optimisator().
void SP38::SP38Optimisator::setStepsPerEpoch (uint)
void SP38::SP38Optimisator::run ()
Runs the traffic simulation optimisation.
Definition at line 272 of file SP38Optimisator.cc.
References libpg::RLAlg::learn().
Referenced by main().