The PG Library: libpg::SoftmaxPolicy Class Reference
libpg::SoftmaxPolicy
libpg::SoftmaxPolicy Class Reference
#include <SoftmaxPolicy.hh>
Public Member Functions
SoftmaxPolicy (double constTemp=1.0)
SoftmaxPolicy (Temperature *tempFunc)
virtual ~SoftmaxPolicy ()
void getAction (Vector dist, Vector &action, Observation &obs)
Classes
class Temperature
Detailed Description
This is a subclass of Policy, implementing the Softmax action selection, with Gibbs (or Boltzmann) distribution.
Definition at line 10 of file SoftmaxPolicy.hh.
Constructor & Destructor Documentation
libpg::SoftmaxPolicy::SoftmaxPolicy (double constTemp = 1.0)
Definition at line 10 of file SoftmaxPolicy.cc.
libpg::SoftmaxPolicy::SoftmaxPolicy (Temperature * tempFunc)
Definition at line 16 of file SoftmaxPolicy.cc.
libpg::SoftmaxPolicy::~SoftmaxPolicy () [virtual]
Definition at line 20 of file SoftmaxPolicy.cc.
Member Function Documentation
void libpg::SoftmaxPolicy::getAction (Vector dist, Vector & action, Observation & obs) [virtual]
Sample an action according to Softmax, given distribution vector and observation.
Implements libpg::Policy.
Definition at line 25 of file SoftmaxPolicy.cc.
References libpg::Sampler::discrete(), libpg::Observation::getSteps(), libpg::SoftmaxPolicy::Temperature::getValue(), sumAndPlot::i, sumAndPlot::max, and sumAndPlot::min.