The PG Library: libpg::Approximator Class Reference
libpg::Approximator
libpg::Approximator Class Reference
#include <Approximator.hh>
Public Types
enum StatsEnum { PARAMS, GRADS, TRACES, DIST }
Public Member Functions
virtual ~Approximator ()
virtual int getNumParams ()=0
virtual void doApprox (Observation &obs, Vector &output)=0
virtual void feedbackGrad (Observation &obs, Vector &deltas)=0
virtual void discountTrace ()=0
virtual void setDiscount (double)=0
virtual void instantStep (double)=0
virtual void setStepSize (double)=0
virtual void resetTrace ()=0
virtual void resetParams ()=0
virtual void randomizeParams (double)
virtual double getMaxParam ()=0
virtual void write (std::ostream &)
virtual void read (std::istream &)
virtual int getInputDim ()=0
virtual int getOutputDim ()=0
virtual void batchStep ()
virtual void accumulateGrad (double, Observation &)
virtual void resetGrad ()
virtual void computeDirection (int)
virtual void reduce (Vector &, Approximator::StatsEnum)
virtual void scatter (Vector &, Approximator::StatsEnum)
Detailed Description
Underlying parameterised function approximator that approximated distributions, either discrete or continuous. Knows about, and performs, basic policy, or value, gradient operations.
Definition at line 16 of file Approximator.hh.
Member Enumeration Documentation
enum libpg::Approximator::StatsEnum
Allows operations that could be equally be performed on params or grads or traces to choose which.
Enumerator:
PARAMS
GRADS
TRACES
DIST
Definition at line 31 of file Approximator.hh.
Constructor & Destructor Documentation
virtual libpg::Approximator::~Approximator () [virtual]
Shut up compiler warning
Definition at line 24 of file Approximator.hh.
Member Function Documentation
virtual int libpg::Approximator::getNumParams () [pure virtual]
Constructor, do whatever you need to. Approximator() {};
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::getNumParams(), libpg::RegressionController::getNumParams(), libpg::CyclicPolicyBias::getNumParams(), libpg::BasicController::getNumParams(), and libpg::LSTDQController::LSTDQController().
virtual void libpg::Approximator::doApprox (Observation & obs, Vector & output) [pure virtual]
Main work horse, feed observations through to get the distribution of actions
Implemented in libpg::Bias, libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::FactoredApproximatorMinUpdates, libpg::LookupTable, libpg::MultidimensionalLookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::doApprox(), libpg::LSTDQController::doApprox(), libpg::CyclicPolicyBias::doApprox(), libpg::Bias::doApprox(), libpg::SARSAController::getAction(), libpg::RegressionController::getAction(), libpg::QLearningController::getAction(), libpg::LSTDQController::getAction(), libpg::BinaryController::getAction(), libpg::BasicController::getAction(), libpg::BinaryController::getMostProbAction(), and libpg::BasicController::getMostProbAction().
virtual void libpg::Approximator::feedbackGrad (Observation & obs, Vector & deltas) [pure virtual]
Feed back a gradient signal. Final gradient accumulated directly to trace object in policy.
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::MultidimensionalLookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::RegressionController::accumulateGrad(), libpg::RegressionController::computePartialsAndFeedback(), libpg::BasicController::computePartialsAndFeedback(), libpg::SARSAController::discountTrace(), libpg::QLearningController::discountTrace(), libpg::TransformApproximator::feedbackGrad(), libpg::CyclicPolicyBias::feedbackGrad(), libpg::LSTDQController::getAction(), libpg::BinaryController::getAction(), and libpg::RegressionController::instantStep().
virtual void libpg::Approximator::discountTrace () [pure virtual]
Just multiply trace by discount factors
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::FactoredApproximatorMinUpdates, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::discountTrace(), libpg::SARSAController::discountTrace(), libpg::QLearningController::discountTrace(), libpg::CyclicPolicyBias::discountTrace(), and libpg::BasicController::discountTrace().
virtual void libpg::Approximator::setDiscount (double) [pure virtual]
Set the discount factors. Does not necessarily have to be constant.
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::FactoredApproximatorMinUpdates, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::setDiscount(), libpg::SARSAController::setDiscount(), libpg::QLearningController::setDiscount(), libpg::LSTDQController::setDiscount(), libpg::CyclicPolicyBias::setDiscount(), and libpg::BasicController::setDiscount().
virtual void libpg::Approximator::instantStep (double) [pure virtual]
Calculate instant gradient and step the parameters
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::FactoredApproximatorMinUpdates, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::instantStep(), libpg::SARSAController::instantStep(), libpg::RegressionController::instantStep(), libpg::QLearningController::instantStep(), libpg::CyclicPolicyBias::instantStep(), and libpg::BasicController::instantStep().
virtual void libpg::Approximator::setStepSize (double) [pure virtual]
Set the step size. Does not necessarily have to be a constant.
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::setStepSize(), libpg::RegressionController::setStepSize(), libpg::CyclicPolicyBias::setStepSize(), and libpg::BasicController::setStepSize().
virtual void libpg::Approximator::resetTrace () [pure virtual]
Reset the eligibility trace to 0
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::FactoredApproximatorMinUpdates, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::QLearningController::discountTrace(), libpg::LSTDQController::getAction(), libpg::TransformApproximator::resetTrace(), libpg::RegressionController::resetTrace(), libpg::CyclicPolicyBias::resetTrace(), and libpg::BasicController::resetTrace().
virtual void libpg::Approximator::resetParams () [pure virtual]
Do whatever resetting the params means.
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::resetParams(), libpg::RegressionController::resetParams(), libpg::CyclicPolicyBias::resetParams(), and libpg::BasicController::resetParams().
virtual void libpg::Approximator::randomizeParams (double) [virtual]
Create a new random set of params.
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Definition at line 85 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::randomizeParams(), libpg::RegressionController::randomizeParams(), libpg::CyclicPolicyBias::randomizeParams(), and libpg::BasicController::randomizeParams().
virtual double libpg::Approximator::getMaxParam () [pure virtual]
Retrieve largest absolute parameter value.
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::getMaxParam(), libpg::RegressionController::getMaxParam(), libpg::CyclicPolicyBias::getMaxParam(), and libpg::BasicController::getMaxParam().
virtual void libpg::Approximator::write (std::ostream &) [virtual]
Read or write parameters
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, and libpg::TransformApproximator.
Definition at line 95 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::write().
virtual void libpg::Approximator::read (std::istream &) [virtual]
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, and libpg::TransformApproximator.
Definition at line 96 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::read().
virtual int libpg::Approximator::getInputDim () [pure virtual]
Query expected number of inputs
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::MultidimensionalLookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::TransformApproximator::getInputDim(), libpg::RegressionController::getInputDim(), libpg::CyclicPolicyBias::getInputDim(), and libpg::BasicController::getInputDim().
virtual int libpg::Approximator::getOutputDim () [pure virtual]
Query output dimension
Implemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::NeuralNet, libpg::Teacher, and libpg::TransformApproximator.
Referenced by libpg::BasicController::BasicController(), libpg::Bias::Bias(), libpg::BinaryController::BinaryController(), libpg::CyclicPolicyBias::CyclicPolicyBias(), libpg::TransformApproximator::getOutputDim(), libpg::CyclicPolicyBias::getOutputDim(), libpg::LSTDQController::LSTDQController(), libpg::QLearningController::QLearningController(), and libpg::SARSAController::SARSAController().
virtual void libpg::Approximator::batchStep () [virtual]
Additional methods that are only for batch gradient algs Assuming we have accumulated a gradient somewhere, step in that direction.
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTableBatch, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 119 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::batchStep(), libpg::RegressionController::batchStep(), libpg::CyclicPolicyBias::batchStep(), and libpg::BasicController::batchStep().
virtual void libpg::Approximator::accumulateGrad (double , Observation &) [virtual]
Calculate and accumulate instant gradient into a batch gradient estimate
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTableBatch, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 125 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::accumulateGrad(), libpg::RegressionController::accumulateGrad(), libpg::CyclicPolicyBias::accumulateGrad(), and libpg::BasicController::accumulateGrad().
virtual void libpg::Approximator::resetGrad () [virtual]
Reset the accumulated gradient only.
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTableBatch, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 130 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::resetGrad(), libpg::RegressionController::resetGrad(), libpg::CyclicPolicyBias::resetGrad(), and libpg::BasicController::resetGrad().
virtual void libpg::Approximator::computeDirection (int) [virtual]
Update the search direction for the parameters from the current gradient and possible past information. For GPOMDP and most codes this is empty. This could hold conjugation code Or it can extract natural actor critic search direction
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTableBatch, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 139 of file Approximator.hh.
References NYI.
Referenced by libpg::TransformApproximator::computeDirection(), libpg::RegressionController::computeDirection(), libpg::CyclicPolicyBias::computeDirection(), and libpg::BasicController::computeDirection().
virtual void libpg::Approximator::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::LookupTableBatch, libpg::NeuralNet, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 148 of file Approximator.hh.
References NYI.
Referenced by libpg::LSTDQController::getAction(), libpg::TransformApproximator::reduce(), libpg::RegressionController::reduce(), libpg::LSTDQController::reduce(), libpg::CyclicPolicyBias::reduce(), and libpg::BasicController::reduce().
virtual void libpg::Approximator::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented in libpg::CyclicPolicyBias, libpg::FactoredApproximator, libpg::LookupTable, libpg::LookupTableBatch, libpg::NeuralNet, libpg::NeuralNetBatch, and libpg::TransformApproximator.
Definition at line 158 of file Approximator.hh.
References NYI.
Referenced by libpg::LSTDQController::batchStep(), libpg::LSTDQController::delayedInstantStep(), libpg::TransformApproximator::scatter(), libpg::RegressionController::scatter(), libpg::LSTDQController::scatter(), libpg::CyclicPolicyBias::scatter(), and libpg::BasicController::scatter().