The PG Library: libpg::TransformApproximator Class Reference
libpg::TransformApproximator
libpg::TransformApproximator Class Reference
#include <TransformApproximator.hh>
Public Member Functions
TransformApproximator (Approximator *approx)
virtual ~TransformApproximator ()
virtual int getNumParams ()
virtual void doApprox (Observation &obs, Vector &output)
virtual void feedbackGrad (Observation &obs, Vector &deltas)
virtual void discountTrace ()
virtual void setDiscount (double)
virtual void instantStep (double)
virtual void setStepSize (double)
virtual void resetTrace ()
virtual void resetParams ()
virtual void randomizeParams (double)
virtual double getMaxParam ()
virtual void write (std::ostream &)
virtual void read (std::istream &)
virtual int getInputDim ()
virtual int getOutputDim ()
virtual void batchStep ()
virtual void accumulateGrad (double, Observation &)
virtual void resetGrad ()
virtual void computeDirection (int)
virtual void reduce (Vector &, Approximator::StatsEnum)
virtual void scatter (Vector &, Approximator::StatsEnum)
Protected Attributes
Approximator * approx
Detailed Description
Generic transformation of an approximator to permit screwing with the output values of approximators without having to reimplement every single method of an approximator. Knows about, and performs, basic policy, or value, gradient operations.
Definition at line 18 of file TransformApproximator.hh.
Constructor & Destructor Documentation
libpg::TransformApproximator::TransformApproximator (Approximator * approx)
Create a wrapper around an existing approximator only.
Parameters:
approx base approximator
Definition at line 13 of file TransformApproximator.cc.
virtual libpg::TransformApproximator::~TransformApproximator () [virtual]
Shut up compiler warning
Definition at line 36 of file TransformApproximator.hh.
Member Function Documentation
int libpg::TransformApproximator::getNumParams () [virtual]
Every single method here just calls its base equivalent.
Implements libpg::Approximator.
Definition at line 21 of file TransformApproximator.cc.
References approx, and libpg::Approximator::getNumParams().
void libpg::TransformApproximator::doApprox (Observation & obs, Vector & output) [virtual]
Main work horse, feed observations through to get the distribution of actions
Implements libpg::Approximator.
Reimplemented in libpg::Bias.
Definition at line 22 of file TransformApproximator.cc.
References approx, and libpg::Approximator::doApprox().
void libpg::TransformApproximator::feedbackGrad (Observation & obs, Vector & deltas) [virtual]
Feed back a gradient signal. Final gradient accumulated directly to trace object in policy.
Implements libpg::Approximator.
Definition at line 23 of file TransformApproximator.cc.
References approx, and libpg::Approximator::feedbackGrad().
void libpg::TransformApproximator::discountTrace () [virtual]
Just multiply trace by discount factors
Implements libpg::Approximator.
Definition at line 24 of file TransformApproximator.cc.
References approx, and libpg::Approximator::discountTrace().
void libpg::TransformApproximator::setDiscount (double) [virtual]
Set the discount factors. Does not necessarily have to be constant.
Implements libpg::Approximator.
Definition at line 25 of file TransformApproximator.cc.
References approx, and libpg::Approximator::setDiscount().
void libpg::TransformApproximator::instantStep (double) [virtual]
Calculate instant gradient and step the parameters
Implements libpg::Approximator.
Definition at line 26 of file TransformApproximator.cc.
References approx, and libpg::Approximator::instantStep().
void libpg::TransformApproximator::setStepSize (double) [virtual]
Set the step size. Does not necessarily have to be a constant.
Implements libpg::Approximator.
Definition at line 27 of file TransformApproximator.cc.
References approx, and libpg::Approximator::setStepSize().
void libpg::TransformApproximator::resetTrace () [virtual]
Reset the eligibility trace to 0
Implements libpg::Approximator.
Definition at line 28 of file TransformApproximator.cc.
References approx, and libpg::Approximator::resetTrace().
void libpg::TransformApproximator::resetParams () [virtual]
Do whatever resetting the params means.
Implements libpg::Approximator.
Definition at line 29 of file TransformApproximator.cc.
References approx, and libpg::Approximator::resetParams().
void libpg::TransformApproximator::randomizeParams (double) [virtual]
Create a new random set of params.
Reimplemented from libpg::Approximator.
Definition at line 30 of file TransformApproximator.cc.
References approx, and libpg::Approximator::randomizeParams().
double libpg::TransformApproximator::getMaxParam () [virtual]
Retrieve largest absolute parameter value.
Implements libpg::Approximator.
Definition at line 31 of file TransformApproximator.cc.
References approx, and libpg::Approximator::getMaxParam().
void libpg::TransformApproximator::write (std::ostream &) [virtual]
Read or write parameters
Reimplemented from libpg::Approximator.
Definition at line 32 of file TransformApproximator.cc.
References approx, and libpg::Approximator::write().
void libpg::TransformApproximator::read (std::istream & is) [virtual]
Reimplemented from libpg::Approximator.
Definition at line 33 of file TransformApproximator.cc.
References approx, and libpg::Approximator::read().
int libpg::TransformApproximator::getInputDim () [virtual]
Query expected number of inputs
Implements libpg::Approximator.
Definition at line 34 of file TransformApproximator.cc.
References approx, and libpg::Approximator::getInputDim().
int libpg::TransformApproximator::getOutputDim () [virtual]
Query output dimension
Implements libpg::Approximator.
Definition at line 35 of file TransformApproximator.cc.
References approx, and libpg::Approximator::getOutputDim().
void libpg::TransformApproximator::batchStep () [virtual]
Additional methods that are only for batch gradient algs Assuming we have accumulated a gradient somewhere, step in that direction.
Reimplemented from libpg::Approximator.
Definition at line 36 of file TransformApproximator.cc.
References approx, and libpg::Approximator::batchStep().
void libpg::TransformApproximator::accumulateGrad (double , Observation &) [virtual]
Calculate and accumulate instant gradient into a batch gradient estimate
Reimplemented from libpg::Approximator.
Definition at line 37 of file TransformApproximator.cc.
References libpg::Approximator::accumulateGrad(), and approx.
void libpg::TransformApproximator::resetGrad () [virtual]
Reset the accumulated gradient only.
Reimplemented from libpg::Approximator.
Definition at line 38 of file TransformApproximator.cc.
References approx, and libpg::Approximator::resetGrad().
void libpg::TransformApproximator::computeDirection (int) [virtual]
Update the search direction for the parameters from the current gradient and possible past information. For GPOMDP and most codes this is empty. This could hold conjugation code Or it can extract natural actor critic search direction
Reimplemented from libpg::Approximator.
Definition at line 39 of file TransformApproximator.cc.
References approx, and libpg::Approximator::computeDirection().
void libpg::TransformApproximator::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Approximator.
Definition at line 40 of file TransformApproximator.cc.
References approx, and libpg::Approximator::reduce().
void libpg::TransformApproximator::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Approximator.
Definition at line 41 of file TransformApproximator.cc.
References approx, and libpg::Approximator::scatter().
Member Data Documentation
Approximator* libpg::TransformApproximator::approx [protected]
Definition at line 22 of file TransformApproximator.hh.
Referenced by accumulateGrad(), batchStep(), computeDirection(), discountTrace(), doApprox(), libpg::Bias::doApprox(), feedbackGrad(), getInputDim(), getMaxParam(), getNumParams(), getOutputDim(), instantStep(), randomizeParams(), read(), reduce(), resetGrad(), resetParams(), resetTrace(), scatter(), setDiscount(), setStepSize(), and write().