The PG Library: libpg::Controller Class Reference
libpg::Controller
libpg::Controller Class Reference
#include <Controller.hh>
Public Member Functions
virtual ~Controller ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)=0
virtual void computePartialsAndFeedback (Observation &obs, int sampledAct, double weight=1.0)=0
virtual void getMostProbAction (Observation &, Vector &)
virtual int getInputDim ()=0
virtual int getNumParams ()=0
virtual void discountTrace ()=0
virtual void setDiscount (double)=0
virtual void accumulateGrad (Vector &, Observation &)
virtual void resetGrad ()
virtual void computeDirection (int)
virtual void instantStep (Vector &)
virtual void batchStep ()
virtual void setStepSize (double)=0
virtual void resetTrace ()=0
virtual void resetParams ()=0
virtual void randomizeParams (double)
virtual double getMaxParam ()=0
virtual void write (std::ostream &)
virtual void read (std::istream &)
virtual void reduce (Vector &, Approximator::StatsEnum)
virtual void scatter (Vector &, Approximator::StatsEnum)
Detailed Description
A controller is an agent that represents the parameterised stochastic action selector. Apart from choosing actions, it also stores parameters, computes gradients, and knows about the basic GPOMDP eligibility trace update maths and gradient step maths.
This is just the abstract version with necessary methods
Definition at line 15 of file Controller.hh.
Constructor & Destructor Documentation
virtual libpg::Controller::~Controller () [virtual]
Shut up compiler warning
Definition at line 22 of file Controller.hh.
Member Function Documentation
virtual void libpg::Controller::getAction (Observation & obs, Vector & action, bool computeGrad = true) [pure virtual]
Main work horse, feed observations through, sample an action. Optionally accumulate instant log action grad directly to trace
Implemented in libpg::BasicController, libpg::BinaryController, libpg::CatObsActionTransform, libpg::FactoredController, libpg::HMMTransform, libpg::ImportanceSamplingController, libpg::LSTDQController, libpg::NACTransform, libpg::ObsWindowTransform, libpg::PSRTransform, libpg::QLearningController, libpg::RegressionController, libpg::SARSAController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, libpg::TransformController, and libpg::ValueController.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), libpg::TransformController::getAction(), libpg::PSRTransform::getAction(), libpg::ObsWindowTransform::getAction(), libpg::NACTransform::getAction(), libpg::ImportanceSamplingController::getAction(), libpg::HMMTransform::getAction(), libpg::CatObsActionTransform::getAction(), libpg::ImportanceSamplingController::getMostProbAction(), and test().
virtual void libpg::Controller::computePartialsAndFeedback (Observation & obs, int sampledAct, double weight = 1.0) [pure virtual]
compute partial derivative of prob of action wrt a vector of likelihoods then feedback to the underlying parametersiation.
Implemented in libpg::BasicController, libpg::FactoredController, libpg::ImportanceSamplingController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, libpg::TransformController, and libpg::ValueController.
Referenced by libpg::TransformController::computePartialsAndFeedback(), and libpg::ImportanceSamplingController::getAction().
virtual void libpg::Controller::getMostProbAction (Observation & , Vector &) [virtual]
Instead of sampling an action, pick the one with the highest prob. Use to exploit policy after learning.
Reimplemented in libpg::BasicController, libpg::BinaryController, libpg::FactoredController, libpg::ImportanceSamplingController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, libpg::OLBFGS, libpg::TransformController, and libpg::ValueController.
Definition at line 41 of file Controller.hh.
References NYI.
Referenced by libpg::RLAlg::evaluate(), libpg::TransformController::getMostProbAction(), and libpg::ImportanceSamplingController::getMostProbAction().
virtual int libpg::Controller::getInputDim () [pure virtual]
Find out what the input dimension of this controller is
Implemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Referenced by libpg::TransformController::getInputDim(), libpg::HMMTransform::HMMTransform(), libpg::NACTransform::NACTransform(), and libpg::PSRTransform::PSRTransform().
virtual int libpg::Controller::getNumParams () [pure virtual]
How many parameters does it have
Implemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Referenced by libpg::NACTransform::batchStep(), libpg::NACTransform::getAction(), libpg::TransformController::getNumParams(), libpg::HardLimitTransform::HardLimitTransform(), libpg::LineSearchAlg::lineSearchInit(), libpg::NACTransform::NACTransform(), libpg::OLBFGS::OLBFGS(), libpg::RegularizeTransform::RegularizeTransform(), and libpg::NACTransform::updateStatistics().
virtual void libpg::Controller::discountTrace () [pure virtual]
Remaining methods just pass through to equivalent in Approximator
Implemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::NACTransform, libpg::QLearningController, libpg::RegressionController, libpg::SARSAController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Referenced by libpg::TransformController::discountTrace(), libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), and libpg::ImportanceSamplingController::getAction().
virtual void libpg::Controller::setDiscount (double) [pure virtual]
Implemented in libpg::BasicController, libpg::FactoredController, libpg::ImportanceSamplingController, libpg::LSTDQController, libpg::NACTransform, libpg::QLearningController, libpg::RegressionController, libpg::SARSAController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Referenced by libpg::ImportanceSamplingController::getAction(), libpg::RLAlg::RLAlg(), libpg::TransformController::setDiscount(), libpg::NACTransform::setDiscount(), and libpg::ImportanceSamplingController::setDiscount().
virtual void libpg::Controller::accumulateGrad (Vector & , Observation &) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 62 of file Controller.hh.
References NYI.
Referenced by libpg::TransformController::accumulateGrad(), and libpg::GPomdp::doSteps().
virtual void libpg::Controller::resetGrad () [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Definition at line 63 of file Controller.hh.
References NYI.
Referenced by libpg::GPomdp::doSteps(), and libpg::TransformController::resetGrad().
virtual void libpg::Controller::computeDirection (int) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 64 of file Controller.hh.
References NYI.
Referenced by libpg::TransformController::computeDirection(), libpg::LineSearchAlg::incrementLineSearch(), libpg::LineSearchAlg::learnCore(), and libpg::GPomdp::learnCore().
virtual void libpg::Controller::instantStep (Vector &) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::HardLimitTransform, libpg::ImportanceSamplingController, libpg::LSTDQController, libpg::NACTransform, libpg::QLearningController, libpg::RegressionController, libpg::RegularizeTransform, libpg::SARSAController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Definition at line 65 of file Controller.hh.
References NYI.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GOALPomdp::doSteps(), libpg::TransformController::instantStep(), libpg::RegularizeTransform::instantStep(), libpg::ImportanceSamplingController::instantStep(), and libpg::HardLimitTransform::instantStep().
virtual void libpg::Controller::batchStep () [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::HardLimitTransform, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, libpg::RegularizeTransform, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 66 of file Controller.hh.
References NYI.
Referenced by libpg::TransformController::batchStep(), libpg::RegularizeTransform::batchStep(), libpg::NACTransform::batchStep(), libpg::HardLimitTransform::batchStep(), and libpg::GPomdp::learnCore().
virtual void libpg::Controller::setStepSize (double) [pure virtual]
Implemented in libpg::BasicController, libpg::FactoredController, libpg::PSRTransform, libpg::RegressionController, libpg::RegularizeTransform, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Referenced by libpg::RLAlg::checkStepSize(), libpg::RLAlg::RLAlg(), libpg::TransformController::setStepSize(), libpg::RegularizeTransform::setStepSize(), and libpg::PSRTransform::setStepSize().
virtual void libpg::Controller::resetTrace () [pure virtual]
Implemented in libpg::BasicController, libpg::FactoredController, libpg::ImportanceSamplingController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, libpg::OLBFGS, and libpg::TransformController.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::GOALPomdp::doSteps(), libpg::NACTransform::getAction(), libpg::LineSearchAlg::incrementLineSearch(), libpg::RLAlg::learn(), libpg::RLAlg::resetLearning(), libpg::TransformController::resetTrace(), and libpg::ImportanceSamplingController::resetTrace().
virtual void libpg::Controller::resetParams () [pure virtual]
Implemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Referenced by libpg::RLAlg::resetLearning(), and libpg::TransformController::resetParams().
virtual void libpg::Controller::randomizeParams (double) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, and libpg::TransformController.
Definition at line 71 of file Controller.hh.
References NYI.
Referenced by main(), and libpg::TransformController::randomizeParams().
virtual double libpg::Controller::getMaxParam () [pure virtual]
Implemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Referenced by libpg::RLAlg::evaluateAndPrint(), libpg::PSRTransform::getAction(), libpg::TransformController::getMaxParam(), libpg::RLAlg::learn(), and libpg::LineSearchAlg::learnCore().
virtual void libpg::Controller::write (std::ostream &) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 73 of file Controller.hh.
References NYI.
Referenced by libpg::RLAlg::write().
virtual void libpg::Controller::read (std::istream &) [virtual]
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 74 of file Controller.hh.
References NYI.
Referenced by main(), and libpg::RLAlg::read().
virtual void libpg::Controller::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 83 of file Controller.hh.
References NYI.
Referenced by libpg::RegularizeTransform::batchStep(), libpg::HardLimitTransform::checkParams(), libpg::NACTransform::getAction(), libpg::ImportanceSamplingController::getAction(), libpg::ImportanceSamplingController::getMostProbAction(), libpg::LineSearchAlg::incrementLineSearch(), libpg::RegularizeTransform::instantStep(), libpg::LineSearchAlg::lineSearch(), libpg::RegularizeTransform::penalise(), libpg::TransformController::reduce(), libpg::NACTransform::reduce(), and libpg::NACTransform::updateStatistics().
virtual void libpg::Controller::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented in libpg::BasicController, libpg::FactoredController, libpg::LSTDQController, libpg::NACTransform, libpg::RegressionController, SP38::FixedController, SP38::SimpleDynamicController, and libpg::TransformController.
Definition at line 93 of file Controller.hh.
References NYI.
Referenced by libpg::NACTransform::batchStep(), libpg::HardLimitTransform::checkParams(), libpg::LineSearchAlg::incrementLineSearch(), libpg::LineSearchAlg::lineSearch(), libpg::RegularizeTransform::penalise(), libpg::TransformController::scatter(), and libpg::NACTransform::scatter().