The PG Library: libpg::Simulator Class Reference
libpg::Simulator
libpg::Simulator Class Reference
#include <Simulator.hh>
Public Member Functions
virtual ~Simulator ()
virtual int getMaxEpisodeLength ()
virtual int getObsRows ()=0
virtual int getObsCols ()=0
virtual int getAgents ()=0
virtual int getActionDim ()=0
virtual int getNumActions ()=0
virtual int getRewardDim ()=0
virtual void getReward (Vector &rewards)=0
virtual void getObservation (Observation &obs)=0
virtual int doAction (Vector &action)=0
Detailed Description
Container for any RL problem we care to define. We simply have to define the dimensionality of actions, a reward function, a way to get observationsk, and a way to do actions.
Definition at line 12 of file Simulator.hh.
Constructor & Destructor Documentation
virtual libpg::Simulator::~Simulator () [virtual]
Shut up compiler warning
Definition at line 19 of file Simulator.hh.
Member Function Documentation
virtual int libpg::Simulator::getMaxEpisodeLength () [virtual]
Maximum episode length in steps. For planning mode. Only used by GOALPomdp at the moment.
Reimplemented in Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Definition at line 25 of file Simulator.hh.
virtual int libpg::Simulator::getObsRows () [pure virtual]
Get the number of rows in observation matrix. Generally the length of the observation vector.
Implemented in BeliefStateCassandra, Cassandra, PSRCassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::RLAlg::evaluate(), and libpg::RLAlg::RLAlg().
virtual int libpg::Simulator::getObsCols () [pure virtual]
Get the number of columns in the observation matrix Typically use multiple columns to provide a different observation to each agent, so the number of columns is the same as getAgents()
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::RLAlg::evaluate(), and libpg::RLAlg::RLAlg().
virtual int libpg::Simulator::getAgents () [pure virtual]
Get the total number of agents. Usually 1.
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::RLAlg::evaluate(), and libpg::RLAlg::RLAlg().
virtual int libpg::Simulator::getActionDim () [pure virtual]
Get the total action dimensionality. Often, but not necessarily, the same as the number of agents.
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), and libpg::RLAlg::evaluate().
virtual int libpg::Simulator::getNumActions () [pure virtual]
Get the number of actions per dimension. Used to initialise the eligible vector in the Observation to the right size
Implemented in Cassandra, FunctionSim, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::RLAlg::evaluate(), and libpg::RLAlg::RLAlg().
virtual int libpg::Simulator::getRewardDim () [pure virtual]
Get the dimensionality of the reward vector. Often, but not necessarily, the same as the number of agents.
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), libpg::RLAlg::evaluate(), libpg::RLAlg::evaluateAndPrint(), libpg::RLAlg::learn(), libpg::RLAlg::learnCore(), libpg::LineSearchAlg::learnCore(), libpg::GPomdp::learnCore(), and libpg::RLAlg::RLAlg().
virtual void libpg::Simulator::getReward (Vector & rewards) [pure virtual]
Just return the reward associated with the most recent state achieved.
Parameters:
vector of rewards. The vector has getAgents() dimensionality In non-local reward mode this vector will just be averaged.
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), and libpg::RLAlg::evaluate().
virtual void libpg::Simulator::getObservation (Observation & obs) [pure virtual]
Return the observation of the current state. Could be a scalar, vector, or matrix, so we left the type as Matrix
Returns:
possibly stochastic observation of the current state
Implemented in BeliefStateCassandra, BlindCassandra, Cassandra, PSRCassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), and libpg::RLAlg::evaluate().
virtual int libpg::Simulator::doAction (Vector & action) [pure virtual]
Do action issued by a controller
Returns:
vector of actions, typically just a scalar which is cast to an int, but it there are multiple agents it will be a vector of actions for each agent.
Parameters:
vector that describes the action to perform.
Implemented in Cassandra, GridSim, FunctionSim, Sequence, SP38::SP38PGSimulator, ThreeState, MySimulator, and ThreeState.
Referenced by libpg::GOALPomdp::doSingleEpisode(), libpg::OLPomdp::doSteps(), libpg::GPomdp::doSteps(), libpg::GOALPomdp::doSteps(), and libpg::RLAlg::evaluate().