The PG Library: libpg::OLPomdp Class Reference
libpg::OLPomdp
libpg::OLPomdp Class Reference
#include <OLPomdp.hh>
Public Member Functions
OLPomdp ()
OLPomdp (Controller *controller, Simulator *simulator, double discount, double stepSize)
virtual double doSteps (Vector &totalReward, int steps, bool learn)
Detailed Description
Definition at line 6 of file OLPomdp.hh.
Constructor & Destructor Documentation
libpg::OLPomdp::OLPomdp ()
Don't call this one. Tears will result.
Definition at line 14 of file OLPomdp.hh.
libpg::OLPomdp::OLPomdp (Controller * controller, Simulator * simulator, double discount, double stepSize)
Top level piece of glue for Policy gradient, link the controller and the simulator
Parameters:
Controller
Simulator (problem specific)
discount factor [0, 1]. If 1, trace must be reset occasionally or have 0 mean reward.
Definition at line 19 of file OLPomdp.cc.
Member Function Documentation
double libpg::OLPomdp::doSteps (Vector & totalRewards, int steps, bool learn) [virtual]
Do a fixed number of individual steps, aggregating the reward. No output is done. Could also be termed an "epoch"
Parameters:
number ofsteps to iterate for
should learning be turned on, or are we just exploiting/evaluating the current policy?
Implements libpg::RLAlg.
Reimplemented in libpg::GOALPomdp.
Definition at line 29 of file OLPomdp.cc.
References libpg::RLAlg::baseline, libpg::RLAlg::controller, libpg::Controller::discountTrace(), libpg::Simulator::doAction(), libpg::Controller::getAction(), libpg::Simulator::getActionDim(), libpg::Simulator::getObservation(), libpg::Simulator::getReward(), libpg::Simulator::getRewardDim(), libpg::Observation::getSteps(), libpg::Controller::instantStep(), libpg::RLAlg::obs, sumAndPlot::s, libpg::Observation::setSteps(), and libpg::RLAlg::simulator.