The PG Library: SP38::ScatsObject Class Reference
SP38::ScatsObject
SP38::ScatsObject Class Reference
#include <ScatsObject.hh>
Public Member Functions
ScatsObject (int s)
int getScatsId ()
Detailed Description
A Scats Object.
Definition at line 9 of file ScatsObject.hh.
Constructor & Destructor Documentation
SP38::ScatsObject::ScatsObject (int s)
Definition at line 12 of file ScatsObject.hh.
Member Function Documentation
int SP38::ScatsObject::getScatsId ()
Definition at line 13 of file ScatsObject.hh.
Referenced by SP38::Phase::addDetector(), SP38::Phase::addSignalGroup(), and SP38::SP38Simulation::setNewPhase().