The PG Library: libpg::RegressionController Class Reference
libpg::RegressionController
libpg::RegressionController Class Reference
#include <RegressionController.hh>
Public Member Functions
RegressionController (Approximator *approx)
virtual ~RegressionController ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void computePartialsAndFeedback (Observation &obs, int sampledAct, double weight=1.0)
virtual void setLastReward (Vector &lastRewards)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual int getInputDim ()
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void accumulateGrad (Vector &rewards, Observation &newObs)
virtual void resetGrad ()
virtual void instantStep (Vector &rewards)
virtual void computeDirection (int steps)
virtual void batchStep ()
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetParams ()
virtual void randomizeParams (double maxRand)
virtual double getMaxParam ()
virtual int getNumParams ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
virtual void reduce (Vector &v, Approximator::StatsEnum s)
Protected Attributes
Approximator * approx
Observation lastObs
Vector lastRewards
Detailed Description
Instead of doing RL, it assumes the reward is the derivative of a loss function for the previous observation (input) and action (approximator output) pair. Eligibility trace is cleared at every step. Loss function derivative is computed in the Simulator::getReward() function. Can be used in online or batch style
Definition at line 13 of file RegressionController.hh.
Constructor & Destructor Documentation
libpg::RegressionController::RegressionController (Approximator * approx)
Parameters:
approximators vector of Approximator*
if true, expect as many colums in the observations as there are approximators and each controller only gets its col as an observation. If false, all approximators get the same observation.
Definition at line 15 of file RegressionController.cc.
virtual libpg::RegressionController::~RegressionController () [virtual]
Definition at line 24 of file RegressionController.hh.
Member Function Documentation
void libpg::RegressionController::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Where the real coding is done to implement
Here we just compute the function approximator output
Implements libpg::Controller.
Definition at line 26 of file RegressionController.cc.
References approx, libpg::Approximator::doApprox(), and lastObs.
Referenced by getMostProbAction().
void libpg::RegressionController::computePartialsAndFeedback (Observation & obs, int sampledAct, double weight = 1.0) [virtual]
This is a bit odd in the context of regression. The action isn't really how we compute partials, it's the reward (which is treated directly as vector of partials). So what it does is computes the partial on the basis of the last reward that was specified via
Implements libpg::Controller.
Definition at line 51 of file RegressionController.cc.
References approx, libpg::Approximator::feedbackGrad(), lastRewards, and resetTrace().
void libpg::RegressionController::setLastReward (Vector & lastRewards) [virtual]
This is a bit of a hack to allow us to call computePartialsAndFeedback() with a regression controller. Since it's not in the spec for a Controller, you have to cast Controllers to RegressionControllers in order to use it. I should think of a neater way to do this (probably changing int sampledAct to a vector.
Definition at line 41 of file RegressionController.cc.
void libpg::RegressionController::getMostProbAction (Observation & obs, Vector & action) [virtual]
Pick the controller that has the highest probability of being chosen.
Parameters:
observation vector
empty vector length 1 to put the action in.
Reimplemented from libpg::Controller.
Definition at line 64 of file RegressionController.cc.
References getAction().
int libpg::RegressionController::getInputDim () [virtual]
Find out what the input dimension of this controller is
Implements libpg::Controller.
Definition at line 71 of file RegressionController.cc.
References approx, and libpg::Approximator::getInputDim().
void libpg::RegressionController::discountTrace () [virtual]
The remaining methods just pass onto equiv Approximator functions. We have to do it in this ugly way because more advanced multiple agent approximators will need to override these functions to update all agents in turn.
Implements libpg::Controller.
Definition at line 85 of file RegressionController.cc.
void libpg::RegressionController::setDiscount (double discount) [virtual]
Implements libpg::Controller.
Definition at line 89 of file RegressionController.cc.
void libpg::RegressionController::accumulateGrad (Vector & rewards, Observation & newObs) [virtual]
Reimplemented from libpg::Controller.
Definition at line 93 of file RegressionController.cc.
References libpg::Approximator::accumulateGrad(), approx, libpg::Approximator::feedbackGrad(), lastObs, and resetTrace().
void libpg::RegressionController::resetGrad () [virtual]
Reimplemented from libpg::Controller.
Definition at line 101 of file RegressionController.cc.
References approx, and libpg::Approximator::resetGrad().
void libpg::RegressionController::instantStep (Vector & rewards) [virtual]
Reimplemented from libpg::Controller.
Definition at line 106 of file RegressionController.cc.
References approx, libpg::Approximator::feedbackGrad(), libpg::Approximator::instantStep(), lastObs, and resetTrace().
void libpg::RegressionController::computeDirection (int steps) [virtual]
Reimplemented from libpg::Controller.
Definition at line 113 of file RegressionController.cc.
References approx, and libpg::Approximator::computeDirection().
void libpg::RegressionController::batchStep () [virtual]
Reimplemented from libpg::Controller.
Definition at line 118 of file RegressionController.cc.
References approx, and libpg::Approximator::batchStep().
void libpg::RegressionController::setStepSize (double stepSize) [virtual]
Implements libpg::Controller.
Definition at line 122 of file RegressionController.cc.
References approx, and libpg::Approximator::setStepSize().
void libpg::RegressionController::resetTrace () [virtual]
Implements libpg::Controller.
Definition at line 127 of file RegressionController.cc.
References approx, and libpg::Approximator::resetTrace().
Referenced by accumulateGrad(), computePartialsAndFeedback(), and instantStep().
void libpg::RegressionController::resetParams () [virtual]
Implements libpg::Controller.
Definition at line 132 of file RegressionController.cc.
References approx, and libpg::Approximator::resetParams().
void libpg::RegressionController::randomizeParams (double maxRand) [virtual]
Reimplemented from libpg::Controller.
Definition at line 137 of file RegressionController.cc.
References approx, and libpg::Approximator::randomizeParams().
double libpg::RegressionController::getMaxParam () [virtual]
Implements libpg::Controller.
Definition at line 142 of file RegressionController.cc.
References approx, and libpg::Approximator::getMaxParam().
int libpg::RegressionController::getNumParams () [virtual]
How many parameters does it have
Implements libpg::Controller.
Definition at line 147 of file RegressionController.cc.
References approx, and libpg::Approximator::getNumParams().
virtual void libpg::RegressionController::write (std::ostream & o) [virtual]
Reimplemented from libpg::Controller.
virtual void libpg::RegressionController::read (std::istream & o) [virtual]
Reimplemented from libpg::Controller.
void libpg::RegressionController::scatter (Vector & v, Approximator::StatsEnum s) [virtual]
Parameters:
s what to set, can't do GRADS here.
Reimplemented from libpg::Controller.
Definition at line 164 of file RegressionController.cc.
References approx, and libpg::Approximator::scatter().
void libpg::RegressionController::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Controller.
Definition at line 168 of file RegressionController.cc.
References approx, and libpg::Approximator::reduce().
Member Data Documentation
Approximator* libpg::RegressionController::approx [protected]
Definition at line 17 of file RegressionController.hh.
Referenced by accumulateGrad(), batchStep(), computeDirection(), computePartialsAndFeedback(), getAction(), getInputDim(), getMaxParam(), getNumParams(), instantStep(), randomizeParams(), reduce(), resetGrad(), resetParams(), resetTrace(), scatter(), and setStepSize().
Observation libpg::RegressionController::lastObs [protected]
Definition at line 18 of file RegressionController.hh.
Referenced by accumulateGrad(), getAction(), and instantStep().
Vector libpg::RegressionController::lastRewards [protected]
Definition at line 19 of file RegressionController.hh.
Referenced by computePartialsAndFeedback().