The PG Library: MySimulator Class Reference
MySimulator Class Reference
#include <MySimulator.hh>
Public Member Functions
MySimulator ()
virtual ~MySimulator ()
double getDiscountFactor ()
virtual void getReward (libpg::Vector &rewards)
virtual void getObservation (libpg::Observation &obs)
virtual int doAction (libpg::Vector &action)
virtual int getMaxEpisodeLength ()
virtual int getObsRows ()
virtual int getObsCols ()
virtual int getAgents ()
virtual int getActionDim ()
virtual int getNumActions ()
virtual int getRewardDim ()
Detailed Description
Definition at line 17 of file MySimulator.hh.
Constructor & Destructor Documentation
MySimulator::MySimulator ()
Constructor for your simulator. Do any once off initialisation. Read data files, allocate memory, stuff like that. Can be left empty if need be.
Definition at line 27 of file MySimulator.cc.
virtual MySimulator::~MySimulator () [virtual]
Definition at line 36 of file MySimulator.hh.
Member Function Documentation
double MySimulator::getDiscountFactor ()
The discount factor for this problem. If you don't know what a discount factor is then read Barto and Sutton "Reinforcement Learning: An introduction", 1998. Note this is not part of the standard simulator interface, but many RL people expect the discount factor to be defined as part of the problem. For infinite horizon settings (assumed by TemplateRLApp) this needs to be between [0,1). Do not choose 1.0!
Definition at line 188 of file MySimulator.cc.
Referenced by createRLAlg().
void MySimulator::getReward (libpg::Vector & rewards) [virtual]
Return the reward for the current state, or previous-state and action combination. In the multi-agent case there is one reward per reward. Here we assume a single agent, so only a single scalar reward. It's often easier to compute the reward during doAction() and save it a class variable to return here.
Parameters:
rewards vector to put the rewards in.
Implements libpg::Simulator.
Definition at line 42 of file MySimulator.cc.
void MySimulator::getObservation (libpg::Observation & obs) [virtual]
Fill in a description of the current state. Think of the observation for a single agent as being a single column matrix of dimension getObsRows()*1.
An observation is sometimes refered to as a basis feature.
It's up to you to define below in getObsRows() how big the observation is. Making it really big can degrade performance because more parameters are required. Choose your observation features carefully.
One tip is to try and normalise each element of your observation to be between -1 and 1. Another tip is to make sure at least one element of the observation is a constant 1.0 to provide bias to the neural network approximator (don't worry if you don't know what this means, just do it.)
In an MDP setting there would typically be only one element in the observation, the state-ID. This is not appropriate for TemplateRLApp. Use a state basis feature instead. If you want to use state-IDs for observations, edit TemplateRLApp.cc to use TableLookup controllers instead of NeuralNet controllers.
Parameters:
obs The observation class to fill in and return
Implements libpg::Simulator.
Definition at line 86 of file MySimulator.cc.
References libpg::Observation::getFeatures(), and getObsRows().
int MySimulator::doAction (libpg::Vector & action) [virtual]
Do the action passed in. Again, in the single agent case the action vector will always be 1x1, and contain an integer valued action. You should take this action and update the state of the simulator accordingly. You can add state variables in MySimulator.hh IMPORTANT: For this template I assume an infinite-horizon process. This means the simulation does not terminate. If your problem is finite-horizon (it has terminal state or goals), then it's your job to reset the state to the initial state when you encounter a terminal state here. By editing TemplateRLApp.cc you can choose GoalPOMDP as the top level algorithm appropriate for episodic cases.
Parameters:
action The 1x1 vector containing the action to do.
Returns:
1 for goal state (ignored in TemplateRLApp).
Implements libpg::Simulator.
Definition at line 126 of file MySimulator.cc.
int MySimulator::getMaxEpisodeLength () [virtual]
Maximum episode length in steps. For planning mode. Only used by GOALPomdp at the moment. Do not change.
Reimplemented from libpg::Simulator.
Definition at line 232 of file MySimulator.cc.
int MySimulator::getObsRows () [virtual]
This defines how many elements there are in your observation vector. This can be as big as you want. Minimum 1 element.
If you in an MDP setting, you can just say getObsRows=1 and you put the state-id in that element. But see warning above.... you need to edit TempateRLApp.cc to do this properly.
Implements libpg::Simulator.
Definition at line 152 of file MySimulator.cc.
Referenced by createRLAlg(), and getObservation().
int MySimulator::getObsCols () [virtual]
Get the number of columns in the observation matrix Typically use multiple columns to provide a different observation to each agent, so the number of columns is the same as getAgents()
Implements libpg::Simulator.
Definition at line 242 of file MySimulator.cc.
References getAgents().
int MySimulator::getAgents () [virtual]
Get the total number of agents. Hard wired to 1 here.
Implements libpg::Simulator.
Definition at line 222 of file MySimulator.cc.
Referenced by getActionDim(), and getObsCols().
int MySimulator::getActionDim () [virtual]
Get the total action dimensionality. Often, but not necessarily, the same as the number of agents.
Implements libpg::Simulator.
Definition at line 251 of file MySimulator.cc.
References getAgents().
int MySimulator::getNumActions () [virtual]
Return the number of actions the simulator knows about. The controller will only produce actionID's between 0 and getNumActions()-1
Implements libpg::Simulator.
Definition at line 168 of file MySimulator.cc.
Referenced by createRLAlg().
int MySimulator::getRewardDim () [virtual]
Get the dimensionality of the reward. Hard wired to 1 for single agent case. Only different if multi-agents and each agent generates its own local reward.
Implements libpg::Simulator.
Definition at line 214 of file MySimulator.cc.