The PG Library: libpg::GOALPomdp Class Reference
libpg::GOALPomdp
libpg::GOALPomdp Class Reference
#include <GOALPomdp.hh>
Public Member Functions
virtual ~GOALPomdp ()
GOALPomdp (Controller *controller, Simulator *simulator, double discount, double stepSize)
virtual double doSteps (Vector &totalRewards, int steps, bool learn)
double doSingleEpisode (Vector &totalRewards, bool learn)
virtual void printPerformanceInfo (bool printTitles, int steps, double avgReward, double maxParam, int seconds)
Public Attributes
int episodeSteps
Protected Member Functions
GOALPomdp ()
Protected Attributes
int episodes
int successes
int totalEpisodes
Detailed Description
Definition at line 6 of file GOALPomdp.hh.
Constructor & Destructor Documentation
libpg::GOALPomdp::GOALPomdp () [protected]
Don't call this one. Tears will result.
Definition at line 19 of file GOALPomdp.hh.
virtual libpg::GOALPomdp::~GOALPomdp () [virtual]
Shut up compiler warning
Definition at line 26 of file GOALPomdp.hh.
libpg::GOALPomdp::GOALPomdp (Controller * controller, Simulator * simulator, double discount, double stepSize)
Top level piece of glue for Policy gradient, link the controller and the simulator
Parameters:
Controller
Simulator (problem specific)
discount factor [0, 1]. If 1, trace must be reset occasionally or have 0 mean reward.
Definition at line 27 of file GOALPomdp.cc.
References episodeSteps, and totalEpisodes.
Member Function Documentation
double libpg::GOALPomdp::doSteps (Vector & totalRewards, int steps, bool learn) [virtual]
Do a fixed number of individual steps, aggregating the reward. No output is done. Could also be termed an "epoch"
Parameters:
empty vector to accumulate average reward for each reward dimension
number ofsteps to iterate for
should learning be turned on, or are we just exploiting/evaluating the current policy?
Reimplemented from libpg::OLPomdp.
Definition at line 42 of file GOALPomdp.cc.
References libpg::RLAlg::baseline, libpg::RLAlg::controller, libpg::Controller::discountTrace(), libpg::Simulator::doAction(), episodes, episodeSteps, libpg::Controller::getAction(), libpg::Simulator::getActionDim(), libpg::Simulator::getObservation(), libpg::Simulator::getReward(), libpg::Simulator::getRewardDim(), libpg::Observation::getSteps(), libpg::Controller::instantStep(), libpg::RLAlg::obs, libpg::Controller::resetTrace(), sumAndPlot::s, libpg::Observation::setSteps(), libpg::RLAlg::simulator, successes, and totalEpisodes.
double libpg::GOALPomdp::doSingleEpisode (Vector & totalRewards, bool learn)
Do as many steps as required to get to the goal for the first time. Assumes simulator has been reset. EpisodeSteps will be reset to 0.
Parameters:
empty vector to accumulate average reward for each reward dimension
should learning be turned on, or are we just exploiting/evaluating the current policy?
Returns:
average reward. Can also query class for episodeSteps
Definition at line 98 of file GOALPomdp.cc.
References libpg::RLAlg::baseline, libpg::RLAlg::controller, libpg::Controller::discountTrace(), libpg::Simulator::doAction(), episodes, episodeSteps, libpg::Controller::getAction(), libpg::Simulator::getActionDim(), libpg::Simulator::getObservation(), libpg::Simulator::getReward(), libpg::Simulator::getRewardDim(), libpg::Observation::getSteps(), libpg::Controller::instantStep(), libpg::RLAlg::obs, libpg::Controller::resetTrace(), libpg::Observation::setSteps(), libpg::RLAlg::simulator, and successes.
void libpg::GOALPomdp::printPerformanceInfo (bool printTitles, int steps, double avgReward, double maxParam, int seconds) [virtual]
Print a line of performance information
Parameters:
are we only printing the headers?
total number of steps so far
average reward over last epoch
maximum parameter
time elapsed so far. This overloaded method from RLAlg additionally prints prob(success)
Reimplemented from libpg::RLAlg.
Definition at line 154 of file GOALPomdp.cc.
References CWIDTH, episodes, PRECISION, successes, and totalEpisodes.
Member Data Documentation
int libpg::GOALPomdp::episodes [protected]
Definition at line 11 of file GOALPomdp.hh.
Referenced by doSingleEpisode(), doSteps(), and printPerformanceInfo().
int libpg::GOALPomdp::successes [protected]
Definition at line 12 of file GOALPomdp.hh.
Referenced by doSingleEpisode(), doSteps(), and printPerformanceInfo().
int libpg::GOALPomdp::totalEpisodes [protected]
Definition at line 14 of file GOALPomdp.hh.
Referenced by doSteps(), GOALPomdp(), and printPerformanceInfo().
int libpg::GOALPomdp::episodeSteps
Definition at line 26 of file GOALPomdp.hh.
Referenced by doSingleEpisode(), doSteps(), and GOALPomdp().