The PG Library: SP38::IntersectionHistory Class Reference
SP38::IntersectionHistory
SP38::IntersectionHistory Class Reference
#include <IntersectionHistory.hh>
Public Member Functions
IntersectionHistory (Intersection *, int *, int, int)
Intersection * getIntersection ()
DetectorHistory * getDetectorHistory (Detector *)
PhaseHistory * getPhaseHistory (Phase *)
void setInitialState ()
void addPhaseHistory (PhaseHistory *)
void addDetectorHistory (DetectorHistory *)
Phase * getCurrentPhase ()
Phase * getPhase (int)
double getPhaseMaxDetectorThroughputBetween (Phase *, int, int)
double getPhaseThroughputBetween (Phase *, int, int)
double getMaxThroughput ()
int getCurrentPhaseDuration ()
Detailed Description
History about an intersection.
Definition at line 16 of file IntersectionHistory.hh.
Constructor & Destructor Documentation
SP38::IntersectionHistory::IntersectionHistory (Intersection * i, int * ct, int max, int m_a_i)
IntersectionHistory constructor.
Parameters:
The intersection to keep history.
Pointer to current time.
Max difference to current time to keep history.
Size of interval time to estimate maximum detector activations.
Definition at line 12 of file IntersectionHistory.cc.
References addDetectorHistory(), addPhaseHistory(), SP38::Intersection::detectors, and SP38::Intersection::phases.
Member Function Documentation
Intersection * SP38::IntersectionHistory::getIntersection ()
Gets the intersection.
Definition at line 37 of file IntersectionHistory.cc.
DetectorHistory * SP38::IntersectionHistory::getDetectorHistory (Detector * d)
Gets the DetectorHistory for a detector.
Parameters:
the detector
Definition at line 155 of file IntersectionHistory.cc.
Referenced by SP38::SP38Simulation::getDetectorCountBetween(), SP38::SP38Simulation::getDetectorMaxThroughput(), getPhaseMaxDetectorThroughputBetween(), getPhaseThroughputBetween(), and SP38::SP38Simulation::isDetectorActive().
PhaseHistory * SP38::IntersectionHistory::getPhaseHistory (Phase * pe)
Gets the PhaseHistory for a phase.
Parameters:
the phase
Definition at line 166 of file IntersectionHistory.cc.
Referenced by getCurrentPhaseDuration(), SP38::SP38Simulation::getPhaseDurationBetween(), getPhaseMaxDetectorThroughputBetween(), getPhaseThroughputBetween(), and SP38::SP38Simulation::setNewPhase().
void SP38::IntersectionHistory::setInitialState ()
Sets the intersection history as a valid initial state for a simulation.
Definition at line 26 of file IntersectionHistory.cc.
void SP38::IntersectionHistory::addPhaseHistory (PhaseHistory * ph)
Adds a PhaseHistory to the set.
Definition at line 146 of file IntersectionHistory.cc.
Referenced by IntersectionHistory().
void SP38::IntersectionHistory::addDetectorHistory (DetectorHistory * dh)
Adds a DetectorHistory to the set.
Definition at line 139 of file IntersectionHistory.cc.
Referenced by IntersectionHistory().
Phase * SP38::IntersectionHistory::getCurrentPhase ()
Definition at line 45 of file IntersectionHistory.cc.
References getPhase().
Referenced by SP38::SP38Simulation::getCurrentPhase(), and getCurrentPhaseDuration().
Phase * SP38::IntersectionHistory::getPhase (int time)
Definition at line 52 of file IntersectionHistory.cc.
Referenced by getCurrentPhase(), and SP38::SP38Simulation::setNewPhase().
double SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween (Phase * p, int start, int end)
Gets the maximum rate of cars that passed through the phase in one of its detectors when active in a given interval.
Parameters:
the phase
start of the interval
end of the interval
Definition at line 75 of file IntersectionHistory.cc.
References SP38::Phase::detectors, SP38::PhaseHistory::getActivationsIntervals(), getDetectorHistory(), getPhaseHistory(), sumAndPlot::i, SP38::PhaseHistory::totalActiveTime(), and SP38::DetectorHistory::totalDeactivations().
Referenced by SP38::SP38Simulation::getPhaseMaxDetectorThroughputBetween().
double SP38::IntersectionHistory::getPhaseThroughputBetween (Phase * p, int start, int end)
Gets the rate of cars that passed through the phase when active in a given interval.
Parameters:
the phase
start of the interval
end of the interval
Definition at line 105 of file IntersectionHistory.cc.
References SP38::Phase::detectors, SP38::PhaseHistory::getActivationsIntervals(), getDetectorHistory(), getPhaseHistory(), sumAndPlot::i, SP38::PhaseHistory::totalActiveTime(), and SP38::DetectorHistory::totalDeactivations().
Referenced by SP38::SP38Simulation::getPhaseThroughputBetween().
double SP38::IntersectionHistory::getMaxThroughput ()
Gets the maximum rate of cars that passed through the intersection when some phase was active.
Definition at line 132 of file IntersectionHistory.cc.
Referenced by SP38::SP38Simulation::getIntersectionMaxThroughput().
int SP38::IntersectionHistory::getCurrentPhaseDuration ()
Get how many time steps the current phase has continously been up to the current time.
Definition at line 63 of file IntersectionHistory.cc.
References getCurrentPhase(), getPhaseHistory(), and SP38::PhaseHistory::lastActivation().
Referenced by SP38::SP38Simulation::getCurrentPhaseDuration().