The PG Library: libpg::Policy Class Reference
libpg::Policy
libpg::Policy Class Reference
#include <Policy.hh>
Public Member Functions
virtual ~Policy ()
virtual void getAction (Vector dist, Vector &action, Observation &obs)=0
Detailed Description
This class defines the policy used to select the next action. Each policy will be implemented as a subclass of this kind.
Definition at line 10 of file Policy.hh.
Constructor & Destructor Documentation
virtual libpg::Policy::~Policy () [virtual]
Shut up compiler warning.
Definition at line 18 of file Policy.hh.
Member Function Documentation
virtual void libpg::Policy::getAction (Vector dist, Vector & action, Observation & obs) [pure virtual]
Sample next action according to policy, given a vector and observations. Note that the dist value vector is passed by copy deliberately.
Parameters:
dist the vector of values for each action
action return value indicting appropriate action(s)
obs the observation vector
Implemented in libpg::eGreedyPolicy, and libpg::SoftmaxPolicy.
Referenced by libpg::SARSAController::getAction(), libpg::QLearningController::getAction(), and libpg::LSTDQController::getAction().