The PG Library: SP38::DetectorHistory Class Reference
SP38::DetectorHistory
SP38::DetectorHistory Class Reference
#include <DetectorHistory.hh>
Public Member Functions
DetectorHistory (Detector *, int *, int, int)
Detector * getDetector ()
void setInitialState ()
void activate (double time)
void deactivate (double time)
bool isActive ()
int totalActivations (double)
int totalActivations (double, double)
int totalDeactivations (double)
int totalDeactivations (double, double)
double getLastActivationTime ()
double getLastDeactivationTime ()
int getMaxActivationsInInterval ()
Detailed Description
Keeps history of detector activations. Give some infered information about the detectors.
Definition at line 18 of file DetectorHistory.hh.
Constructor & Destructor Documentation
SP38::DetectorHistory::DetectorHistory (Detector * d, int * ct, int max, int m_a_i)
DetectorHistory Constructor.
Parameters:
The detector to keep history.
Current Time pointer.
Max time differente to current time to keep history.
Size of interval time to estimate maximum detector activations.
Definition at line 12 of file DetectorHistory.cc.
Member Function Documentation
Detector * SP38::DetectorHistory::getDetector ()
Gets the Detector.
Definition at line 28 of file DetectorHistory.cc.
void SP38::DetectorHistory::setInitialState ()
Sets the detector history as a valid initial state for a simulation.
Definition at line 20 of file DetectorHistory.cc.
References deactivate().
void SP38::DetectorHistory::activate (double time)
Sets the detector as active in the time given.
Parameters:
time when the detector was activated
Definition at line 64 of file DetectorHistory.cc.
void SP38::DetectorHistory::deactivate (double time)
Sets the detector as deactivated in the time given.
Parameters:
time when the detector was deactivated
Definition at line 77 of file DetectorHistory.cc.
Referenced by setInitialState().
bool SP38::DetectorHistory::isActive ()
Says if the detector is currently active.
Definition at line 35 of file DetectorHistory.cc.
Referenced by SP38::SP38Simulation::isDetectorActive().
int SP38::DetectorHistory::totalActivations (double start)
Gets total detector activations from a given time to the current time.
Parameters:
time to start counting
Definition at line 131 of file DetectorHistory.cc.
Referenced by SP38::SP38Simulation::getDetectorCountBetween().
int SP38::DetectorHistory::totalActivations (double start, double end)
Gets total detector activations from a start time to a end time.
Parameters:
time to start counting
time to end counting
Definition at line 140 of file DetectorHistory.cc.
References EPS.
int SP38::DetectorHistory::totalDeactivations (double start)
Gets total detector deactivations from a given time to the current time.
Parameters:
time to start counting
Definition at line 167 of file DetectorHistory.cc.
Referenced by SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween(), and SP38::IntersectionHistory::getPhaseThroughputBetween().
int SP38::DetectorHistory::totalDeactivations (double start, double end)
Gets total detector deactivations from a start time to a end time.
Parameters:
time to start counting
time to end counting
Definition at line 176 of file DetectorHistory.cc.
References EPS.
double SP38::DetectorHistory::getLastActivationTime ()
Gets the last activation time.
Definition at line 42 of file DetectorHistory.cc.
double SP38::DetectorHistory::getLastDeactivationTime ()
Gets the last deactivation time.
Definition at line 56 of file DetectorHistory.cc.
int SP38::DetectorHistory::getMaxActivationsInInterval ()
Gives the maximum estimated detectors activations in one given interval.
Definition at line 49 of file DetectorHistory.cc.
Referenced by SP38::SP38Simulation::getDetectorMaxThroughput().