The PG Library: libpg::Sampler Class Reference
libpg::Sampler
libpg::Sampler Class Reference
#include <Sampler.hh>
Static Public Member Functions
static int discrete (Vector &pdf, double cdf)
Detailed Description
Definition at line 6 of file Sampler.hh.
Member Function Documentation
int libpg::Sampler::discrete (Vector & pdf, double cdf) [static]
Definition at line 8 of file Sampler.cc.
References sumAndPlot::i.
Referenced by libpg::SoftmaxPolicy::getAction(), libpg::ImportanceSamplingController::getAction(), and libpg::BasicController::getAction().