The PG Library: libpg::BasicController Class Reference
libpg::BasicController
libpg::BasicController Class Reference
#include <BasicController.hh>
Public Member Functions
BasicController (Approximator *approx)
virtual ~BasicController ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual void computePartialsAndFeedback (Observation &obs, int sampledAct, double weight=1.0)
virtual int getInputDim ()
virtual int getNumParams ()
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void accumulateGrad (Vector &reward, Observation &newObs)
virtual void resetGrad ()
virtual void instantStep (Vector &reward)
virtual void batchStep ()
virtual void computeDirection (int steps)
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetParams ()
virtual void randomizeParams (double maxRand)
virtual double getMaxParam ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void reduce (Vector &v, Approximator::StatsEnum s)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
Public Attributes
Approximator * approx
Vector dist
Vector distribution
Detailed Description
The first concrete controller class that only assumes that there is exactly one ParameterisedDistribution that it talks to. Has not yet made concrete the process of sampling from approximated distributions.
Definition at line 14 of file BasicController.hh.
Constructor & Destructor Documentation
libpg::BasicController::BasicController (Approximator * approx)
Parameters:
parameterised distribution we'll be using today
Definition at line 12 of file BasicController.cc.
References dist, distribution, and libpg::Approximator::getOutputDim().
virtual libpg::BasicController::~BasicController () [virtual]
Definition at line 32 of file BasicController.hh.
Member Function Documentation
void libpg::BasicController::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Where the real coding is done to implement
Where the real coding is done to implement softmax
Implements libpg::Controller.
Reimplemented in libpg::BinaryController, libpg::LSTDQController, libpg::QLearningController, libpg::SARSAController, and libpg::ValueController.
Definition at line 24 of file BasicController.cc.
References approx, computePartialsAndFeedback(), libpg::Sampler::discrete(), dist, distribution, libpg::Approximator::doApprox(), libpg::Observation::getEligible(), and sumAndPlot::i.
Referenced by libpg::ImportanceSamplingController::getAction(), and libpg::ImportanceSamplingController::getMostProbAction().
void libpg::BasicController::getMostProbAction (Observation & obs, Vector & action) [virtual]
Return the most probable action for evaluation purposes only.
Parameters:
Observation vector
empty vector to load with the most probably action
Reimplemented from libpg::Controller.
Reimplemented in libpg::BinaryController, libpg::LSTDQController, and libpg::ValueController.
Definition at line 80 of file BasicController.cc.
References approx, dist, libpg::Approximator::doApprox(), and sumAndPlot::i.
void libpg::BasicController::computePartialsAndFeedback (Observation & obs, int sampledAct, double weight = 1.0) [virtual]
compute partial derivative of prob of action wrt a vector of likelihoods then feedback to the underlying parametersiation.
Implements libpg::Controller.
Reimplemented in libpg::ValueController.
Definition at line 64 of file BasicController.cc.
References approx, dist, and libpg::Approximator::feedbackGrad().
Referenced by getAction().
int libpg::BasicController::getInputDim () [virtual]
Just return the input dimensionality of the approximator
Implements libpg::Controller.
Definition at line 98 of file BasicController.cc.
References approx, and libpg::Approximator::getInputDim().
Referenced by libpg::LSTDQController::getAction().
int libpg::BasicController::getNumParams () [virtual]
How many parameters does it have
Implements libpg::Controller.
Definition at line 168 of file BasicController.cc.
References approx, and libpg::Approximator::getNumParams().
Referenced by libpg::LSTDQController::reduce(), and libpg::LSTDQController::scatter().
void libpg::BasicController::discountTrace () [virtual]
The remaining methods just pass onto equiv Approximator functions. We have to do it in this ugly way because more advanced multiple agent controllers will need to override these functions to update all agents in turn.
Implements libpg::Controller.
Reimplemented in libpg::LSTDQController, libpg::QLearningController, and libpg::SARSAController.
Definition at line 111 of file BasicController.cc.
References approx, and libpg::Approximator::discountTrace().
void libpg::BasicController::setDiscount (double discount) [virtual]
Implements libpg::Controller.
Reimplemented in libpg::LSTDQController, libpg::QLearningController, and libpg::SARSAController.
Definition at line 115 of file BasicController.cc.
References approx, and libpg::Approximator::setDiscount().
void libpg::BasicController::accumulateGrad (Vector & reward, Observation & newObs) [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 119 of file BasicController.cc.
References libpg::Approximator::accumulateGrad(), and approx.
void libpg::BasicController::resetGrad () [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 124 of file BasicController.cc.
References approx, and libpg::Approximator::resetGrad().
void libpg::BasicController::instantStep (Vector & reward) [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController, libpg::QLearningController, and libpg::SARSAController.
Definition at line 128 of file BasicController.cc.
References approx, and libpg::Approximator::instantStep().
void libpg::BasicController::batchStep () [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 139 of file BasicController.cc.
References approx, and libpg::Approximator::batchStep().
void libpg::BasicController::computeDirection (int steps) [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 135 of file BasicController.cc.
References approx, and libpg::Approximator::computeDirection().
void libpg::BasicController::setStepSize (double stepSize) [virtual]
Implements libpg::Controller.
Definition at line 143 of file BasicController.cc.
References approx, and libpg::Approximator::setStepSize().
void libpg::BasicController::resetTrace () [virtual]
Implements libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 148 of file BasicController.cc.
References approx, and libpg::Approximator::resetTrace().
void libpg::BasicController::resetParams () [virtual]
Implements libpg::Controller.
Definition at line 152 of file BasicController.cc.
References approx, and libpg::Approximator::resetParams().
void libpg::BasicController::randomizeParams (double maxRand) [virtual]
Reimplemented from libpg::Controller.
Definition at line 157 of file BasicController.cc.
References approx, and libpg::Approximator::randomizeParams().
double libpg::BasicController::getMaxParam () [virtual]
Implements libpg::Controller.
Definition at line 162 of file BasicController.cc.
References approx, and libpg::Approximator::getMaxParam().
virtual void libpg::BasicController::write (std::ostream & o) [virtual]
Reimplemented from libpg::Controller.
virtual void libpg::BasicController::read (std::istream & o) [virtual]
Reimplemented from libpg::Controller.
void libpg::BasicController::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 181 of file BasicController.cc.
References approx, libpg::Approximator::DIST, distribution, and libpg::Approximator::reduce().
Referenced by libpg::ImportanceSamplingController::getAction(), and libpg::ImportanceSamplingController::getMostProbAction().
void libpg::BasicController::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Controller.
Reimplemented in libpg::LSTDQController.
Definition at line 193 of file BasicController.cc.
References approx, and libpg::Approximator::scatter().
Member Data Documentation
Approximator* libpg::BasicController::approx
the parameterised distribution
Definition at line 22 of file BasicController.hh.
Referenced by accumulateGrad(), libpg::LSTDQController::batchStep(), batchStep(), computeDirection(), computePartialsAndFeedback(), libpg::LSTDQController::delayedInstantStep(), libpg::SARSAController::discountTrace(), libpg::QLearningController::discountTrace(), discountTrace(), libpg::LSTDQController::doApprox(), libpg::SARSAController::getAction(), libpg::QLearningController::getAction(), libpg::LSTDQController::getAction(), libpg::BinaryController::getAction(), getAction(), getInputDim(), getMaxParam(), libpg::BinaryController::getMostProbAction(), getMostProbAction(), getNumParams(), libpg::SARSAController::instantStep(), libpg::QLearningController::instantStep(), instantStep(), randomizeParams(), libpg::LSTDQController::reduce(), reduce(), resetGrad(), resetParams(), resetTrace(), libpg::LSTDQController::scatter(), scatter(), libpg::SARSAController::setDiscount(), libpg::QLearningController::setDiscount(), libpg::LSTDQController::setDiscount(), setDiscount(), and setStepSize().
Vector libpg::BasicController::dist
The output of the approximator that we will pass through softmax
Reimplemented in libpg::SARSAController.
Definition at line 27 of file BasicController.hh.
Referenced by BasicController(), computePartialsAndFeedback(), libpg::BinaryController::getAction(), getAction(), libpg::BinaryController::getMostProbAction(), and getMostProbAction().
Vector libpg::BasicController::distribution
Definition at line 29 of file BasicController.hh.
Referenced by BasicController(), getAction(), and reduce().