The PG Library: libpg::GPomdp Class Reference
libpg::GPomdp
libpg::GPomdp Class Reference
#include <GPomdp.hh>
Public Member Functions
GPomdp ()
GPomdp (Controller *controller, Simulator *simulator, double discount, double stepSize)
virtual double learnCore (int stepsPerEpoch, int &totalSteps)
virtual double doSteps (Vector &totalReward, int steps, bool learn)
Detailed Description
Definition at line 6 of file GPomdp.hh.
Constructor & Destructor Documentation
libpg::GPomdp::GPomdp ()
Don't call this one directly. Tears will result.
Definition at line 13 of file GPomdp.hh.
libpg::GPomdp::GPomdp (Controller * controller, Simulator * simulator, double discount, double stepSize)
Top level piece of glue for Policy gradient, link the controller and the simulator
Parameters:
Controller
Simulator (problem specific)
discount factor [0, 1]. If 1, trace must be reset occasionally or have 0 mean reward.
Definition at line 18 of file GPomdp.cc.
Member Function Documentation
double libpg::GPomdp::learnCore (int stepsPerEpoch, int & totalSteps) [virtual]
Use the GPOMDP estimate to step parameters in the correct direction.
Parameters:
steps to estimate gradient for
ref to variable counting total learning steps. include any steps used for a line search
Reimplemented from libpg::RLAlg.
Reimplemented in libpg::LineSearchAlg.
Definition at line 73 of file GPomdp.cc.
References libpg::RLAlg::baseline, libpg::Controller::batchStep(), libpg::Controller::computeDirection(), libpg::RLAlg::controller, doSteps(), libpg::Simulator::getRewardDim(), libpg::RLAlg::simulator, and libpg::RLAlg::useAutoBaseline.
double libpg::GPomdp::doSteps (Vector & totalRewards, int steps, bool learn) [virtual]
Do a fixed number of individual steps, aggregating the reward and gradient if learn is true. No output is done. Could also be termed an "epoch"
Parameters:
returns average rewards for each reward dimension
number ofsteps to accumulate gradient for
should learning be turned on, or are we just exploiting/evaluating the current policy?
Implements libpg::RLAlg.
Definition at line 30 of file GPomdp.cc.
References libpg::Controller::accumulateGrad(), libpg::RLAlg::baseline, libpg::RLAlg::controller, libpg::Controller::discountTrace(), libpg::Simulator::doAction(), libpg::Controller::getAction(), libpg::Simulator::getActionDim(), libpg::Simulator::getObservation(), libpg::Simulator::getReward(), libpg::Simulator::getRewardDim(), libpg::Observation::getSteps(), libpg::RLAlg::obs, libpg::Controller::resetGrad(), sumAndPlot::s, libpg::Observation::setSteps(), and libpg::RLAlg::simulator.
Referenced by libpg::LineSearchAlg::incrementLineSearch(), libpg::LineSearchAlg::learnCore(), and learnCore().