The PG Library: SP38::SP38PGSimulator Class Reference
SP38::SP38PGSimulator
SP38::SP38PGSimulator Class Reference
#include <SP38PGSimulator.hh>
Public Member Functions
SP38PGSimulator (ScenarioReader *, int, string, RewardType, bool, bool, bool, bool, int, bool)
virtual ~SP38PGSimulator ()
int getMaxEpisodeLength ()
int getObsRows ()
int getObsCols ()
int getAgents ()
int getActionDim ()
int getRewardDim ()
void getReward (libpg::Vector &rewards)
void getObservation (libpg::Observation &obs)
int doAction (libpg::Vector &action)
SP38Simulation * getSP38Simulation ()
Scenario * getScenario ()
ScenarioHistory * getCurrentScenarioHistory ()
void setDebug (bool)
void setNoisy (bool)
bool isUsingConstantFeature ()
bool isUsingCurrentPhaseFeature ()
bool isUsingPhaseDurationFeature ()
bool isUsingCycleDurationFeature ()
bool isUsingAllPhasesDurationFeature ()
bool isUsingDetectorActiveFeature ()
bool isUsingPhasesHistoryFeature ()
bool isUsingIgnoredFeature ()
bool isUsingDayHourFeature ()
void setUsingConstantFeature (bool)
void setUsingCurrentPhaseFeature (bool)
void setUsingPhaseDurationFeature (bool)
void setUsingCycleDurationFeature (bool)
void setUsingAllPhasesDurationFeature (bool)
void setUsingDetectorActiveFeature (bool)
void setUsingPhasesHistoryFeature (bool)
void setUsingIgnoredFeature (bool)
void setUsingDayHourFeature (bool)
Detailed Description
Implements the libpg::Simulator for the Signalling Traffic problem.
Definition at line 28 of file SP38PGSimulator.hh.
Constructor & Destructor Documentation
SP38::SP38PGSimulator::SP38PGSimulator (ScenarioReader * sr, int sd, string host, RewardType tp, bool fapc, bool f, bool d, bool n, int maxt, bool dp)
SP38PGSimulator constructor.
Parameters:
The instance reader
Step duration in seconds (Or interval between actions of the RL Algorithm)
host of the simulator
the reward type
Force the All Phases in cycle constraint
Execute optimisation forever
Show debug messages
Show some general messages
Maximum connection tries
Show debug messages for the SP38 protocol
Definition at line 18 of file SP38PGSimulator.cc.
References SP38::SP38Simulation::getScenario(), and SP38::SP38Simulation::startSimulation().
virtual SP38::SP38PGSimulator::~SP38PGSimulator () [virtual]
Definition at line 33 of file SP38PGSimulator.hh.
Member Function Documentation
int SP38::SP38PGSimulator::getMaxEpisodeLength () [virtual]
Maximum episode length in steps. For planning mode. Only used by GOALPomdp at the moment.
Reimplemented from libpg::Simulator.
Definition at line 35 of file SP38PGSimulator.hh.
int SP38::SP38PGSimulator::getObsRows () [virtual]
Gets the number of rows in the observation vector.
Implements libpg::Simulator.
Definition at line 241 of file SP38PGSimulator.cc.
References SP38::Scenario::getCycleDuration(), SP38::Scenario::getMaxTotalDetectors(), SP38::Scenario::getMaxTotalPhases(), SP38::SP38Simulation::getTimeStepSize(), isUsingAllPhasesDurationFeature(), isUsingConstantFeature(), isUsingCurrentPhaseFeature(), isUsingCycleDurationFeature(), isUsingDayHourFeature(), isUsingDetectorActiveFeature(), isUsingIgnoredFeature(), isUsingPhaseDurationFeature(), and isUsingPhasesHistoryFeature().
Referenced by SP38::SP38Optimisator::getController().
int SP38::SP38PGSimulator::getObsCols () [virtual]
Gets the number of columns in the observation vector.
Implements libpg::Simulator.
Definition at line 312 of file SP38PGSimulator.cc.
References SP38::Scenario::intersections.
Referenced by getActionDim(), getAgents(), and getRewardDim().
int SP38::SP38PGSimulator::getAgents () [virtual]
Gets the number of agents.
Implements libpg::Simulator.
Definition at line 319 of file SP38PGSimulator.cc.
References getObsCols().
int SP38::SP38PGSimulator::getActionDim () [virtual]
Gets the dimension of action vector.
Implements libpg::Simulator.
Definition at line 326 of file SP38PGSimulator.cc.
References getObsCols().
int SP38::SP38PGSimulator::getRewardDim () [virtual]
Gets the dimension of reward vector.
Implements libpg::Simulator.
Definition at line 333 of file SP38PGSimulator.cc.
References getObsCols().
void SP38::SP38PGSimulator::getReward (libpg::Vector & rewards) [virtual]
Sets the reward received at the current state.
Parameters:
rewards to be set
Implements libpg::Simulator.
Definition at line 31 of file SP38PGSimulator.cc.
References SP38::Scenario::intersections, SP38::RT_LocalReward, SP38::RT_MixedReward, and SP38::RT_PowerLocalReward.
void SP38::SP38PGSimulator::getObservation (libpg::Observation & obs) [virtual]
Sets the obersvations for the current state.
Parameters:
observations to be set
Implements libpg::Simulator.
Definition at line 103 of file SP38PGSimulator.cc.
References SP38::SP38Simulation::getCurrentCycleDuration(), SP38::SP38Simulation::getCurrentPhase(), SP38::SP38Simulation::getCurrentPhaseDuration(), SP38::SP38Simulation::getCurrentTime(), SP38::Scenario::getCycleDuration(), SP38::SP38Simulation::getDayHour(), SP38::SP38Simulation::getDayHourMinute(), libpg::Observation::getFeatures(), SP38::SP38Simulation::getIntersectionMaxThroughput(), SP38::Scenario::getMaxTotalDetectors(), SP38::Scenario::getMaxTotalPhases(), SP38::SP38Simulation::getPhaseDurationInCurrentCycle(), SP38::SP38Simulation::getPhaseThroughputInCurrentCyle(), SP38::SP38Simulation::getPhaseThroughputInLastCompletedCyle(), SP38::SP38Simulation::getTimeStepSize(), SP38::Scenario::intersections, SP38::SP38Simulation::isAnythingScheduled(), SP38::SP38Simulation::isDetectorActive(), isUsingAllPhasesDurationFeature(), isUsingConstantFeature(), isUsingCurrentPhaseFeature(), isUsingCycleDurationFeature(), isUsingDayHourFeature(), isUsingDetectorActiveFeature(), isUsingIgnoredFeature(), isUsingPhaseDurationFeature(), and isUsingPhasesHistoryFeature().
int SP38::SP38PGSimulator::doAction (libpg::Vector & action) [virtual]
Sets the schedule and simulates one step.
Parameters:
action vector with schedules
Implements libpg::Simulator.
Definition at line 273 of file SP38PGSimulator.cc.
References SP38::SP38Simulation::doStep(), SP38::Scenario::intersections, SP38::SP38Simulation::setNewPhase(), and SP38::SP38Simulation::simulating().
SP38Simulation * SP38::SP38PGSimulator::getSP38Simulation ()
Gets the simulation
Definition at line 289 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::getController().
Scenario * SP38::SP38PGSimulator::getScenario ()
Gets the scenario
Definition at line 297 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
ScenarioHistory * SP38::SP38PGSimulator::getCurrentScenarioHistory ()
Gets the current scenario history. Note that it changes when the simulation is restarted.
Definition at line 305 of file SP38PGSimulator.cc.
References SP38::SP38Simulation::getCurrentScenarioHistory().
void SP38::SP38PGSimulator::setDebug (bool d)
Set debug nessages
Definition at line 340 of file SP38PGSimulator.cc.
void SP38::SP38PGSimulator::setNoisy (bool n)
Set general messages
Definition at line 347 of file SP38PGSimulator.cc.
bool SP38::SP38PGSimulator::isUsingConstantFeature ()
Tells if it's using a bit always equals one in the feature vector.
Definition at line 354 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingCurrentPhaseFeature ()
Tells if it's placing the current phase index in the feature vector.
Definition at line 361 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingPhaseDurationFeature ()
Tells if it's placing the duration of the current phase in the feature vector.
Definition at line 368 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingCycleDurationFeature ()
Tells if it's placing the current cycle duration in the feature vector.
Definition at line 375 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingAllPhasesDurationFeature ()
Tells if it's placing the duration of every phase in the feature vector.
Definition at line 382 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingDetectorActiveFeature ()
Tells if it's placing the activation state of every detector in the feature vector.
Definition at line 389 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingPhasesHistoryFeature ()
Tells if it's placing the phase's throughput in the current cycle in the feature vector.
Definition at line 396 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingIgnoredFeature ()
Tells if it's using a bit equals one when next action will be ignored in the feature vector.
Definition at line 403 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
bool SP38::SP38PGSimulator::isUsingDayHourFeature ()
Tells if it's placing the current hour of the day in the feature vector.
Definition at line 410 of file SP38PGSimulator.cc.
Referenced by getObservation(), and getObsRows().
void SP38::SP38PGSimulator::setUsingConstantFeature (bool v)
Sets if it'll use a bit always equals one in the feature vector.
Definition at line 418 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingCurrentPhaseFeature (bool v)
Sets if it'll place the current phase index in the feature vector.
Definition at line 425 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingPhaseDurationFeature (bool v)
Sets if it'll place the duration of the current phase in the feature vector.
Definition at line 432 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingCycleDurationFeature (bool v)
Sets if it'll place the current cycle duration in the feature vector.
Definition at line 439 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingAllPhasesDurationFeature (bool v)
Sets if it'll place the duration of every phase in the feature vector.
Definition at line 446 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingDetectorActiveFeature (bool v)
Sets if it'll place the activation state of every detector in the feature vector.
Definition at line 453 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingPhasesHistoryFeature (bool v)
Sets if it'll place the phase's throughput in the current cycle in the feature vector.
Definition at line 460 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingIgnoredFeature (bool v)
Sets if it'll use a bit equals one when next action will be ignored in the feature vector.
Definition at line 467 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
void SP38::SP38PGSimulator::setUsingDayHourFeature (bool v)
Sets if it'll place the current hour of the day in the feature vector.
Definition at line 474 of file SP38PGSimulator.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().