The PG Library: libpg::HardLimitTransform Class Reference
libpg::HardLimitTransform
libpg::HardLimitTransform Class Reference
#include <HardLimitTransform.hh>
Public Member Functions
HardLimitTransform (Controller *c, double penalty)
~HardLimitTransform ()
virtual void setMax (double maxp)
virtual void instantStep (Vector &rewards)
virtual void batchStep ()
Protected Member Functions
virtual void checkParams ()
Protected Attributes
Controller * controller
double maxp
Vector params
Detailed Description
Stop the underlying parameters (or values) from growing past a fixed absolute limit Useful if you have an RL process that drives parameters past the point where exponentiating them causes overflow problems.
Definition at line 12 of file HardLimitTransform.hh.
Constructor & Destructor Documentation
libpg::HardLimitTransform::HardLimitTransform (Controller * c, double maxp)
Implements absolute max for parameter values.
Definition at line 14 of file HardLimitTransform.cc.
References controller, libpg::Controller::getNumParams(), and params.
libpg::HardLimitTransform::~HardLimitTransform ()
Definition at line 25 of file HardLimitTransform.hh.
Member Function Documentation
void libpg::HardLimitTransform::checkParams () [protected, virtual]
The only non-trivial routine.. just make sure all parameter values are within the maximum abosolute val. Limit them if they are.
Definition at line 53 of file HardLimitTransform.cc.
References libpg::UBlasExtras::containsNaN(), controller, sumAndPlot::i, maxp, libpg::Approximator::PARAMS, params, libpg::Controller::reduce(), and libpg::Controller::scatter().
Referenced by batchStep(), and instantStep().
void libpg::HardLimitTransform::setMax (double maxp) [virtual]
Definition at line 23 of file HardLimitTransform.cc.
void libpg::HardLimitTransform::instantStep (Vector & rewards) [virtual]
Reimplemented from libpg::TransformController.
Definition at line 39 of file HardLimitTransform.cc.
References checkParams(), controller, and libpg::Controller::instantStep().
void libpg::HardLimitTransform::batchStep () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 29 of file HardLimitTransform.cc.
References libpg::Controller::batchStep(), checkParams(), and controller.
Member Data Documentation
Controller* libpg::HardLimitTransform::controller [protected]
Reimplemented from libpg::TransformController.
Definition at line 17 of file HardLimitTransform.hh.
Referenced by batchStep(), checkParams(), HardLimitTransform(), and instantStep().
double libpg::HardLimitTransform::maxp [protected]
Definition at line 18 of file HardLimitTransform.hh.
Referenced by checkParams().
Vector libpg::HardLimitTransform::params [protected]
Definition at line 19 of file HardLimitTransform.hh.
Referenced by checkParams(), and HardLimitTransform().