The PG Library: libpg::Bias Class Reference
libpg::Bias
libpg::Bias Class Reference
#include <Bias.hh>
Public Member Functions
Bias (Approximator *approx, Teacher *teacher)
virtual ~Bias ()
virtual void doApprox (Observation &obs, Vector &output)
Protected Attributes
Teacher * teacher
Vector teacherOutput
Detailed Description
This controller is a biased version of the ManyToOneController.
Definition at line 15 of file Bias.hh.
Constructor & Destructor Documentation
libpg::Bias::Bias (Approximator * approx, Teacher * teacher)
Use a teacher to add an amount of bias to an approximators output.
Definition at line 13 of file Bias.cc.
References libpg::Approximator::getOutputDim(), and teacherOutput.
virtual libpg::Bias::~Bias () [virtual]
Definition at line 25 of file Bias.hh.
Member Function Documentation
void libpg::Bias::doApprox (Observation & obs, Vector & output) [virtual]
Where the real coding is done to implement
Where the real coding is done to implement softmax
Reimplemented from libpg::TransformApproximator.
Definition at line 29 of file Bias.cc.
References libpg::TransformApproximator::approx, libpg::Teacher::doApprox(), libpg::Approximator::doApprox(), OutputWeight, teacher, and teacherOutput.
Member Data Documentation
Teacher* libpg::Bias::teacher [protected]
Definition at line 19 of file Bias.hh.
Referenced by doApprox().
Vector libpg::Bias::teacherOutput [protected]
Definition at line 20 of file Bias.hh.
Referenced by Bias(), and doApprox().