The PG Library: PSRCassandra Class Reference
PSRCassandra Class Reference
#include <PSRCassandra.hh>
Public Member Functions
PSRCassandra (Cassandra &c)
virtual int doAction (int action)
virtual Vector getBelief ()
virtual void getObservation (Observation &obs)
virtual int getObsRows ()
Protected Member Functions
void discoverPSR ()
bool recursePSRDiscovery (std::string test, Matrix &U)
Protected Attributes
Vector belief
Detailed Description
Definition at line 17 of file PSRCassandra.hh.
Constructor & Destructor Documentation
PSRCassandra::PSRCassandra (Cassandra & c)
Definition at line 15 of file PSRCassandra.cc.
References belief, discoverPSR(), Cassandra::numObservations, and Cassandra::numStates.
Member Function Documentation
void PSRCassandra::discoverPSR () [protected]
Discover exact PSR core tests and params
Definition at line 94 of file PSRCassandra.cc.
References sumAndPlot::a, Cassandra::actionObservations, Cassandra::actionTransitions, Cassandra::numActions, Cassandra::numObservations, Cassandra::numStates, recursePSRDiscovery(), sumAndPlot::s, and test().
Referenced by PSRCassandra().
bool PSRCassandra::recursePSRDiscovery (std::string test, Matrix & U) [protected]
Referenced by discoverPSR().
int PSRCassandra::doAction (int action) [virtual]
Perform the action with the specified index, generating a state and observation.
action, the index of the action to perform.
Reimplemented from Cassandra.
Definition at line 42 of file PSRCassandra.cc.
References Cassandra::actionObservations, Cassandra::actionTransitions, belief, Cassandra::currAction, Cassandra::currObservation, Cassandra::currState, Cassandra::lastState, and Cassandra::numActions.
Vector PSRCassandra::getBelief () [virtual]
Definition at line 246 of file PSRCassandra.cc.
References belief.
void PSRCassandra::getObservation (Observation & obs) [virtual]
Returns an observation generated by the previous call to doAction.
Observations are found when the action is performed, not on a call to getObservation. Multiple calls to getObservation, without a call to doAction, will return the same observation.
Reimplemented from Cassandra.
Definition at line 251 of file PSRCassandra.cc.
References belief, libpg::Observation::getFeatures(), libpg::Observation::getSteps(), and sumAndPlot::i.
int PSRCassandra::getObsRows () [virtual]
Get the number of rows in observation matrix. Generally the length of the observation vector.
Reimplemented from Cassandra.
Definition at line 259 of file PSRCassandra.cc.
Member Data Documentation
Vector PSRCassandra::belief [protected]
Definition at line 35 of file PSRCassandra.hh.
Referenced by doAction(), getBelief(), getObservation(), and PSRCassandra().