The PG Library: SP38::Scenario Class Reference
SP38::Scenario
SP38::Scenario Class Reference
#include <Scenario.hh>
Public Member Functions
Scenario ()
Intersection * getIntersection (string id)
Intersection * getIntersection (int scatsId)
Link * getLink (string id)
void addIntersection (Intersection *)
void addLink (Link *)
void setCycleDuration (int duration)
int getMaxTotalPhases ()
int getMaxTotalDetectors ()
int getCycleDuration ()
Public Attributes
IntersectionSet intersections
LinkSet links
Detailed Description
A Traffic Scenario or Instance.
Definition at line 17 of file Scenario.hh.
Constructor & Destructor Documentation
SP38::Scenario::Scenario ()
Definition at line 11 of file Scenario.cc.
Member Function Documentation
Intersection * SP38::Scenario::getIntersection (string id)
Definition at line 65 of file Scenario.cc.
References sumAndPlot::i, and intersections.
Intersection * SP38::Scenario::getIntersection (int scatsId)
Definition at line 75 of file Scenario.cc.
References sumAndPlot::i, and intersections.
Link * SP38::Scenario::getLink (string id)
Definition at line 112 of file Scenario.cc.
References links.
void SP38::Scenario::addIntersection (Intersection * i)
Definition at line 34 of file Scenario.cc.
References intersections.
void SP38::Scenario::addLink (Link * l)
Definition at line 42 of file Scenario.cc.
References SP38::Intersection::addInLink(), SP38::Intersection::addNeighbour(), SP38::Intersection::addOutLink(), SP38::Link::getFrom(), SP38::Link::getTo(), and links.
void SP38::Scenario::setCycleDuration (int d)
Sets the cycle duration. Default is 120
Definition at line 19 of file Scenario.cc.
Referenced by SP38::SP38Optimisator::SP38Optimisator().
int SP38::Scenario::getMaxTotalPhases ()
Definition at line 97 of file Scenario.cc.
References sumAndPlot::i, intersections, and sumAndPlot::max.
Referenced by SP38::SP38PGSimulator::getObservation(), and SP38::SP38PGSimulator::getObsRows().
int SP38::Scenario::getMaxTotalDetectors ()
Definition at line 84 of file Scenario.cc.
References sumAndPlot::i, intersections, and sumAndPlot::max.
Referenced by SP38::SP38PGSimulator::getObservation(), and SP38::SP38PGSimulator::getObsRows().
int SP38::Scenario::getCycleDuration ()
Gets the cycle duration.
Definition at line 26 of file Scenario.cc.
Referenced by SP38::SP38Simulation::doStep(), SP38::ScenarioHistory::getCurrentCycleDuration(), SP38::SP38PGSimulator::getObservation(), SP38::SP38PGSimulator::getObsRows(), SP38::SP38Simulation::getPhaseThroughputInLastCompletedCyle(), SP38::ScenarioHistory::ScenarioHistory(), and SP38::ScenarioHistory::setCurrentTime().
Member Data Documentation
IntersectionSet SP38::Scenario::intersections
Definition at line 34 of file Scenario.hh.
Referenced by addIntersection(), SP38::SP38PGSimulator::doAction(), SP38::SP38Simulation::endSimulation(), getIntersection(), getMaxTotalDetectors(), getMaxTotalPhases(), SP38::SP38PGSimulator::getObsCols(), SP38::SP38PGSimulator::getObservation(), SP38::SP38PGSimulator::getReward(), SP38::ScenarioHistory::ScenarioHistory(), SP38::SP38Optimisator::SP38Optimisator(), and SP38::SP38Simulation::startSimulation().
LinkSet SP38::Scenario::links
Definition at line 35 of file Scenario.hh.
Referenced by addLink(), and getLink().