The PG Library: libpg::TransformController Class Reference
libpg::TransformController
libpg::TransformController Class Reference
#include <TransformController.hh>
Public Member Functions
TransformController (Controller *controller)
virtual ~TransformController ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void computePartialsAndFeedback (Observation &obs, int sampledAct, double weight=1.0)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual int getInputDim ()
virtual int getNumParams ()
virtual void discountTrace ()
virtual void setDiscount (double discount)
virtual void accumulateGrad (Vector &reward, Observation &newObs)
virtual void resetGrad ()
virtual void instantStep (Vector &reward)
virtual void batchStep ()
virtual void computeDirection (int steps)
virtual void setStepSize (double stepSize)
virtual void resetTrace ()
virtual void resetParams ()
virtual void randomizeParams (double maxRand)
virtual double getMaxParam ()
virtual void write (std::ostream &o)
virtual void read (std::istream &o)
virtual void reduce (Vector &v, Approximator::StatsEnum s)
virtual void scatter (Vector &v, Approximator::StatsEnum s)
Protected Attributes
Controller * controller
Detailed Description
A dummy controller that serves as a basis for sub-classes to build transformations of observations and actions on without having to define all the abstract methods below.
Definition at line 13 of file TransformController.hh.
Constructor & Destructor Documentation
libpg::TransformController::TransformController (Controller * controller)
Parameters:
underlying controller.
Definition at line 14 of file TransformController.cc.
virtual libpg::TransformController::~TransformController () [virtual]
Definition at line 24 of file TransformController.hh.
Member Function Documentation
void libpg::TransformController::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Just pass to underlying controller
Implements libpg::Controller.
Reimplemented in libpg::CatObsActionTransform, libpg::HMMTransform, libpg::ImportanceSamplingController, libpg::NACTransform, libpg::ObsWindowTransform, libpg::PSRTransform, and libpg::OLBFGS.
Definition at line 22 of file TransformController.cc.
References controller, and libpg::Controller::getAction().
void libpg::TransformController::computePartialsAndFeedback (Observation & obs, int sampledAct, double weight = 1.0) [virtual]
compute partial derivative of prob of action wrt a vector of likelihoods then feedback to the underlying parametersiation.
Implements libpg::Controller.
Reimplemented in libpg::ImportanceSamplingController.
Definition at line 28 of file TransformController.cc.
References libpg::Controller::computePartialsAndFeedback(), and controller.
void libpg::TransformController::getMostProbAction (Observation & obs, Vector & action) [virtual]
Just pass to underlying controller
Parameters:
Observation vector
empty vector to load with the most probably action
Reimplemented from libpg::Controller.
Reimplemented in libpg::ImportanceSamplingController, libpg::NACTransform, and libpg::OLBFGS.
Definition at line 37 of file TransformController.cc.
References controller, and libpg::Controller::getMostProbAction().
int libpg::TransformController::getInputDim () [virtual]
Just pass to underlying controller
Implements libpg::Controller.
Definition at line 45 of file TransformController.cc.
References controller, and libpg::Controller::getInputDim().
Referenced by libpg::NACTransform::delayedInstantStep(), libpg::NACTransform::getAction(), and libpg::NACTransform::updateStatistics().
int libpg::TransformController::getNumParams () [virtual]
How many parameters does it have
Implements libpg::Controller.
Definition at line 118 of file TransformController.cc.
References controller, and libpg::Controller::getNumParams().
Referenced by libpg::NACTransform::reduce(), and libpg::NACTransform::scatter().
void libpg::TransformController::discountTrace () [virtual]
The remaining methods just pass onto equiv Controller functions. We have to do it in this ugly way because more advanced multiple agent controllers will need to override these functions to update all agents in turn.
Implements libpg::Controller.
Reimplemented in libpg::NACTransform, and libpg::OLBFGS.
Definition at line 58 of file TransformController.cc.
References controller, and libpg::Controller::discountTrace().
void libpg::TransformController::setDiscount (double discount) [virtual]
Implements libpg::Controller.
Reimplemented in libpg::ImportanceSamplingController, libpg::NACTransform, and libpg::OLBFGS.
Definition at line 63 of file TransformController.cc.
References controller, and libpg::Controller::setDiscount().
void libpg::TransformController::accumulateGrad (Vector & reward, Observation & newObs) [virtual]
Reimplemented from libpg::Controller.
Definition at line 68 of file TransformController.cc.
References libpg::Controller::accumulateGrad(), and controller.
void libpg::TransformController::resetGrad () [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::NACTransform, and libpg::OLBFGS.
Definition at line 73 of file TransformController.cc.
References controller, and libpg::Controller::resetGrad().
void libpg::TransformController::instantStep (Vector & reward) [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::HardLimitTransform, libpg::ImportanceSamplingController, libpg::NACTransform, libpg::RegularizeTransform, and libpg::OLBFGS.
Definition at line 78 of file TransformController.cc.
References controller, and libpg::Controller::instantStep().
void libpg::TransformController::batchStep () [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::HardLimitTransform, libpg::NACTransform, and libpg::RegularizeTransform.
Definition at line 88 of file TransformController.cc.
References libpg::Controller::batchStep(), and controller.
void libpg::TransformController::computeDirection (int steps) [virtual]
Reimplemented from libpg::Controller.
Reimplemented in libpg::NACTransform.
Definition at line 83 of file TransformController.cc.
References libpg::Controller::computeDirection(), and controller.
void libpg::TransformController::setStepSize (double stepSize) [virtual]
Implements libpg::Controller.
Reimplemented in libpg::PSRTransform, libpg::RegularizeTransform, and libpg::OLBFGS.
Definition at line 93 of file TransformController.cc.
References controller, and libpg::Controller::setStepSize().
void libpg::TransformController::resetTrace () [virtual]
Implements libpg::Controller.
Reimplemented in libpg::ImportanceSamplingController, libpg::NACTransform, and libpg::OLBFGS.
Definition at line 98 of file TransformController.cc.
References controller, and libpg::Controller::resetTrace().
void libpg::TransformController::resetParams () [virtual]
Implements libpg::Controller.
Definition at line 103 of file TransformController.cc.
References controller, and libpg::Controller::resetParams().
void libpg::TransformController::randomizeParams (double maxRand) [virtual]
Reimplemented from libpg::Controller.
Definition at line 108 of file TransformController.cc.
References controller, and libpg::Controller::randomizeParams().
double libpg::TransformController::getMaxParam () [virtual]
Implements libpg::Controller.
Definition at line 113 of file TransformController.cc.
References controller, and libpg::Controller::getMaxParam().
virtual void libpg::TransformController::write (std::ostream & o) [virtual]
Reimplemented from libpg::Controller.
virtual void libpg::TransformController::read (std::istream & o) [virtual]
Reimplemented from libpg::Controller.
void libpg::TransformController::reduce (Vector & , Approximator::StatsEnum) [virtual]
Add either the parameters or gradient or traces into a vector
Parameters:
v vector to store stuff into. v must be at least as big as total params/grads/traces. Will not be resized. Will not be cleared.
s whether to collect grads or params or traces
Reimplemented from libpg::Controller.
Reimplemented in libpg::NACTransform.
Definition at line 133 of file TransformController.cc.
References controller, and libpg::Controller::reduce().
void libpg::TransformController::scatter (Vector & , Approximator::StatsEnum) [virtual]
Disperse either the parameters or gradient into appropriate data structures for this class.
Parameters:
v Vector to replace current params or grads or traces. Must be correct size
s whether to restore grads or params or traces
Reimplemented from libpg::Controller.
Reimplemented in libpg::NACTransform.
Definition at line 138 of file TransformController.cc.
References controller, and libpg::Controller::scatter().
Member Data Documentation
Controller* libpg::TransformController::controller [protected]
Reimplemented in libpg::HardLimitTransform.
Definition at line 18 of file TransformController.hh.
Referenced by accumulateGrad(), batchStep(), libpg::RegularizeTransform::batchStep(), libpg::NACTransform::batchStep(), computeDirection(), computePartialsAndFeedback(), discountTrace(), getAction(), libpg::PSRTransform::getAction(), libpg::ObsWindowTransform::getAction(), libpg::NACTransform::getAction(), libpg::ImportanceSamplingController::getAction(), libpg::HMMTransform::getAction(), libpg::CatObsActionTransform::getAction(), getInputDim(), getMaxParam(), getMostProbAction(), libpg::ImportanceSamplingController::getMostProbAction(), getNumParams(), instantStep(), libpg::RegularizeTransform::instantStep(), libpg::ImportanceSamplingController::instantStep(), libpg::RegularizeTransform::penalise(), randomizeParams(), reduce(), libpg::NACTransform::reduce(), libpg::RegularizeTransform::RegularizeTransform(), resetGrad(), resetParams(), resetTrace(), libpg::ImportanceSamplingController::resetTrace(), scatter(), libpg::NACTransform::scatter(), setDiscount(), libpg::NACTransform::setDiscount(), libpg::ImportanceSamplingController::setDiscount(), setStepSize(), libpg::RegularizeTransform::setStepSize(), libpg::PSRTransform::setStepSize(), and libpg::NACTransform::updateStatistics().