The PG Library: SP38::Phase Class Reference
SP38::Phase
SP38::Phase Class Reference
#include <Phase.hh>
Public Member Functions
Phase (string id)
string getId ()
int getTotalDetectors ()
void addSignalGroup (SignalGroup *)
void addDetector (Detector *)
SignalGroup * getSignalGroup (int scatsId)
Detector * getDetector (int scatsId)
Public Attributes
SignalGroupSet signal_groups
DetectorSet detectors
Detailed Description
A Signal Phase of an intersection
Definition at line 17 of file Phase.hh.
Constructor & Destructor Documentation
SP38::Phase::Phase (string id_p)
Phase Constructor.
Definition at line 10 of file Phase.cc.
Member Function Documentation
string SP38::Phase::getId ()
Get the Phase Id.
Definition at line 17 of file Phase.cc.
Referenced by SP38::Intersection::getNextPhase(), and SP38::SP38Simulation::setNewPhase().
int SP38::Phase::getTotalDetectors ()
Returns the total of detectors for the phase.
Definition at line 24 of file Phase.cc.
References detectors.
void SP38::Phase::addSignalGroup (SignalGroup * sg)
Adds a signal group to the Phase.
Parameters:
the signal group
Definition at line 33 of file Phase.cc.
References SP38::ScatsObject::getScatsId(), getSignalGroup(), and signal_groups.
void SP38::Phase::addDetector (Detector * d)
Adds a detector to the Phase.
Parameters:
the detector
Definition at line 42 of file Phase.cc.
References detectors, getDetector(), and SP38::ScatsObject::getScatsId().
SignalGroup * SP38::Phase::getSignalGroup (int scatsId)
Gets a signal group from the Phase.
Parameters:
Signal Group's Scats ID
Definition at line 61 of file Phase.cc.
References signal_groups.
Referenced by addSignalGroup(), and SP38::SP38Simulation::setNewPhase().
Detector * SP38::Phase::getDetector (int scatsId)
Gets a Detector from the Phase.
Parameters:
Detector's Scats ID
Definition at line 51 of file Phase.cc.
References detectors.
Referenced by addDetector().
Member Data Documentation
SignalGroupSet SP38::Phase::signal_groups
Definition at line 26 of file Phase.hh.
Referenced by addSignalGroup(), getSignalGroup(), and SP38::SP38Simulation::setNewPhase().
DetectorSet SP38::Phase::detectors
Definition at line 27 of file Phase.hh.
Referenced by addDetector(), getDetector(), SP38::IntersectionHistory::getPhaseMaxDetectorThroughputBetween(), SP38::IntersectionHistory::getPhaseThroughputBetween(), and getTotalDetectors().