The PG Library: libpg::MultidimensionalLookupTable Class Reference
libpg::MultidimensionalLookupTable
libpg::MultidimensionalLookupTable Class Reference
#include <MultidimensionalLookupTable.hh>
Public Member Functions
MultidimensionalLookupTable (int observations, int outputs, int memoryLength)
virtual void doApprox (Observation &obs, Vector &output)
virtual void feedbackGrad (Observation &obs, Vector &deltas)
virtual int getInputDim ()
Protected Attributes
int maxHistory
int * powerArray
Detailed Description
A lookup table that accepts as inputs a finite windows of past history
Definition at line 9 of file MultidimensionalLookupTable.hh.
Constructor & Destructor Documentation
libpg::MultidimensionalLookupTable::MultidimensionalLookupTable (int observations, int outputs, int maxHistory)
Construct a FiniteMemoryLookup table.
Parameters:
observations,the range of observation values.
outputs,the number of outputs (actions) to map the observations to.
memoryLength,the number of past observations being remembered.
Definition at line 33 of file MultidimensionalLookupTable.cc.
References libpg::LookupTable::actions, libpg::LookupTableBatch::grads, libpg::LookupTable::params, libpg::power(), and libpg::LookupTable::trace.
Member Function Documentation
void libpg::MultidimensionalLookupTable::doApprox (Observation & obs, Vector & output) [virtual]
Simply return a copy of column associated with obs in output
Parameters:
obs observation matrix, in this case always 1x1
output will be populated with real values action preferences
Reimplemented from libpg::LookupTable.
Definition at line 50 of file MultidimensionalLookupTable.cc.
References libpg::Observation::getAgent(), libpg::Observation::getFeatures(), sumAndPlot::i, maxHistory, libpg::LookupTable::observations, libpg::LookupTable::params, and libpg::power().
void libpg::MultidimensionalLookupTable::feedbackGrad (Observation & obs, Vector & deltas) [virtual]
Feed back a gradient signal. Final gradient accumulated directly to trace object in policy.
Reimplemented from libpg::LookupTable.
Definition at line 65 of file MultidimensionalLookupTable.cc.
References libpg::Observation::getAgent(), libpg::Observation::getFeatures(), sumAndPlot::i, maxHistory, libpg::LookupTable::observations, libpg::power(), and libpg::LookupTable::trace.
int libpg::MultidimensionalLookupTable::getInputDim () [virtual]
An input or each element of history
Reimplemented from libpg::LookupTable.
Definition at line 80 of file MultidimensionalLookupTable.cc.
References maxHistory.
Member Data Documentation
int libpg::MultidimensionalLookupTable::maxHistory [protected]
Definition at line 12 of file MultidimensionalLookupTable.hh.
Referenced by doApprox(), feedbackGrad(), and getInputDim().
int* libpg::MultidimensionalLookupTable::powerArray [protected]
Definition at line 13 of file MultidimensionalLookupTable.hh.