The PG Library: libpg::OLBFGS Class Reference
libpg::OLBFGS
libpg::OLBFGS Class Reference
#include <OLBFGS.hh>
Public Member Functions
OLBFGS (Controller *controller, size_t memLength)
virtual void discountTrace ()
virtual void getAction (Observation &obs, Vector &action, bool computeGrad=true)
virtual void getMostProbAction (Observation &obs, Vector &action)
virtual void setStepSize (double s)
virtual void resetTrace ()
virtual void resetGrad ()
virtual void accumulateGrad (double reward, Observation &newObs)
virtual void instantStep (Vector &reward)
virtual void setDiscount (double d)
Protected Types
typedef std::list
< Vector >::iterator vecListIt
typedef std::list
< Vector >
::reverse_iterator vecListRIt
typedef std::list
< double >::iterator rhoListIt
typedef std::list
< double >
::reverse_iterator rhoListRIt
Protected Member Functions
void init ()
Vector updateDirection (Vector &s, Vector &y, Vector &newP)
void updatePara ()
Protected Attributes
int iter
size_t memLength
std::list< Vector > sArray
std::list< Vector > yArray
std::list< double > rho
Vector p
Vector y
Vector s
Vector g
Vector dummyAction
Observation lastObs
Vector trace
int OLBFGSSteps
Vector lastAction
double stepSize
double discountFactor
Detailed Description
Definition at line 10 of file OLBFGS.hh.
Member Typedef Documentation
typedef std::list<Vector>::iterator libpg::OLBFGS::vecListIt [protected]
Definition at line 15 of file OLBFGS.hh.
typedef std::list<Vector>::reverse_iterator libpg::OLBFGS::vecListRIt [protected]
Definition at line 16 of file OLBFGS.hh.
typedef std::list<double>::iterator libpg::OLBFGS::rhoListIt [protected]
Definition at line 17 of file OLBFGS.hh.
typedef std::list<double>::reverse_iterator libpg::OLBFGS::rhoListRIt [protected]
Definition at line 18 of file OLBFGS.hh.
Constructor & Destructor Documentation
OLBFGS::OLBFGS (Controller * controller, size_t memLength)
Parameters:
controller the underlying congtroller to BFGS'ify
memLength the length of memory in BFGS
Definition at line 9 of file OLBFGS.cc.
References libpg::Controller::getNumParams(), p, resetGrad(), s, trace, and y.
Member Function Documentation
void libpg::OLBFGS::init () [protected]
Vector OLBFGS::updateDirection (Vector & s, Vector & y, Vector & newP) [protected]
Definition at line 24 of file OLBFGS.cc.
References sumAndPlot::i, OLBFGS::rho, OLBFGS::sArray, and OLBFGS::yArray.
void libpg::OLBFGS::updatePara () [protected]
void OLBFGS::discountTrace () [virtual]
OLBFGS implicitly removes need for a trace
Reimplemented from libpg::TransformController.
Definition at line 83 of file OLBFGS.cc.
void OLBFGS::getAction (Observation & obs, Vector & action, bool computeGrad = true) [virtual]
Do getAction call twice, with different state/action pairs. The "standard" gradient is computed here. The second sample comes from instantStep().
Reimplemented from libpg::TransformController.
Definition at line 104 of file OLBFGS.cc.
References libpg::Observation::getFeatures().
virtual void libpg::OLBFGS::getMostProbAction (Observation & obs, Vector & action) [virtual]
Just pass to underlying controller
Parameters:
Observation vector
empty vector to load with the most probably action
Reimplemented from libpg::TransformController.
Definition at line 50 of file OLBFGS.hh.
References NYI.
void OLBFGS::setStepSize (double stepSize) [virtual]
It helps for OLBFGS to know what the step size is. Just keep a local copy
Reimplemented from libpg::TransformController.
Definition at line 136 of file OLBFGS.cc.
void OLBFGS::resetTrace () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 119 of file OLBFGS.cc.
void OLBFGS::resetGrad () [virtual]
Reimplemented from libpg::TransformController.
Definition at line 124 of file OLBFGS.cc.
References OLBFGS::rho, OLBFGS::sArray, and OLBFGS::yArray.
Referenced by OLBFGS().
void OLBFGS::accumulateGrad (double reward, Observation & newObs) [virtual]
Definition at line 215 of file OLBFGS.cc.
void OLBFGS::instantStep (Vector & reward) [virtual]
Now that we have a reward we can compute the instant gradients to be used by OLBFGS. We have to compute a second gradient by recalling getAction() with the same observation/action pair chosen before.
Reimplemented from libpg::TransformController.
Definition at line 147 of file OLBFGS.cc.
References OLBFGS::g, OLBFGS::p, sumAndPlot::s, and OLBFGS::updateDirection().
void OLBFGS::setDiscount (double d) [virtual]
OLBFGS takes over the discounting of the trace, but does pass on the new discount factor to the child controller.
Reimplemented from libpg::TransformController.
Definition at line 93 of file OLBFGS.cc.
Member Data Documentation
int libpg::OLBFGS::iter [protected]
Definition at line 20 of file OLBFGS.hh.
size_t libpg::OLBFGS::memLength [protected]
Definition at line 21 of file OLBFGS.hh.
std::list<Vector> libpg::OLBFGS::sArray [protected]
Definition at line 22 of file OLBFGS.hh.
std::list<Vector> libpg::OLBFGS::yArray [protected]
Definition at line 22 of file OLBFGS.hh.
std::list<double> libpg::OLBFGS::rho [protected]
Definition at line 23 of file OLBFGS.hh.
Vector libpg::OLBFGS::p [protected]
Definition at line 24 of file OLBFGS.hh.
Referenced by OLBFGS().
Vector libpg::OLBFGS::y [protected]
Definition at line 24 of file OLBFGS.hh.
Referenced by OLBFGS().
Vector libpg::OLBFGS::s [protected]
Definition at line 24 of file OLBFGS.hh.
Referenced by OLBFGS().
Vector libpg::OLBFGS::g [protected]
Definition at line 24 of file OLBFGS.hh.
Vector libpg::OLBFGS::dummyAction [protected]
Definition at line 24 of file OLBFGS.hh.
Observation libpg::OLBFGS::lastObs [protected]
Definition at line 25 of file OLBFGS.hh.
Vector libpg::OLBFGS::trace [protected]
Definition at line 26 of file OLBFGS.hh.
Referenced by OLBFGS().
int libpg::OLBFGS::OLBFGSSteps [protected]
Definition at line 27 of file OLBFGS.hh.
Vector libpg::OLBFGS::lastAction [protected]
Definition at line 28 of file OLBFGS.hh.
double libpg::OLBFGS::stepSize [protected]
Definition at line 30 of file OLBFGS.hh.
double libpg::OLBFGS::discountFactor [protected]
Definition at line 31 of file OLBFGS.hh.