The PG Library: SP38::ScenarioHistory Class Reference
SP38::ScenarioHistory
SP38::ScenarioHistory Class Reference
#include <ScenarioHistory.hh>
Public Member Functions
ScenarioHistory (Scenario *, int)
IntersectionHistory * getIntersectionHistory (Intersection *)
void setInitialState ()
int getCurrentCycleDuration ()
int getCurrentCycle ()
void setCurrentTime (int)
int getCurrentTime ()
Public Attributes
IntersectionHistorySet intersections_history
Detailed Description
Simulation History for a Scenario. You cannont reuse a simulation history object. It's only for one simulation.
Definition at line 16 of file ScenarioHistory.hh.
Constructor & Destructor Documentation
SP38::ScenarioHistory::ScenarioHistory (Scenario * sc, int m_a_i)
ScenarioHistory constructor.
Definition at line 8 of file ScenarioHistory.cc.
References SP38::Scenario::getCycleDuration(), sumAndPlot::i, and SP38::Scenario::intersections.
Member Function Documentation
IntersectionHistory * SP38::ScenarioHistory::getIntersectionHistory (Intersection * i)
Gets the history of an intersection.
Definition at line 49 of file ScenarioHistory.cc.
References intersections_history.
Referenced by SP38::SP38Simulation::getCurrentPhase(), SP38::SP38Simulation::getCurrentPhaseDuration(), SP38::SP38Simulation::getDetectorCountBetween(), SP38::SP38Simulation::getDetectorMaxThroughput(), SP38::SP38Simulation::getIntersectionMaxThroughput(), SP38::SP38Simulation::getPhaseDurationBetween(), SP38::SP38Simulation::getPhaseMaxDetectorThroughputBetween(), SP38::SP38Simulation::getPhaseThroughputBetween(), SP38::SP38Simulation::isDetectorActive(), and SP38::SP38Simulation::setNewPhase().
void SP38::ScenarioHistory::setInitialState ()
Sets the history as a valid initial state for a simulation.
Definition at line 17 of file ScenarioHistory.cc.
References intersections_history.
Referenced by SP38::SP38Simulation::doStep().
int SP38::ScenarioHistory::getCurrentCycleDuration ()
Return how many steps the current cycle has lasted.
Definition at line 42 of file ScenarioHistory.cc.
References SP38::Scenario::getCycleDuration().
Referenced by SP38::SP38Simulation::getCurrentCycleDuration().
int SP38::ScenarioHistory::getCurrentCycle ()
void SP38::ScenarioHistory::setCurrentTime (int t)
Set the current time.
Parameters:
current time
Definition at line 26 of file ScenarioHistory.cc.
References SP38::Scenario::getCycleDuration().
Referenced by SP38::SP38Simulation::doStep().
int SP38::ScenarioHistory::getCurrentTime ()
Get the current time.
Definition at line 35 of file ScenarioHistory.cc.
Member Data Documentation
IntersectionHistorySet SP38::ScenarioHistory::intersections_history
Definition at line 28 of file ScenarioHistory.hh.
Referenced by getIntersectionHistory(), and setInitialState().